### ISSUE TITLE
Scala 3 + Akka streams + worksheet not working

### ISSUE THREAD

**Issue by Swoorup** [scalameta/metals#2525] opened 2021-02-18 10:34 UTC
**Describe the bug**

Scala 3 Worksheet does not work when using Akka Streams. 

**To Reproduce**

Execute the following as worksheet file:

```scala
import akka.actor.ActorSystem
import akka._
import akka.stream.scaladsl._
import com.typesafe.config.ConfigFactory
import java.io.File
import akka.actor._
import scala.concurrent.Await
import scala.concurrent.duration.DurationInt

implicit val system: ActorSystem = ActorSystem("QuickStart")
val source: Source[Int, NotUsed] = Source(1 to 100)
val future = source.runWith(Sink.foreach(println))
Await.result(future, 3.seconds)
```

**Expected behavior**

Worksheet evaluates successfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/3408009/108344156-e6bbdc00-7230-11eb-9037-d910006cb48c.png)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.10
- Scala version: 3.0.0-M3

**Additional context**

Also attached a sample sbt solution to reproduce the issue.

[test.zip](https://github.com/scalameta/metals/files/6002106/test.zip)

**Comment by tgodzik** [comment] 2021-02-18 10:37
Thanks for reporting and the reproduction!

**Comment by jvdp** [comment] 2021-02-25 15:23
I think it's not related to Scala 3 nor Akka Streams. I was able to get a bit further by resolving the configuration manually:

```scala
import $dep.`com.typesafe.akka::akka-actor:2.6.13`
import akka.actor.Actor
import com.typesafe.config.ConfigFactory
import akka.actor.ActorSystem

val config = ConfigFactory
  .load()
  .withFallback(ConfigFactory.parseResources(Actor.getClass(), "/version.conf"))
  .withFallback(
    ConfigFactory.parseResources(Actor.getClass(), "/reference.conf")
  )
  .resolve()

implicit val system = ActorSystem("worksheet", config)
```

This results in another error:
```
java.lang.ClassNotFoundException: akka.event.DefaultLoggingFilter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at akka.actor.ReflectiveDynamicAccess.$anonfun$getClassFor$1(ReflectiveDynamicAccess.scala:29)
	at scala.util.Try$.apply(Try.scala:210)
	at akka.actor.ReflectiveDynamicAccess.getClassFor(ReflectiveDynamicAccess.scala:28)
	at akka.actor.ReflectiveDynamicAccess.createInstanceFor(ReflectiveDynamicAccess.scala:47)
	at akka.actor.ActorSystemImpl.<init>(ActorSystem.scala:922)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
	at akka.actor.ActorSystem$.apply(ActorSystem.scala:290)
	at repl.MdocSession$App.<init>(akka.worksheet.sc:29)
	at repl.MdocSession$.app(akka.worksheet.sc:3)
```

Something classloader-y, at least...

**Comment by Swoorup** [comment] 2021-02-28 02:47
Yeah this is just an example. I found few other libraries like this one 
https://index.scala-lang.org/scalikejdbc/csvquery/csvquery/1.5.0?target=_2.13 

to not work at all ☹️

**Comment by ckipp01** [comment] 2021-02-28 09:03
> Yeah this is just an example. I found few other libraries like this one
> [index.scala-lang.org/scalikejdbc/csvquery/csvquery/1.5.0?target=_2.13](https://index.scala-lang.org/scalikejdbc/csvquery/csvquery/1.5.0?target=_2.13)
> 
> to not work at all ☹️

So this case is actually a different one. I just tried this out, and it looks like if you switch to jdk8 this should work fine. It's the same issue that we have outlined here https://github.com/scalameta/metals/issues/2187

**Comment by tgodzik** [comment] 2021-03-25 16:39
Ok, I think I got it fixed in https://github.com/scalameta/mdoc/pull/473

**Comment by Swoorup** [comment] 2021-03-25 17:10
Wow sounds really cool. 2021 seems like a great year for Scala 3

**Comment by tgodzik** [comment] 2021-04-02 17:54
Seems it still doesn't not work for `akka-stream`, which are used in the first example. Getting:
```
akka2:13:1: error: java.lang.NoSuchMethodError: com.typesafe.config.Config.getDuration(Ljava/lang/String;)Ljava/time/Duration;
       at akka.stream.SystemMaterializer.<init>(SystemMaterializer.scala:53)
       at akka.stream.SystemMaterializer$.createExtension(SystemMaterializer.scala:39)
       at akka.stream.SystemMaterializer$.createExtension(SystemMaterializer.scala:32)
       at akka.actor.ActorSystemImpl.registerExtension(ActorSystem.scala:1158)
       at akka.actor.ActorSystemImpl.$anonfun$loadExtensions$1(ActorSystem.scala:1201)
       at scala.collection.Iterator.foreach(Iterator.scala:943)
       at scala.collection.Iterator.foreach$(Iterator.scala:943)
       at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
       at scala.collection.IterableLike.foreach(IterableLike.scala:74)
       at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
       at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
       at akka.actor.ActorSystemImpl.loadExtensions$1(ActorSystem.scala:1195)
       at akka.actor.ActorSystemImpl.loadExtensions(ActorSystem.scala:1214)
       at akka.actor.ActorSystemImpl.liftedTree2$1(ActorSystem.scala:1035)
      at akka.actor.ActorSystemImpl._start$lzycompute(ActorSystem.scala:1022)
       at akka.actor.ActorSystemImpl._start(ActorSystem.scala:1022)
       at akka.actor.ActorSystemImpl.start(ActorSystem.scala:1045)
       at akka.actor.ActorSystem$.apply(ActorSystem.scala:272)
       at akka.actor.ActorSystem$.apply(ActorSystem.scala:316)
       at akka.actor.ActorSystem$.apply(ActorSystem.scala:260)
       at repl.MdocSession$App.<init>(akka2.scala:35)
       at repl.MdocSession$.app(akka2.scala:3)
```

:/

**Closed** 2021-04-03 09:40 UTC
Labels: bug, fixed-upstream, worksheets

**Comment by HyoungsungKim** [comment] 2022-03-23 09:47
Hi How did you import akka in vscode worksheet?

**Comment by HyoungsungKim** [comment] 2022-03-23 10:05
@ckipp01 I really really thanks for your fast reply!
