### ISSUE TITLE
Metals spawns lots of blocked threads on some files

### ISSUE THREAD

**Issue by rreckel** [scalameta/metals#724] opened 2019-05-17 13:00 UTC
Sometimes, saving files, forces metals to spawn hundreds of threads, which are blocked immediately.

The stacktrace of the blocked thread:
```
scala.meta.internal.pc.CompilerAccess.withNonCancelableCompiler(CompilerAccess.scala:79)
scala.meta.internal.pc.ScalaPresentationCompiler.hover(ScalaPresentationCompiler.scala:113)
scala.meta.internal.metals.Compilers.$anonfun$hover$1(Compilers.scala:154)
scala.meta.internal.metals.Compilers$$Lambda$902/214800689.apply(Unknown Source)
scala.meta.internal.metals.Compilers.$anonfun$withPC$1(Compilers.scala:229)
scala.meta.internal.metals.Compilers$$Lambda$941/1967279211.apply(Unknown Source)
scala.Option.map(Option.scala:163)
scala.meta.internal.metals.Compilers.withPC(Compilers.scala:224)
scala.meta.internal.metals.Compilers.hover(Compilers.scala:152)
scala.meta.internal.metals.MetalsLanguageServer.$anonfun$hover$1(MetalsLanguageServer.scala:715)
scala.meta.internal.metals.MetalsLanguageServer$$Lambda$897/1567444668.apply(Unknown Source)
scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:24)
scala.meta.internal.metals.CancelTokens$$$Lambda$900/1347923837.apply(Unknown Source)
scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
scala.concurrent.Future$$$Lambda$75/373593858.apply(Unknown Source)
scala.util.Success.$anonfun$map$1(Try.scala:255)
scala.util.Success.map(Try.scala:213)
scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
scala.concurrent.Future$$Lambda$76/1949247242.apply(Unknown Source)
scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
scala.concurrent.impl.Promise$$Lambda$77/292159033.apply(Unknown Source)
scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)
```

Sadly it is impossible to reproduce this behaviour or to know what is causing this problem.
It happens when there is a compilation failure involved.

The usual workaround, is to restart metals.

OS: Mac OS X 10.14.4
JVM: JDK 1.8.0_201
Metals: 0.5.2

**Comment by olafurpg** [comment] 2019-05-22 09:08
Thank you for reporting! Closing this as a duplicate of #723

**Closed by olafurpg** 2019-05-22 09:08 UTC
