### ISSUE TITLE
Type parameters from extension receiver not forwarded to completions in scala 3

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#4184] opened 2022-07-22 08:47 UTC
### Describe the bug

If the signature of a method added by an extension or an implicit conversion refers to a type parameter which should be fixed by the method receiver, the type is not substituted in code completions, e.g. for
```scala
extension[T](opt: Option[T])
  def append(x: T): Seq[T] = opt.toSeq :+ x

val x = Some(1).app@@
```
or
```scala
implicit class FooOps[T](opt: Option[T]):
  def append(x: T): Seq[T] = opt.toSeq :+ x

val x = Some(1).app@@
```
the suggested completion is
```scala
append(x: T): Seq[T]
```

### Expected behavior

Type parameters from the extension receiver should be properly propagated, e.g. in the given example the suggested completion should be
```scala
append(x: Int): Seq[Int]
```

### Version of Metals

0.11.7+60-d9677cff-SNAPSHOT

**Comment by tgodzik** [comment] 2022-07-22 11:19
I think we could do 2 things:
- copy over the logic from https://github.com/lampepfl/dotty/pull/11187/files or try to reuse it in some way
- make the interface for completions a bit better (@prolativ already raised na issue): https://github.com/lampepfl/dotty/issues/15730. We can use it for the newer versions of compiler

**Comment by dos65** [comment] 2022-07-22 12:22
@tgodzik @prolativ I would choose to not to change interfaces. Actually, the are good enough to use.
The issue is that by some reason we are getting a symbol with not-precise denot or info. But it's possible to fix

We can reuse this thing that we have in metals:
https://github.com/scalameta/metals/blob/d9677cff9df3cbd3af977470e3513334abd74b53/mtags/src/main/scala-3/scala/meta/internal/mtags/MtagsEnrichments.scala#L132-L146

**Comment by prolativ** [comment] 2022-07-22 12:41
The point is that in a case like this it's impossible to get the full type signature from a symbol - one needs the entire typed tree of the extension receiver

**Comment by dos65** [comment] 2022-07-22 13:26
@prolativ but it's possible on dotty side. I only meant that it would be nice to change public interfaces

**Comment by prolativ** [comment] 2022-07-22 13:33
`I would choose to not to change interfaces`
`it would be nice to change public interfaces`
Now I'm quite confused which solution you would prefer 😕

**Comment by dos65** [comment] 2022-07-22 13:36
opps :smile: 

I mean do NOT to change

**Comment by rochala** [comment] 2024-02-29 13:06
This is actually fixed with https://github.com/lampepfl/dotty/pull/18914

**Closed by rochala** 2024-02-29 13:06 UTC
Labels: bug, upstream-fix-needed
