### ISSUE TITLE
Problems with config-scoped inter-project dependencies and SBT build server

### ISSUE THREAD

**Issue by asflierl** [scalameta/metals#2625] opened 2021-03-19 09:35 UTC
**Describe the bug**

When editing the test sources of a project A that depends on another project B in test scope (that itself depends on project C), the symbols of project B and project C are not "visible" to Metals, i.e. not available for code completion and organize imports will remove imports from project B even though they are used.

**To Reproduce**

1. Clone this minimal example project: https://github.com/asflierl/project-level-test-dependency.git
2. Start SBT & VSCode, switch to SBT as build server and reload the SBT project
3. Open the file `seriousApp/src/test/scala/SeriousAppSpec.scala`
4. Remove a few letters from "wibble" in line 12 or "candy" in line 14, then trigger code completion
5. no available completions from Metals
6. trigger "organize imports" 
7. the imports in line 4 and 5 are removed even though they are used

**Expected behavior**

Code completions for symbols from project B and C are available when editing test sources of project A.
Used imports are not removed.
(Both work fine with Bloop as build server.)

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.0

**Additional context**

Transitive library dependencies seem to work fine. Try e.g. completing "Specification" (line 8). It works, even though Specs2 is a dependency of project B.

**Comment by adpi2** [comment] 2021-03-19 13:37
@asflierl  thanks for reporting

There are 2 cases:

1. sbt is reloaded manually (`sbtn reload` in the console)
In this case Metals does not even know that sbt has been reloaded and which projects have changed. We could have an "auto-import" solution once sbt has implemented the [`buildTarget/didChange` notification](https://build-server-protocol.github.io/docs/specification.html#build-target-changed-notification), but it is not yet the case.

2. you click the `Import changes` button on the `sbt build needs to be re-imported` pop-up
In this case Metals should probably re-import everything after reloading sbt, but it is not optimal because some projects may not have changed. Again it would be better to have the [`buildTarget/didChange` notification](https://build-server-protocol.github.io/docs/specification.html#build-target-changed-notification) implemented in sbt.

You can solve this problem temporarily by clicking the `connect to build server` button. It will reconnect to sbt and re-import everything.

**Comment by tgodzik** [comment] 2021-03-19 20:56
Thanks for reporting! We should be able to investigate it further using you reproduction :tada:

**Comment by tgodzik** [comment] 2021-03-22 09:46
After digging in a bit this seems to be an issue with sbt, raised it there https://github.com/sbt/sbt/issues/6410

**Comment by adpi2** [comment] 2021-03-24 09:17
This bug is fixed upstream by https://github.com/sbt/sbt/pull/6414. It will be released in sbt 1.5.0 in two weeks or something.

**Closed by adpi2** 2021-03-24 09:17 UTC
Labels: BSP, bug, sbt server, upstream-fix-needed
