### ISSUE TITLE
java.util.concurrent.ExecutionException: Boxed InterruptedException

### ISSUE THREAD

**Issue by oharboe** [scalameta/metals#1465] opened 2020-02-25 08:48 UTC
**Describe the bug**
When I try to import my scala project into Visual Studio Code, I get an exception

This used to work, but has suddenly stopped working. 

**To Reproduce**
1. Go to Visual Studio Code
2. Click on Import Build
3. Scroll down to "output" log

```
Java home: /usr/lib/jvm/java-1.8.0-openjdk-amd64
/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j/0.8.1/org.eclipse.lsp4j-0.8.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/thoughtworks/qdox/qdox/2.0.0/qdox-2.0.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.0/config-1.4.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.12/2.0.4/jsoniter-scala-core_2.12-2.0.4.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.12/0.2.0/sourcecode_2.12-0.2.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/h2database/h2/1.4.200/h2-1.4.200.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/upickle-core_2.12/0.9.7/upickle-core_2.12-0.9.7.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/io/github/soc/directories/11/directories-11.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/thesamet/scalapb/lenses_2.12/0.9.0/lenses_2.12-0.9.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/fastparse-utils_2.12/1.0.1/fastparse-utils_2.12-1.0.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/outr/perfolation-macros_2.12/1.1.5/perfolation-macros_2.12-1.1.5.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/checkerframework/checker-qual/2.10.0/checker-qual-2.10.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/openjdk/jol/jol-core/0.9/jol-core-0.9.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/trees_2.12/4.3.0/trees_2.12-4.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.10/scala-compiler-2.12.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/xtend/org.eclipse.xtend.lib/2.18.0/org.eclipse.xtend.lib-2.18.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/ujson_2.12/0.9.7/ujson_2.12-0.9.7.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/mdoc-interfaces/2.1.1/mdoc-interfaces-2.1.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/errorprone/error_prone_annotations/2.3.4/error_prone_annotations-2.3.4.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/wildfly/common/wildfly-common/1.5.2.Final/wildfly-common-1.5.2.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.2/jna-4.5.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna-platform/4.5.2/jna-platform-4.5.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/io/get-coursier/interface/0.0.16/interface-0.0.16.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/outr/scribe-slf4j_2.12/2.7.10/scribe-slf4j_2.12-2.7.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/outr/scribe-macros_2.12/2.7.10/scribe-macros_2.12-2.7.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bsp4j/2.0.0-M4%2B10-61e61e87/bsp4j-2.0.0-M4%2B10-61e61e87.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/thesamet/scalapb/scalapb-runtime_2.12/0.9.0/scalapb-runtime_2.12-0.9.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.10/scala-reflect-2.12.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.generator/0.8.1/org.eclipse.lsp4j.generator-0.8.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/pprint_2.12/0.5.8/pprint_2.12-0.5.8.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/xtext/org.eclipse.xtext.xbase.lib/2.18.0/org.eclipse.xtext.xbase.lib-2.18.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.12/2.1.3/fastparse_2.12-2.1.3.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/wildfly/client/wildfly-client-config/1.0.0.Final/wildfly-client-config-1.0.0.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/xtend/org.eclipse.xtend.lib.macro/2.18.0/org.eclipse.xtend.lib.macro-2.18.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/mtags_2.12.10/0.8.0/mtags_2.12.10-0.8.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jboss/logging/jboss-logging/3.4.0.Final/jboss-logging-3.4.0.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/ipcsocket/ipcsocket/1.0.0/ipcsocket-1.0.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/parsers_2.12/4.3.0/parsers_2.12-4.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/fansi_2.12/0.2.8/fansi_2.12-0.2.8.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jboss/xnio/xnio-api/3.7.7.Final/xnio-api-3.7.7.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc.debug/0.8.1/org.eclipse.lsp4j.jsonrpc.debug-0.8.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/mtags-interfaces/0.8.0/mtags-interfaces-0.8.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.7.1/protobuf-java-3.7.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.jsonrpc/0.8.1/org.eclipse.lsp4j.jsonrpc-0.8.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/scalafmt-dynamic_2.12/2.3.2/scalafmt-dynamic_2.12-2.3.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/flywaydb/flyway-core/6.1.4/flyway-core-6.1.4.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bloop-config_2.12/1.4.0-RC1/bloop-config_2.12-1.4.0-RC1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/guava/guava/28.2-jre/guava-28.2-jre.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scalap/2.12.10/scalap-2.12.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-collection-compat_2.12/2.1.3/scala-collection-compat_2.12-2.1.3.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/scalameta_2.12/4.3.0/scalameta_2.12-4.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/eclipse/lsp4j/org.eclipse.lsp4j.debug/0.8.1/org.eclipse.lsp4j.debug-0.8.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/outr/perfolation_2.12/1.1.5/perfolation_2.12-1.1.5.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/bloop-launcher_2.12/1.4.0-RC1/bloop-launcher_2.12-1.4.0-RC1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.9.0/scala-java8-compat_2.12-0.9.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/scalafmt-interfaces/2.3.2/scalafmt-interfaces-2.3.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/geny_2.12/0.5.0/geny_2.12-0.5.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/outr/scribe_2.12/2.7.10/scribe_2.12-2.7.10.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/semanticdb-scalac-core_2.12.10/4.3.0/semanticdb-scalac-core_2.12.10-4.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/io/methvin/directory-watcher/0.8.0/directory-watcher-0.8.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/metals_2.12/0.8.0/metals_2.12-0.8.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/fastparse_2.12/1.0.1/fastparse_2.12-1.0.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalameta/common_2.12/4.3.0/common_2.12-4.3.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jboss/threads/jboss-threads/2.3.0.Beta2/jboss-threads-2.3.0.Beta2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jsoup/jsoup/1.12.1/jsoup-1.12.1.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/lz4/lz4-java/1.7.0/lz4-java-1.7.0.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/io/undertow/undertow-core/2.0.29.Final/undertow-core-2.0.29.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jboss/xnio/xnio-nio/3.7.7.Final/xnio-nio-3.7.7.Final.jar:/home/oyvind/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.10/scala-library-2.12.10.jar


INFO  logging to file /home/oyvind/ascenium/ascenium/hardware/aptos/.metals/metals.log
INFO  started: Metals version 0.8.0 in workspace '/home/oyvind/ascenium/ascenium/hardware/aptos'
INFO  time: initialize in 0.24s
Initializing Scala Debugger
WARN  no build target for: /home/oyvind/ascenium/ascenium/hardware/aptos/src/main/scala/ascenium/avalon/AptosAvalonMMSlave.scala
INFO  running '/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals4266470362928566051/sbt-launch.jar set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
INFO  skipping build import with status 'Started'
INFO  [info] Loading global plugins from /home/oyvind/.sbt/1.0/plugins
INFO  [info] Loading settings for project aptos-build from plugins.sbt,metals.sbt ...
INFO  [info] Loading project definition from /home/oyvind/ascenium/ascenium/hardware/aptos/project
INFO  [info] Loading settings for project aptos from build.sbt ...
INFO  [info] Set current project to Aptos (in build file:/home/oyvind/ascenium/ascenium/hardware/aptos/)
INFO  [info] Defining Global / bloopExportJarClassifiers
INFO  [info] The new value will be used by ThisBuild / bloopExportJarClassifiers
INFO  [info] Reapplying settings...
INFO  [info] Set current project to Aptos (in build file:/home/oyvind/ascenium/ascenium/hardware/aptos/)
INFO  [success] Generated .bloop/aptos-test.json
INFO  [success] Generated .bloop/aptos.json
INFO  [success] Total time: 1 s, completed Feb 25, 2020 9:42:41 AM
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 10s
INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/oyvind/.cache/metals/bsp.trace.json
INFO  time: connected to build server in 0.15s
INFO  Connected to Build server v1.4.0-RC1
WARN  Could not find java sources in Some(/usr/lib/jvm/java-1.8.0-openjdk-amd64). Java symbols will not be available.
INFO  time: indexed workspace in 1.69s
INFO  Deduplicating compilation of aptos from bsp client 'Metals 0.8.0' (since 21m 2.179s)
INFO  running '/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Djline.terminal=jline.UnsupportedTerminal -Dsbt.log.noformat=true -Dfile.encoding=UTF-8 -jar /tmp/metals6309795045859104765/sbt-launch.jar set bloopExportJarClassifiers in Global := Some(Set("sources")) bloopInstall'
INFO  [info] Loading global plugins from /home/oyvind/.sbt/1.0/plugins
INFO  [info] Loading settings for project aptos-build from plugins.sbt,metals.sbt ...
INFO  [info] Loading project definition from /home/oyvind/ascenium/ascenium/hardware/aptos/project
INFO  [info] Loading settings for project aptos from build.sbt ...
INFO  [info] Set current project to Aptos (in build file:/home/oyvind/ascenium/ascenium/hardware/aptos/)
INFO  [info] Defining Global / bloopExportJarClassifiers
INFO  [info] The new value will be used by ThisBuild / bloopExportJarClassifiers
INFO  [info] Reapplying settings...
INFO  [info] Set current project to Aptos (in build file:/home/oyvind/ascenium/ascenium/hardware/aptos/)
INFO  [success] Generated .bloop/aptos-test.json
INFO  [success] Generated .bloop/aptos.json
INFO  [success] Total time: 0 s, completed Feb 25, 2020 9:42:51 AM
INFO  build tool exit: 0
INFO  time: ran 'sbt bloopInstall' in 6.42s
INFO  disconnected: build server
ERROR Failed to connect with build server, no functionality will work.
java.util.concurrent.ExecutionException: Boxed InterruptedException
	at scala.concurrent.impl.Promise$.resolver(Promise.scala:86)
	at scala.concurrent.impl.Promise$.scala$concurrent$impl$Promise$$resolveTry(Promise.scala:79)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:92)
	at scala.concurrent.java8.FuturesConvertersImpl$P.accept(FutureConvertersImpl.scala:89)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
	at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:20)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:114)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:54)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:49)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.InterruptedException
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$3(BuildServerConnection.scala:145)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at scala.util.Try$.apply(Try.scala:213)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$register$2(BuildServerConnection.scala:145)
	at scala.meta.internal.metals.Cancelable$$anon$1.cancel(Cancelable.scala:17)
	at scala.meta.internal.metals.Cancelable$.$anonfun$cancelAll$1(Cancelable.scala:28)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.meta.internal.metals.Cancelable$.cancelAll(Cancelable.scala:27)
	at scala.meta.internal.metals.MutableCancelable.cancel(MutableCancelable.scala:20)
	at scala.meta.internal.metals.BuildServerConnection.cancel(BuildServerConnection.scala:114)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1(BuildServerConnection.scala:54)
	at scala.meta.internal.metals.BuildServerConnection.$anonfun$shutdown$1$adapted(BuildServerConnection.scala:49)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/oyvind/.cache/metals/bsp.trace.json
INFO  Connected to Build server v1.4.0-RC1
WARN  Could not find java sources in Some(/usr/lib/jvm/java-1.8.0-openjdk-amd64). Java symbols will not be available.
INFO  time: indexed workspace in 0.26s
INFO  Deduplicating compilation of aptos from bsp client 'Metals 0.8.0' (since 21m 10.862s)

```

**Expected behavior**

No error message

**Screenshots**

![image](https://user-images.githubusercontent.com/2798822/75230328-ba9f8380-57b3-11ea-84dd-4acd26346e01.png)

**Installation:**

- Operating system: Ubuntu 18.04
- Editor: Visual Studio Code 1.42.1
- Metals version: v0.8.0
- Scala Metals plugin v. 1.7.8

**Additional context**

**Search terms**

**Comment by oharboe** [comment] 2020-02-25 08:51
Strange.... when I try to look at the Java version, I see Java version 8 in the logs, but in settings I find Java version 11

![image](https://user-images.githubusercontent.com/2798822/75230617-40bbca00-57b4-11ea-906e-55aba09cdeba.png)

**Comment by oharboe** [comment] 2020-02-25 08:56
I'm not intentionally trying to use Java 8, so I uninstalled all openjdk-8-* ubuntu packages.

Then I get this error message:

![image](https://user-images.githubusercontent.com/2798822/75230964-f25afb00-57b4-11ea-8b6e-14df24c24443.png)

**Comment by oharboe** [comment] 2020-02-25 08:59
Aha!

It turns out my workspace setting was using Java 8.

Once I fixed that it worked.

I consider this "problem" solved, so I'm closing this issue.

Sorry for the noise, I can only hope someone will save time by googling this solution :-)

**Comment by akilegaspi** [comment] 2020-03-10 05:46
I'm quite curious on what actually causes this problem, I'm on Java 8 and this is also happening to me.

**Comment by oharboe** [comment] 2020-03-10 06:18
@akilegaspi  To my understanding, Java 8 is no longer supported, so unless this can be proven to be a problem on a newer Java, I don't expect the problem to be chased down.

**Comment by ckipp01** [comment] 2020-03-10 10:04
I'm going to reopen this up. I've been consistently hitting on this as well. When I get a bit of free time I'll try to narrow down what is going this to give a more accurate minimal reproduction.

> Java 8 is no longer supported

I'm not sure if this is aimed at Metals or not, however, we still support Java 8.

**Comment by oharboe** [comment] 2020-03-10 21:25
@ckipp01  Java 8 has until December 2020... https://www.oracle.com/java/technologies/java-se-support-roadmap.html

**Comment by gabro** [comment] 2020-03-19 17:08
A colleague of mine just hit on this. @ckipp01 did you ever figure it out?

**Comment by ckipp01** [comment] 2020-03-19 17:16
For whatever reason, when we restarted bloop it ended up fixing the issue.

**Comment by gabro** [comment] 2020-03-23 16:18
I can confirm `killall java` fixed it for us...

**Comment by akilegaspi** [comment] 2020-03-23 19:00
Seems to be ok for me also now after restarting bloop, I wonder what might have caused it thought.

**Comment by ckipp01** [comment] 2020-03-28 00:00
I believe we can close this as there has been multiple reports of restarting bloop fixing the problem. I also haven't came across this in a while either. If we come across it again, we can reopen.

**Closed by ckipp01** 2020-03-28 00:00 UTC
Labels: needs more information
