### ISSUE TITLE
Error highlighting is intermittent in Emacs

### ISSUE THREAD

**Issue by marcsaegesser** [scalameta/metals#1027] opened 2019-10-28 23:55 UTC
**Describe the bug**
Compiler errors not always indicated in Emacs. Sometimes the red-squigglies appear along with error messages in the margin. Other times compiler errors are just not highlighted at all. Potentially related, there are times where errors are highlighted and when the error is fixed the red-squigglies do not go away.

This behavior is intermittent. Some times it works and then it stops.

I have created a simple project that I used to demonstrate the issue it can be found [here](https://github.com/marcsaegesser/ScalaMetalsTest). In the root directory is the minimal Emacs init.el file that I used. It is taken directly from the Metals documentation for Emacs with the small addition of disabling SBT supershell because that kills sbt-mode.

This directory also contains the metals.log file in case that is useful. The screen shot file is also there. The screen shows that the compiler errors appear in the sbt-mode window but the source code does not indicate any errors.

**To Reproduce**
1. I removed the existing .bloop and .metals directories so that I was starting from scratch.
2. I opened the Main.scala file in Emacs and selected "I" when prompted to import the project.
3. I split the window and started sbt-mode
4. In the sbt-mode window I started a continuous compile with ~compile
5. I entered two lines of code, each with a type error. This time the errors were highlighted.
6. I deleted those two lines and entered them again. This time the errors where not highlighted.
7. The sbt-mode windows shows the compiler errors that are not highlighted in the source code.

**Expected behavior**
Compiler errors should always be highlighted.

**Screenshots**
![ScreenShot](https://user-images.githubusercontent.com/1134304/67726531-24e61a00-f9b4-11e9-97bc-556446adedfe.png)

**Installation:**
- Linux
- Editor: Emacs
- Metals version: v0.7.6+170-9eddd91f-SNAPSHOT

**Additional context**

**Search terms**
red squiggly highlighting

**Comment by olafurpg** [comment] 2019-10-29 10:45
Thank you for reporting! I'm unable to reproduce in VS Code.

This might be a duplicate of https://github.com/scalameta/metals/issues/956.

> I deleted those two lines and entered them again. This time the errors where not highlighted.

Did you save the file between the changes? Metals triggers compilation on file save.

I see there's a `.#Main.scala` file in the screenshot, what happens if you configure emacs to place those generated files in another directory?

**Comment by marcsaegesser** [comment] 2019-10-29 13:04
Yes, I saved the file but it actually didn't matter. Again, the behavior is intermittent so it's difficult to provide concrete reproduction steps.

In this particular test I started with the plain HelloWord Main.scala file. I typed in the two lines with errors and the errors were highlighted as I was typing and the highlights remained after I saved the file. I then deleted those two lines and typed them again. This time there was no error highlighting at all as I was typing or after I saved the file. If I recall, after that I went around to various other parts of the file created several other syntax errors which were not highlighted. For the screen shot I left the cursor on the println function to show that the ugly pop-up still happened to demonstrate that Metals was still active, just not reporting compiler errors.

I will experiment with removing the editor's temp files. Those files are transient and short-lived. SBT's continous compilation sometimes catches them (which I think is a bug or at least non-desirable behavior). If this is what's confusing Metals then would it also fail if I copied Main.scala to Main2.scala so that there were two Scala source files for the same object? Obviously, that should be a compile error but if a transient .# temp file gets picked up and confuses Metals wouldn't any other duplicated file do the same? I'll try some more experiments.

**Comment by marcsaegesser** [comment] 2019-10-29 14:09
Results:
- Configuring Emacs to store auto-save files somewhere else seems to resolve the problem.
- Copying Main.scala to Main2.scala recreates the problem. No compiler errors are reported at all even though there are now two objects named Main plus lots of other compile errors.

When I get time I'll submit a PR to update the recommended Emacs configuration to help others avoid this.

I think the existing behavior is a bug, though. For example, if someone copies a source file during refactoring and creates a compile error Metals' error reporting shouldn't vanish.

**Comment by olafurpg** [comment] 2019-10-29 17:48
That's good to hear! I agree that the error should appear in both files when the same class is defined twice, however the Scala compiler only reports an error for the second definition
```scala
cat foo.scala bar.scala && scalac foo.scala bar.scala
object Main {
}
object Main {
}
bar.scala:1: error: Main is already defined as object Main
object Main {
       ^
one error found
```

I opened a minimized issue to the Scala compiler https://github.com/scala/bug/issues/11784 There isn't much we can do on the Metals side to fix this, we only report the errors that come from the compiler.

> When I get time I'll submit a PR to update the recommended Emacs configuration to help others avoid this.

Please do!

**Closed by olafurpg** 2019-10-29 17:48 UTC

**Comment by olafurpg** [comment] 2019-10-29 20:57
I'm unable to reproduce, when I create a separate file `Main2.scala` I see an error reported in one file while the other file has no errors.

![2019-10-29 20 52 28](https://user-images.githubusercontent.com/1408093/67808230-300d7880-fa8e-11e9-8b28-2e3de7659a7b.gif)

Please report an issue in https://github.com/scalacenter/bloop/ if you can provide an example project where the code compiles in Metals but it does not compile with sbt. Metals only forwards the errors that come from the build server (which is Bloop by default for sbt/gradle/maven projects)
