### ISSUE TITLE
Compile errors only updated at server start

### ISSUE THREAD

**Issue by spaceotter** [scalameta/metals#956] opened 2019-10-03 08:18 UTC
**Describe the bug**
Reported compile errors do not update in emacs after metals is started.

**To Reproduce**
Source code:
https://github.com/freechipsproject/chisel-template
With scala version bumped to '2.12.8' otherwise there are even more problems
Run its test: `$ sbt 'testOnly gcd.GCDTester -- -z Basic'`
The test works ok.
Start bloop: `$ bloop server`
Open GCD.scala in emacs with lsp-mode, import build
Type random characters to create a build error.
Nothing is reported.
Emacs I/O log says it got this from metals when the file was updated:
```
[Trace - 12:47:39 AM] Received notification 'window/logMessage'.
Params: {
  "message": "Failed to compile 'chisel-template'",
  "type": 4
}


[Trace - 12:47:39 AM] Received notification 'textDocument/publishDiagnostics'.
Params: {
  "diagnostics": [],
  "uri": "file:///home/eric/src/chisel-template/src/main/scala/gcd/.%23GCD.scala"
}
```
Further updates to the file do not change the error list at all, which will highlight incorrect regions of the file as a result of the text moving.
If the metals server is restarted from emacs, the error(s) will be reported by metals and marked by flycheck correctly only once.

**Expected behavior**
The build error is reported with flycheck without restarting the server.

**Installation:**
- Operating system: Manjaro
- Editor: Emacs 26.3
- Metals version: v0.7.6
- Bloop: 1.3.3, no difference seen with 1.3.2

**Additional context**
metals and bloop are installed through the AUR.

**Search terms**
compilation error update

**Comment by tgodzik** [comment] 2019-10-04 14:36
Thanks for reporting! Looks like the compilation is not triggering, do you save the file each time? We only trigger compilation on file save.

Does compilation work with client Bloop itself  or maybe there is something in `metals.log`?

Also `/gcd/.%23GCD.scala` doesn't look like a proper file name. 

Will try to reproduce time permitting.

**Comment by spaceotter** [comment] 2019-10-04 21:03
The line `Failed to compile 'chisel-template'` appears every time I save the file. On startup, it reports that this compilation succeeded even there is an error in the file. I turned on the i/o trace with bloop and the failure message seems to originate from bloop. So I would guess there is a problem with bloop, or the way bloop is being configured. I just started using metals and bloop 2 days ago so I don't know how it works.

**Comment by tgodzik** [comment] 2019-10-05 12:22
@spaceotter I checked out the project and it seems to be working. Can you try maybe running `bloop compile chisel-template` ? This should show any issues you might have that are not diagnostics related, since this looks like an issue with Bloop itself.

**Comment by spaceotter** [comment] 2019-10-05 19:10
I downgraded bloop to 1.3.2.
`bloop compile chisel-template` works as expected. It also produces the message `Failed to compile 'chisel-template'` if there were compilation errors.
[bsp.trace.json.log](https://github.com/scalameta/metals/files/3693618/bsp.trace.json.log)
Here's a log. At the end, metals requests a compilation of chisel-template and gets 'failed to compile' right away even though the errors were deleted, and `bloop compile` gives the correct result.

**Comment by spaceotter** [comment] 2019-10-11 18:44
Some further debugging implicates bloop. It seems as though the build is internally marked as cancelled for some reason.

**Comment by spaceotter** [comment] 2019-10-27 21:22
It seems that the issue with the build being cancelled is supposed to be fixed in bloop 1.3.4, and installing metals 0.7.6 and bloop 1.3.4 and repeating the above on two other computers yields a working setup. Additionally, the metals installed by vs code using the bloop server 1.3.4 from AUR on the original computer works.

I've rebuilt and reinstalled metals from the AUR and deleted/redownloaded chisel-template multiple times on the original machine, and it remains broken. I can't figure out what the significant difference is between the computers that work normally and the one that remains broken (even after deleting the .ivy2 cache, .sbt cache, bloop cache, metals cache, and starting over it *still* doesn't work)

**Comment by tgodzik** [comment] 2019-10-28 09:55
@spaceotter without any kind of reproduction or a direct access to the computer in question I am afraid we can't do anything. I will ask some people to try and set up chisel-template and see if there is an issue.

You can also try the newest snapshots, where we changed the way we connect to Bloop itself. Maybe this could help?

**Comment by olafurpg** [comment] 2019-10-28 11:11
@spaceotter are you able to reproduce with VS Code? If not, then you might want to report an issue to lsp-mode instead.

**Comment by marcsaegesser** [comment] 2019-11-05 01:29
I'm using 0.7.6+189-60592c9a-SNAPSHOT dated 04 Nov 2019 15:52. According to the bsp.trace.json file this is using Bloop  "version": "1.3.5" and  "bspVersion": "2.0.0-M4+10-61e61e87". My platform is Linux, OpenJDK8 and Scala 2.13.1, Emacs 26.3.

I'm seeing this same behavior. Things seem to work OK for a few minutes and then I stop getting updated compile errors. When this happens I find messages like the following in the bsp.trace.json file. Restarting Metals seems to resolve the problem for a few more minutes and then it fails again in the same way. If the problem was supposedly fixed in Bloop 1.3.4 then either there's a different problem or that issue still isn't fixed.

I haven't found the exact scenario(s) that cause the failure but I haven't been able to work on this project for more than 10 minutes at a time without restarting Metals. Is there any way to see _why_ Bloop failed to compile this project?

> [Trace - 06:17:00 PM] Received notification 'build/logMessage'
> Params: {
>   "type": 1,
>   "message": "Failed to compile \u0027advent2016\u0027"
> }

**Comment by spaceotter** [comment] 2019-11-05 01:38
With bloop 1.3.4, there was a message in bsp.trace.json with the status code "3" which as far as I could tell indicates that the build was "cancelled" - I couldn't tell why. When it works normally, it also says the build failed, but the build errors appear in bsp.trace.json and emacs.

**Comment by marcsaegesser** [comment] 2019-11-05 01:56
All I see are status codes of 2.

The only thing I've noticed so far that might be a pattern is that this seems to happen when I've just created an error. For example, I just typed in something like ```List[Items]``` when it should have been ```List[Item]```. I got the red squiggly for the error but when I backed up and removed the 's' the error highlight remained. I checked bsp.trace.json and saw the "Failed to compile" error again. Maybe the compile errors are a red herring? I have no clue.

I was using lsp-mode version 20191030. I just updated to 20191104 so we'll see if that has any impact. Also, if the problem isn't with Bloop then I should probably turn on the lsp.trace.json file to see if anything shows up there.

**Comment by marcsaegesser** [comment] 2019-11-11 01:46
I, sort of, know what's going on. When a buffer is modified, Emacs creates an [interlock](https://www.gnu.org/software/emacs/manual/html_node/emacs/Interlocking.html#Interlocking) file to prevent different users (or different instances of Emacs) from modifying the same file and potentially overwriting changes. These interlock files have the form ".#filename" and are a symlink to a non-existent file whose name indicates the user and process that has unsaved modifications to the file.

These interlock files are ignored by SBT. The existence of these interlock files has no effect on compile or ~compile in SBT. However, these files screw up Metals (probably via Bloop but I don't know how that works).

As a work-around, adding (setq create-lockfiles nil) to your init.el will disable the creation of the interlock files. I don't recommend this as a good practice. If you know that it is unlikely for multiple users to be editing the same file at the same time then it's probably not too dangerous.

**Comment by marcsaegesser** [comment] 2019-11-11 15:15
FYI, I opened issue [#1088](https://github.com/scalacenter/bloop/issues/1088) in Bloop for this.

**Comment by tgodzik** [comment] 2019-11-11 16:11
@marcsaegesser Thanks for looking into this! I will close this for now, since this seems to be an issue only with Bloop.

**Closed by tgodzik** 2019-11-11 16:11 UTC
Labels: needs more information

**Comment by ashkan-leo** [comment] 2020-03-17 21:47
I'm also facing this issue and adding `(setq create-lockfiles nil)` to the `init.el` didn't help.
