### ISSUE TITLE
Compile errors during import build affects other compile-able classes

### ISSUE THREAD

**Issue by smiklos** [scalameta/metals#4238] opened 2022-08-09 15:19 UTC
### Describe the bug

I'm using vscode with the metals extension and have a multi project setup.

Inside one of the projects, (2nd layer in the <> architecture) I have two files in two packages, 
lets say x.y.z.File1 and x.y.z.x.File2. (Tested with flat hierarchy too, e.g when File1 and File2 is in the same package)

File1 has compilation errors unrelated to File2, File2 compiles just fine. 

When I import a build (fresh, no metals files) or after I clean the compile work space I get no code completion nor any type support in the editor for File2. I then go to File1 and fix the compile errors, now File2 starts working just fine. I go back to File1, make the same compilation errors and File1 is still getting completion and all is great. 

Is this expected behavior? It seems File1 can work happily without File2 compiling yet when I reimport the build or clean the workspace metals somehow breaks down and doesn't give File2 the love it needs. 

### Expected behavior

I expect that classes that compile do get code completion and let me modify them while classes that don't compile or classes that depend on others that don't will not work. I expect that I don't need to manually fix all compile errors before I can work on parts of a project after I just reimported the project / cleaned the compile work space 

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

V1.18.0 vscode extension

**Comment by tgodzik** [comment] 2022-08-09 15:24
Thanks for reporting! This is currently expected behaviour since the presentation compiler requires the classpath to have working completions for other files. This is not a trivial matter unfortunately.

There is a long standing issue that raises this https://github.com/scalameta/metals/issues/917

Closing it as a duplicate of that one.

**Closed by tgodzik** 2022-08-09 15:24 UTC

**Comment by smiklos** [comment] 2022-08-09 15:25
Thank you!
