### ISSUE TITLE
Stability issues / Unexpected warnings/errors in metals.log 

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#2925] opened 2021-07-02 16:07 UTC
**Describe the bug**

I don't see errors being updated in the UI, this may be related or not.

<details>
<summary>Exhibit 1: newCompile unknown compiler options</summary>

This may be a red herring, `utf8` might be added to the compiler flags because I have `scalacOptions ++= Seq("-encoding", "utf8")` somewhere in the build - not sure how these are added for the presentation compiler.

```
Jul 02, 2021 2:59:48 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
Jul 02, 2021 2:59:50 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
Jul 02, 2021 2:59:51 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 85
Jul 02, 2021 3:00:40 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
Jul 02, 2021 3:01:10 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
Jul 02, 2021 3:01:11 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
Jul 02, 2021 3:01:12 AM scala.meta.internal.pc.ScalaPresentationCompiler newCompiler
WARNING: Unknown compiler options: utf8
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@46b24b79 rejected from java.util.concurrent.ThreadPoolExecutor@75b8769c[Shutting down, pool size = 4, active threads = 4, queued tasks = 0, completed tasks = 166]
```

</details>

<details>
<summary>Exhibit 2: rejected execution</summary>

```
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@46b24b79 rejected from java.util.concurrent.ThreadPoolExecutor@75b8769c[Shutting down, pool size = 4, active threads = 4
, queued tasks = 0, completed tasks = 166]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
        at scala.concurrent.impl.Promise.transform(Promise.scala:33)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
        at scala.concurrent.Future.map(Future.scala:292)
        at scala.concurrent.Future.map$(Future.scala:292)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
        at scala.concurrent.Future$.apply(Future.scala:659)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1277)
        at scala.meta.internal.metals.MetalsLanguageServer.didChangeWatchedFiles(MetalsLanguageServer.scala:1250)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1$adapted(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.FileWatcher$$anon$1.onUpdate(FileWatcher.scala:68)
        at com.swoval.files.CacheObservers.onUpdate(CacheObservers.java:59)
        at com.swoval.files.FileCacheDirectoryTree$6.run(FileCacheDirectoryTree.java:514)
        at com.swoval.files.FileCacheDirectoryTree$4.run(FileCacheDirectoryTree.java:258)
        at com.swoval.files.Executor$PriorityRunnable.run(Executor.java:161)
        at com.swoval.files.Executor$ExecutorImpl$1.run(Executor.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@63918ccd rejected from java.util.concurrent.ThreadPoolExecutor@75b8769c[Shutting down, pool size = 4, active threads = 4
, queued tasks = 0, completed tasks = 166]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
        at scala.concurrent.impl.Promise.transformWith(Promise.scala:40)
        at scala.concurrent.impl.Promise.transformWith$(Promise.scala:38)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transformWith(Promise.scala:379)
        at scala.concurrent.Future.flatMap(Future.scala:306)
        at scala.concurrent.Future.flatMap$(Future.scala:306)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.flatMap(Promise.scala:379)
        at scala.meta.internal.metals.BuildServerConnection.register(BuildServerConnection.scala:220)
        at scala.meta.internal.metals.BuildServerConnection.compile(BuildServerConnection.scala:109)
        at scala.meta.internal.metals.Compilations.compile(Compilations.scala:212)
        at scala.meta.internal.metals.Compilations.compile(Compilations.scala:194)
        at scala.meta.internal.metals.Compilations.$anonfun$compileBatch$1(Compilations.scala:31)
        at scala.meta.internal.metals.BatchedFunction.runRelease(BatchedFunction.scala:93)
        at scala.meta.internal.metals.BatchedFunction.runAcquire(BatchedFunction.scala:76)
        at scala.meta.internal.metals.BatchedFunction.apply(BatchedFunction.scala:40)
        at scala.meta.internal.metals.Compilations.compileFiles(Compilations.scala:93)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1278)
        at scala.meta.internal.metals.MetalsLanguageServer.didChangeWatchedFiles(MetalsLanguageServer.scala:1250)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1$adapted(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.FileWatcher$$anon$1.onUpdate(FileWatcher.scala:68)
        at com.swoval.files.CacheObservers.onUpdate(CacheObservers.java:59)
        at com.swoval.files.FileCacheDirectoryTree$6.run(FileCacheDirectoryTree.java:514)
        at com.swoval.files.FileCacheDirectoryTree$4.run(FileCacheDirectoryTree.java:258)
        at com.swoval.files.Executor$PriorityRunnable.run(Executor.java:161)
        at com.swoval.files.Executor$ExecutorImpl$1.run(Executor.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@3431a75e rejected from java.util.concurrent.ThreadPoolExecutor@75b8769c[Shutting down, pool size = 4, active threads = 4
, queued tasks = 0, completed tasks = 166]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
        at scala.meta.internal.metals.BatchedFunction.runRelease(BatchedFunction.scala:95)
        at scala.meta.internal.metals.BatchedFunction.runAcquire(BatchedFunction.scala:76)
        at scala.meta.internal.metals.BatchedFunction.apply(BatchedFunction.scala:40)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1279)
        at scala.meta.internal.metals.MetalsLanguageServer.didChangeWatchedFiles(MetalsLanguageServer.scala:1250)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1$adapted(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.FileWatcher$$anon$1.onUpdate(FileWatcher.scala:68)
        at com.swoval.files.CacheObservers.onUpdate(CacheObservers.java:59)
        at com.swoval.files.FileCacheDirectoryTree$6.run(FileCacheDirectoryTree.java:514)
        at com.swoval.files.FileCacheDirectoryTree$4.run(FileCacheDirectoryTree.java:258)
        at com.swoval.files.Executor$PriorityRunnable.run(Executor.java:161)
        at com.swoval.files.Executor$ExecutorImpl$1.run(Executor.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@12d6cc92 rejected from java.util.concurrent.ThreadPoolExecutor@75b8769c[Shutting down, pool size = 4, active threads = 4
, queued tasks = 0, completed tasks = 166]
        at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
        at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
        at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
        at scala.concurrent.impl.ExecutionContextImpl$$anon$4.execute(ExecutionContextImpl.scala:138)
        at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete(Promise.scala:372)
        at scala.concurrent.impl.Promise$KeptPromise$Kept.onComplete$(Promise.scala:371)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.onComplete(Promise.scala:379)
        at scala.concurrent.impl.Promise.transform(Promise.scala:33)
        at scala.concurrent.impl.Promise.transform$(Promise.scala:31)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.transform(Promise.scala:379)
        at scala.concurrent.Future.map(Future.scala:292)
        at scala.concurrent.Future.map$(Future.scala:292)
        at scala.concurrent.impl.Promise$KeptPromise$Successful.map(Promise.scala:379)
        at scala.concurrent.Future$.apply(Future.scala:659)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$onChange$3(MetalsLanguageServer.scala:1280)
        at scala.collection.immutable.List.map(List.scala:293)
        at scala.meta.internal.metals.MetalsLanguageServer.onChange(MetalsLanguageServer.scala:1280)
        at scala.meta.internal.metals.MetalsLanguageServer.didChangeWatchedFiles(MetalsLanguageServer.scala:1250)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$fileWatcher$1$adapted(MetalsLanguageServer.scala:183)
        at scala.meta.internal.metals.FileWatcher$$anon$1.onUpdate(FileWatcher.scala:68)
        at com.swoval.files.CacheObservers.onUpdate(CacheObservers.java:59)
        at com.swoval.files.FileCacheDirectoryTree$6.run(FileCacheDirectoryTree.java:514)
        at com.swoval.files.FileCacheDirectoryTree$4.run(FileCacheDirectoryTree.java:258)
        at com.swoval.files.Executor$PriorityRunnable.run(Executor.java:161)
        at com.swoval.files.Executor$ExecutorImpl$1.run(Executor.java:65)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

...and then the same thing again and again

</details>

<details>
<summary>Exhibit 3: match error</summary>

```
SEVERE: implicit class <error> extends  (of class scala.reflect.internal.Trees$ClassDef)
scala.MatchError: implicit class <error> extends  (of class scala.reflect.internal.Trees$ClassDef)
        at scala.tools.nsc.typechecker.Unapplies.constrParamss(Unapplies.scala:64)
        at scala.tools.nsc.typechecker.Unapplies.factoryMeth(Unapplies.scala:141)
        at scala.tools.nsc.typechecker.Unapplies.factoryMeth$(Unapplies.scala:138)
        at scala.meta.internal.pc.MetalsGlobal$MetalsInteractiveAnalyzer.factoryMeth(MetalsGlobal.scala:59)
        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth.enterImplicitWrapper(MethodSynthesis.scala:229)
        at scala.tools.nsc.typechecker.MethodSynthesis$MethodSynth.enterImplicitWrapper$(MethodSynthesis.scala:228)
        at scala.tools.nsc.typechecker.Namers$Namer.enterImplicitWrapper(Namers.scala:58)
        at scala.tools.nsc.interactive.InteractiveAnalyzer$InteractiveNamer.enterExistingSym(Global.scala:94)
        at scala.tools.nsc.interactive.InteractiveAnalyzer$InteractiveNamer.enterExistingSym$(Global.scala:80)
        at scala.tools.nsc.interactive.InteractiveAnalyzer$$anon$2.enterExistingSym(Global.scala:51)
        at scala.tools.nsc.typechecker.Namers$Namer.standardEnterSym(Namers.scala:298)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym(AnalyzerPlugins.scala:479)
        at scala.tools.nsc.typechecker.AnalyzerPlugins.pluginsEnterSym$(AnalyzerPlugins.scala:478)
        at scala.meta.internal.pc.MetalsGlobal$MetalsInteractiveAnalyzer.pluginsEnterSym(MetalsGlobal.scala:59)
        at scala.tools.nsc.typechecker.Namers$Namer.enterSym(Namers.scala:272)
        at scala.tools.nsc.typechecker.Typers$Typer.enterSym(Typers.scala:1933)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$enterSyms$1(Typers.scala:1928)
        at scala.tools.nsc.typechecker.Typers$Typer.enterSyms(Typers.scala:1928)
        at scala.tools.nsc.typechecker.Typers$Typer.typedTemplate(Typers.scala:1990)
        at scala.tools.nsc.typechecker.Typers$Typer.typedClassDef(Typers.scala:1830)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5644)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStat$1(Typers.scala:5788)
        at scala.tools.nsc.typechecker.Typers$Typer.$anonfun$typedStats$10(Typers.scala:3335)
        at scala.tools.nsc.typechecker.Typers$Typer.typedStats(Typers.scala:3335)
        at scala.tools.nsc.typechecker.Typers$Typer.typedPackageDef$1(Typers.scala:5354)
        at scala.tools.nsc.typechecker.Typers$Typer.typed1(Typers.scala:5647)
        at scala.tools.nsc.typechecker.Typers$Typer.typed(Typers.scala:5724)
        at scala.tools.nsc.typechecker.Analyzer$typerFactory$TyperPhase.apply(Analyzer.scala:115)
        at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:454)
        at scala.tools.nsc.interactive.Global$TyperRun.$anonfun$applyPhase$1(Global.scala:1340)
        at scala.tools.nsc.interactive.Global$TyperRun.applyPhase(Global.scala:1340)
        at scala.tools.nsc.interactive.Global$TyperRun.typeCheck(Global.scala:1333)
        at scala.tools.nsc.interactive.Global.typeCheck(Global.scala:665)
        at scala.tools.nsc.interactive.Global.typedTreeAt(Global.scala:814)
        at scala.tools.nsc.interactive.Global.completionsAt(Global.scala:1225)
        at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala:402)
        at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:58)
```

</details>

<details>
<summary>Exhibit 4: Something's wrong</summary>

```
something's wrong: no file:///Users/jkoslowski/dev/subscription-service/play/src/main/scala/com/mlbam/subscription/core/api/marshallers/ApiSubscriptionFormats.scala in play.api.libs.json.OFormat[<error>]RangePosit
ion(file:///Users/jkoslowski/dev/subscription-service/play/src/main/scala/com/mlbam/subscription/core/api/marshallers/ApiSubscriptionFormats.scala, 12971, 12971, 12988)
something's wrong: no file:///Users/jkoslowski/dev/subscription-service/play/src/main/scala/com/mlbam/subscription/core/api/marshallers/ApiSubscriptionFormats.scala in play.api.libs.json.Format[<error>]RangePositi
on(file:///Users/jkoslowski/dev/subscription-service/play/src/main/scala/com/mlbam/subscription/core/api/marshallers/ApiSubscriptionFormats.scala, 12971, 12971, 12987)
```

Newlines are just `less` output.

</details>

**To Reproduce**

- Use the IDE for an hour with lots of non-compiling states 😅 sadly I don't have anything more deterministic/specific

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.4

**Comment by kubukoz** [comment] 2021-07-02 16:09
Update: after "connect to build server" I have 4 Metals server instances for a single project.

**Comment by tgodzik** [comment] 2021-07-05 10:44
Thanks for reporting!

> Update: after "connect to build server" I have 4 Metals server instances for a single project.

That should be fixed in the recent snapshot and might cause some of the issues.

> WARNING: Unknown compiler options: utf8

is usually caused by using a wrong flag, I think there was some issue with tpolecat recommended flags?

> java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable

Might be connected to the multidiude of clients running at the same time

> SEVERE: implicit class <error> extends  (of class scala.reflect.internal.Trees$ClassDef)

This is a compiler issue, best to report it there, but might have been caused by a specific code state.

> something's wrong: no file,,,

That's a fun one, I think we get source files cached in some places, but I have no idea where.

**Comment by kubukoz** [comment] 2021-07-05 15:52
> > WARNING: Unknown compiler options: utf8
> 
> is usually caused by using a wrong flag, I think there was some issue with tpolecat recommended flags?

I think it's doing what https://docs.scala-lang.org/overviews/compiler-options/index.html does: passing `-encoding`, `utf8` as separate parameters to `scalacOptions`. Perhaps there's some reordering/sorting along the way so they get added to the PC in the wrong order?

> 
> > java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable
> 
> Might be connected to the multidiude of clients running at the same time

I have one client only :/

**Comment by tgodzik** [comment] 2021-07-05 16:27
> I think it's doing what https://docs.scala-lang.org/overviews/compiler-options/index.html does: passing `-encoding`, `utf8` as separate parameters to `scalacOptions`. Perhaps there's some reordering/sorting along the way so they get added to the PC in the wrong order?

Might be, but we don't really reorder anything, if you have a short repro we could check it out. I haven't seen an issue with it normally.

> > 
> > Might be connected to the multidiude of clients running at the same time
> 
> I have one client only :/

yeah, but because of the bug multiple clients might still be connected to Bloop :/

Should be fixed in the newest master.

**Comment by kubukoz** [comment] 2021-07-05 16:38
cool, I'll get onto the bleeding edge :D

**Comment by ckipp01** [comment] 2021-12-29 15:06
So I played around here with a few things trying to reproduce and I wasn't able to. The last status of this seems to be that some things were changed to fix some of the issues and others were mentioned should be reported upstream. I'm going to close for now, but please do report back or re-open if you either get more info on one of these by coming across it again.

**Closed by ckipp01** 2021-12-29 15:06 UTC
