### ISSUE TITLE
NoSuchFileException: scalac-plugin.xml

### ISSUE THREAD

**Issue by scalavision** [scalameta/metals#1720] opened 2020-05-11 12:12 UTC
**Describe the bug**

during build import for metals 0.9.0, I get this error:

```
2020.05.11 13:59:58 INFO  Connected to Build server v1.4.0-RC1-229-b7c15aa9
2020.05.11 13:59:59 INFO  compiling analytics (21 scala sources)
2020.05.11 13:59:59 INFO  time: indexed workspace in 1.67s
2020.05.11 14:00:00 INFO  Deduplicating compilation of analytics from bsp client 'Metals 0.9.0' (since 1.748s)
2020.05.11 14:00:00 INFO  compiling analytics (21 scala sources)
2020.05.11 14:00:02 ERROR 
<path to coursier cache>/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar
java.nio.file.NoSuchFileException: scalac-plugin.xml
	at com.sun.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:544)
	at com.sun.nio.zipfs.ZipPath.newInputStream(ZipPath.java:645)
	at com.sun.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:278)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at scala.meta.internal.metals.CompilerPlugins.$anonfun$isSupportedPlugin$1(CompilerPlugins.scala:65)
```
I got this firstly on scala 2.13.1, thought it could be some corrupted files, so upgraded to 2.13.2 to trigger new download, but that didn't help.

Is this `xml` file needed by metals or can it be ignored? It seems to be working just fine without it.

**To Reproduce**

Import a freshly cloned project.

**Expected behavior**

**Screenshots**

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**

I also got an error in semanticdb file missing before this, so I cleansed out `.metals` and `.bloop` folder. 

I am using mill version 0.6.1 as build system.

**Search terms**

scalac-plugin.xml

**Comment by tgodzik** [comment] 2020-05-11 14:34
Thanks for reporting! We actually try to read that xml for anything that is defined as a plugin with `-Xplugin:`. That exception should not be an issue when using Metals, but is a sign that something is misconfigured.

It looks like mill is defining scala-lang as a compiler plugin, which looks like a mistake. I do remember something similar happening in the past, however I am unable to reproduce it in my mill workspace. 

Is the sting:
`-Xplugin:<path to coursier cache>/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar`
anywhere in the codebase?

Or maybe could you try posting a minimized `build.sc` where this exception shows up?

**Comment by scalavision** [comment] 2020-05-11 17:58
Sure :-)

thanks for looking into this, hm.. maybe some of my compiler plugins could be the cause?

I also get this for:

`jline.jar`, `scala-reflect.jar`, `jna.jar`, `scala-compiler.jar`, `silencer-lib`. 

This doesn't seem to have much effect metals in vscode luckily.

My entire build is configured as this:

```scala
import mill._, scalalib._
import $ivy.`com.lihaoyi::mill-contrib-bloop:0.6.1`

trait common extends ScalaModule {

  val stdOptions = Seq(
    "-deprecation",
    "-encoding",
    "UTF-8",
    "-explaintypes",
    "-Yrangepos",
    "-feature",
    "-Xfuture",
    "-language:higherKinds",
    "-language:existentials",
    "-unchecked",
    "-Xlint:_,-type-parameter-shadow",
    "-Xsource:2.13",
    "-Xfatal-warnings",
    "-Ymacro-annotations",
    "-opt-warnings",                                                                                         
    "-Ywarn-extra-implicit",                                                                                 
    "-Ywarn-unused:_,imports",                                                                               
    "-Ywarn-unused:imports",                                                                                 
    "-opt:l:inline",                                                                                         
    "-opt-inline-from:<source>",
    "-feature",
    "-Ywarn-value-discard",
    "-Ywarn-dead-code",
    "-Ywarn-numeric-widen",
    "-Ypatmat-exhaust-depth", "off"
  )
  
  def scalaVersion = "2.13.2"
  
  def compileIvyDeps = Agg(
    ivy"com.github.ghik:silencer-plugin_2.13.2:1.7.0",
    ivy"org.typelevel:kind-projector_2.13.2:0.11.0",
    //ivy"org.typelevel::kind-projector:0.11.0",
    ivy"com.github.tomasmikula::pascal:0.3.5"
  )

  def scalacPluginIvyDeps = Agg(
    ivy"com.github.ghik:silencer-plugin_2.13.2:1.7.0",
    ivy"org.typelevel:kind-projector_2.13.2:0.11.0",
    ivy"com.github.tomasmikula::pascal:0.3.5"
  )

  def ivyDeps = Agg(
    ivy"org.scala-lang.modules::scala-collection-compat:2.1.4",
    ivy"com.lihaoyi::sourcecode:0.2.1",
    ivy"com.lihaoyi::pprint:0.5.8",
    ivy"com.lihaoyi::os-lib:0.6.3",
    ivy"org.scalanlp::breeze:1.0",
    ivy"org.knowm.xchart:xchart:3.6.3",
    ivy"de.erichseifert.vectorgraphics2d:VectorGraphics2D:0.13",
    ivy"org.scalameta::scalafmt-dynamic:2.4.2",
    ivy"org.scalameta::scalafmt-core:2.4.2",
    ivy"org.scala-lang:scala-reflect:${scalaVersion}",
    ivy"org.scala-lang:scala-compiler:${scalaVersion}",
  )

  def compile = T {
    // clearing the screen
//    print("\u001b[2J")
    super.compile()
  }

  def scalacOptions = stdOptions

  object test extends Tests {
    def ivyDeps = Agg(
      ivy"dev.zio::zio-test:1.0.0-RC18-2",
      ivy"dev.zio::zio-test-sbt:1.0.0-RC18-2"
    )
    def testFrameworks = 
      Seq("zio.test.sbt.ZTestFramework")
  }
}

object analytics extends common {}
```

**Comment by tgodzik** [comment] 2020-05-12 12:44
Looks like Mill is adding the scala compiler as a compiler plugin:
```
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/typelevel/kind-projector_2.13.2/0.11.0/kind-projector_2.13.2-0.11.0.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.2/scala-library-2.13.2.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/jline/jline/3.14.1/jline-3.14.1.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.2/scala-reflect-2.13.2.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/net/java/dev/jna/jna/5.3.1/jna-5.3.1.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.2/scala-compiler-2.13.2.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-lib_2.13.2/1.7.0/silencer-lib_2.13.2-1.7.0.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/ghik/silencer-plugin_2.13.2/1.7.0/silencer-plugin_2.13.2-1.7.0.jar",
                "-Xplugin:/home/tgodzik/.cache/coursier/v1/https/repo1.maven.org/maven2/com/github/tomasmikula/pascal_2.13/0.3.5/pascal_2.13-0.3.5.jar"
```
it should be fixed in Mill. Could you open an issue and link to this one?

**Comment by scalavision** [comment] 2020-05-12 17:04
I've opened an issue here in mill:

https://github.com/lihaoyi/mill/issues/880

**Comment by lefou** [comment] 2020-05-12 19:49
Can you check if these are transitive dependencies of your scalac plugins? And if, shouldn't these be marked as "provided"?

**Comment by scalavision** [comment] 2020-05-14 14:26
hm.. could you elaborate a bit more? I wasn't able to list any transitive dependencies for my scalac plugins using ``mill analytics.ivyDepsTree``.  Doing ``mill analytics._`` tries to download a new version of ammonite, but the maven resolution breaks. Possibly because of 2.13.2? 

I don't have much experience with `mill`, hoped it would be easier to use than sbt, and for most cases I really think it is.

By ``ivy".."exclude()`` do you mean something like this:

```
 ivy"com.github.ghik:silencer-plugin_2.13.2:${silencerVersion}".exclude(scala-library)
```

etc.? I hope that wouldn't be necessary though ..

I have also dfined them both as `compileIvyDeps` and as `scalacPluginIvyDeps`, I think that is according to the manual.

**Comment by lefou** [comment] 2020-05-14 19:32
If you write an ivy dependency and coursier resolves it, it will in most cases also resolve all of it's transitive dependencies. If you want only exactly the JAR defined by the ivy coordinates without any possibly transitive dependency, you can for example write `ivy"com.github.ghik:silencer-plugin_2.13.2:${silencerVersion}".exclude("*" -> "*"). If that works for you, than we have found the issue. It's in the published metadata of that plugin. I already have your workaround and can create an issue upstream. If not, we need to investigate further.

Also I think, you only need to also list the plugins in your normal or compile ivy deps, if you are going to use any API they contain.

**Comment by lefou** [comment] 2020-05-14 19:36
The `ivyDepsTree` does not list scalac plugin dependency currently. It lists `ivyDeps` and supports the two options `--withCompile` and `--withRuntime` to include compile-time and runtime deps.

**Comment by tgodzik** [comment] 2020-05-18 09:43
Thanks for the additional comments @lefou ! I think we can close it, as it is not a problem with Metals,  and continue if neccessary in the mill repository.

**Closed by tgodzik** 2020-05-18 09:43 UTC
Labels: needs more information

**Comment by scalavision** [comment] 2020-05-18 10:55
Thank your very much for your helpful explanations @lefou :-)

Adding this to my build, makes the error message go away:

```scala
 def scalacPluginIvyDeps = Agg(
    ivy"com.github.ghik:silencer-plugin_2.13.2:${silencerVersion}".exclude("*" -> "*"),
    ivy"org.typelevel:kind-projector_2.13.2:0.11.0".exclude("*" -> "*"),
    ivy"com.github.tomasmikula:pascal_2.13.2:${pascalVersion}".exclude("*" -> "*")
  )
```

and it doesn't seem to affect the build in any negative way ..
