### ISSUE TITLE
"no build tool detected in workspace", but some features work

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#4278] opened 2022-08-18 17:34 UTC
### Describe the bug

Pretty much all the time, I'm getting errors like:

> no build tool detected in workspace '/Users/kubukoz/dev/scala-scripts'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. 

in a project where **scala-cli** is the build server. Some features work, like go to definition (including external libraries).

I also get messages like `ERROR Unexpected error when compiling project_183d125c5c: 'null'`.

This _seems_ to be dependent on the Scalafmt config in the project. This looks fine:

```
version = "3.5.9"
runner.dialect = scala213Source3
```

but this doesn't:

```
version = "2.7.4"
```

After making these changes, I closed Metals and ran the following:

```bash
rm -rf .scala-build .bsp
scala-cli compile .
```

### Expected behavior

No confusing errors in the output panel (which gets focused anytime I try to navigate) :)

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.8+25-04b682be-SNAPSHOT

**Comment by kubukoz** [comment] 2022-08-18 17:37
Update, looks like even with the updated scalafmt config I get the output panel to show up with errors. Apparently this happens whenever I change something in the scala-cli build config.

**Comment by dos65** [comment] 2022-08-19 12:02
@kubukoz  Thanks for reporting!

I can't reproduce the thing with: `ERROR Unexpected error when compiling project_183d125c5c: 'null'`
Which scala-cli version do you use?

In my case I have the following one:
`2022.08.19 14:52:42 ERROR scalafmt: /home/dos65/projects/metals/samples/issues/scala-cli-4278/.scalafmt.conf: Invalid config: Unknown input 'scala213Source3'. Expected one of: scala212, sbt1, paradise211, scala211, paradise212, default, dotty, scala213, sbt0137`

**Comment by kubukoz** [comment] 2022-08-19 12:38
I'm on 0.1.11.

**Comment by dos65** [comment] 2022-08-19 13:54
> I'm on 0.1.11.

I have the same.
It's needed more info or a reliable way to reproduce it.

The only idea I have, than we can improve error message in bloop logs for this situation to get smth useful instead of just 'null'

**Comment by kubukoz** [comment] 2022-08-19 17:53
that'd be good enough! I don't know how to reproduce this outside of that one particular project, and I can't publish the code... seeing some more detail of the error would definitely be helpful for me to minimize the issue.

**Comment by tgodzik** [comment] 2022-08-22 15:03
> ERROR Unexpected error when compiling project_183d125c5c: 'null'

Looks like an issue with ScalaCLI. This is actually a message forwarded from Bloop. Maybe running `scala-cli -v -v -v` when this happens would shed more information?

I think the dialect should be `Scala213Source3`

**Comment by dos65** [comment] 2022-08-22 15:47
I think I got this error - `Unexpected error when compiling project_183d125c5c: 'null'`. In my case, there is also a stacktrace from scala cli

@alexarchambault Have you seen anything like this?
```
2022.08.22 18:42:10 INFO  Scala CLI: java.nio.file.ClosedFileSystemException
2022.08.22 18:42:10 INFO  Scala CLI: 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1619)
2022.08.22 18:42:09 INFO  time: compiled project_183d125c5c in 0.54s
2022.08.22 18:42:10 INFO  Scala CLI: 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.getFileAttributes(ZipFileSystem.java:531)
2022.08.22 18:42:10 INFO  Scala CLI: 	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:767)
2022.08.22 18:42:10 INFO  Scala CLI: 	at jdk.zipfs/jdk.nio.zipfs.ZipPath.readAttributes(ZipPath.java:777)
2022.08.22 18:42:10 INFO  Scala CLI: 	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:276)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.nio.file.Files.readAttributes(Files.java:1851)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.nio.file.Files.size(Files.java:2468)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.HashUtil$.farmHash(HashUtil.scala:31)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.FarmHash$.ofPath(Stamp.scala:89)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.Stamper$.$anonfun$forHashInRootPaths$3(Stamp.scala:233)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.Stamper$.tryStamp(Stamp.scala:188)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.Stamper$.$anonfun$forHashInRootPaths$1(Stamp.scala:233)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.UncachedStamps.library(Stamp.scala:465)
2022.08.22 18:42:09 ERROR Unexpected error when compiling project_183d125c5c: 'null'
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.InitialStamps.$anonfun$library$1(Stamp.scala:419)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.InitialStamps.library(Stamp.scala:419)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.$anonfun$addProductsAndDeps$16(BloopAnalysisCallback.scala:400)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableLike.map(TraversableLike.scala:286)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableLike.map$(TraversableLike.scala:279)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.mutable.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:50)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.SetLike.map(SetLike.scala:105)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.SetLike.map$(SetLike.scala:105)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.mutable.AbstractSet.map(Set.scala:50)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.$anonfun$addProductsAndDeps$1(BloopAnalysisCallback.scala:398)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:196)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableOnce$folder$1.apply(TraversableOnce.scala:194)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.mutable.HashSet.foreach(HashSet.scala:79)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableOnce.foldLeft(TraversableOnce.scala:199)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.TraversableOnce.foldLeft$(TraversableOnce.scala:192)
2022.08.22 18:42:10 INFO  Scala CLI: 	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:108)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.addProductsAndDeps(BloopAnalysisCallback.scala:356)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.bloop.internal.BloopAnalysisCallback.get(BloopAnalysisCallback.scala:298)
2022.08.22 18:42:10 INFO  Scala CLI: 	at sbt.internal.inc.bloop.internal.BloopIncremental$.$anonfun$compileIncremental$5(BloopIncremental.scala:119)
2022.08.22 18:42:10 INFO  Scala CLI: 	at monix.eval.Task.$anonfun$map$1(Task.scala:407)
2022.08.22 18:42:10 INFO  Scala CLI: 	at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:176)
2022.08.22 18:42:10 INFO  Scala CLI: 	at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
2022.08.22 18:42:10 INFO  Scala CLI: 	at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
2022.08.22 18:42:10 INFO  Scala CLI: 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by alexarchambault** [comment] 2022-08-22 15:50
> Have you seen anything like this?

Yes, that should be fixed by https://github.com/scala-cli/bloop-core/pull/112, that the upcoming Scala CLI release will use by default.

In the mean time, the following commands should bump the (Scala CLI's own) Bloop server version:
```text
$ scala-cli bloop exit
$ scala-cli bloop --bloop-version 1.5.3-sc-1 about
```

**Comment by kubukoz** [comment] 2022-08-23 23:21
After updating to scala-cli 0.1.12 and reverting to this version of the project, I'm (so far) unable to reproduce the issue.

I definitely see this in the output:

```
2022.08.24 01:15:17 INFO  Required scalafmt dialect rewrite to 'scala213source3'. Directories:
...
```

which makes sense with the default dialect, as I have `-Xsource:3.0` enabled and I'm using Scala 2.13.

Closing, will reopen if it happens again - thanks everyone!

**Comment by tgodzik** [comment] 2022-08-30 16:48
I can't seem to reproduce, but this looks like an issue with ScalaCLI 

Does this happen every time for you with that file? Or just in that specific workspace?

**Comment by kubukoz** [comment] 2022-08-31 00:27
It's specific to the workspace but it's not the first one I've seen it in.

**Comment by tgodzik** [comment] 2022-09-01 11:25
If you compile that using CLI does it show the same error? Maybe you could compile with `-v -v -v` options to see what is happening?

**Comment by kubukoz** [comment] 2022-09-08 15:34
I don't see any issues when using the CLI.

**Comment by tgodzik** [comment] 2024-01-05 12:17
Can you still reproduce it? You should be able to turn on verbose compilation as well as Bloop should be able to print more of the stack trace now.

**Comment by tgodzik** [comment] 2024-01-05 18:26
Looks like a bug in Scala CLI, it should have a proper fallback in that case. I will check and raise it there. Thanks!

**Comment by tgodzik** [comment] 2024-01-05 18:35
Looks to  be working with newest Scala CLI, can you confirm that the newest one is used?

**Comment by kubukoz** [comment] 2024-01-05 20:09
This was on 1.1.0, which seems to be the latest 🤔

**Comment by kubukoz** [comment] 2024-01-05 20:11
well, looks like even 2.13.8 works fine now. I don't know what it was, but it seems to have resolved itself 😅

**Comment by tgodzik** [comment] 2024-01-07 17:17
Let's reopen if that happens again.

**Closed by tgodzik** 2024-01-07 17:17 UTC
Labels: needs more information
