### ISSUE TITLE
Worksheets stop updating from time to time

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#1432] opened 2020-02-13 21:35 UTC
**Describe the bug**
After a couple minutes / a few tens of evaluations, Worksheets stop updating.

I don't have any way of reliably reproducing it, but when I encounter it again, I'll put some logs here.

**To Reproduce**

- not sure yet

**Expected behavior**
Worksheets don't stop updating!

**Screenshots**
- not yet

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
- 

**Search terms**
worksheet, hang, reload

**Comment by ckipp01** [comment] 2020-04-03 20:54
@kubukoz just following up on this. Since you've originally reported, have you continually still come across this or no?

**Comment by kubukoz** [comment] 2020-04-03 21:11
> @kubukoz just following up on this. Since you've originally reported, have you continually still come across this or no?

I haven't used worksheets that much recently :(

**Comment by ckipp01** [comment] 2020-04-04 06:52
> I haven't used worksheets that much recently :(

No worries, was just wondering!

**Comment by tgodzik** [comment] 2020-05-07 15:55
Closing this for now, I haven't encountered it at any point and we've been heavily using worksheets, so I think we can reopen this once we get a reproducible scenario.

**Closed by tgodzik** 2020-05-07 15:55 UTC
Labels: bug, missing-reproduction
