### ISSUE TITLE
Test decorator and test run command in aggregate root project fail

### ISSUE THREAD

**Issue by markusa380** [scalameta/metals#2690] opened 2021-04-08 09:39 UTC
When
* the build.sbt contains two projects
* one project ("root") contains a testing framework and tests, and `.aggregate`s the other project ("common")
* SBT is used as language server

running the `test` decorator or the `metals.test-current-file` fails with an ugly error message in the Metals output:

```
...
[Error - 11:36:15 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:704)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:29)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:26)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:67)
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:59)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:875)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:110)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:107)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:873)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:72)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:288)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:288)
	at scala.concurrent.Promise.complete(Promise.scala:53)
	at scala.concurrent.Promise.complete$(Promise.scala:52)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:187)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: scala.meta.internal.metals.MetalsBspException: BSP connection failed in the attempt to get: DebugSessionAddress.  no matching test group
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:237)
	at scala.meta.internal.metals.BuildServerConnection$$anonfun$1.applyOrElse(BuildServerConnection.scala:229)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
	... 4 more

2021.04.08 11:36:14 ERROR no matching test group
2021.04.08 11:36:14 ERROR (common / Test / startTestSuitesDebugSession) no matching test group
2021.04.08 11:36:14 ERROR Error -33000: 
...
```

**To Reproduce**

1. Clone this repository: https://github.com/markusa380/metals-test-error
2. Select SBT as build server (didn't test with Bloop)
3. Run the `test` decorator in `HelloSpec.scala`

**Expected behavior**

Tests work.

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.10.1

**Additional context**

Only tested with SBT as build server.

**Search terms**

test, decorator, command, sbt

**Comment by tgodzik** [comment] 2021-04-08 09:55
Thanks for the report and reproduction! Is this something that might be needed to fixes in the debug plugin ? @adpi2

**Comment by tgodzik** [comment] 2021-04-08 11:44
Hmm.. I am getting an altogether different issue, looks like getting https://github.com/scalameta/metals/issues/2245 but it doesn't seem to be set in Metals. @ckipp01 could you confimr this one? I was trying to fix it, but I am not able figure it out.

However, this let to another fix https://github.com/scalameta/metals/pull/2693 - which might help figuring this situation in the future.

**Comment by adpi2** [comment] 2021-04-08 12:02
Thanks for the reproduction! This bug should be fixed in https://github.com/scalacenter/scala-debug-adapter/issues/40

**Comment by adpi2** [comment] 2021-04-09 09:29
@markusa380 I have published a fixed version of the `sbt-debug-adapter` plugin.  You can force it in your current project by adding it explicitly:

```scala
// project/plugins.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-debug-adapter" % "1.1.1")
```

**Closed** 2021-04-13 11:59 UTC
Labels: BSP, sbt, sbt server, upstream-fix-needed
