### ISSUE TITLE
Using directives not highlighted properly in ScalaCLI scripts

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#5149] opened 2023-04-14 12:27 UTC
### Describe the bug

1. Create a script
2. Add using directives for example `//> using scala "2.13.10`
3. Start within Metals

No highlight is shown. This is most likely related to the additional adjust positions that the script has.

### Expected behavior

using directives are properly highlighted

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

### Extra context or search terms

semantic highlight tokens scalacli

**Comment by tgodzik** [comment] 2023-04-14 12:27
@jkciesluk could you take a look?

**Comment by jkciesluk** [comment] 2023-04-14 13:43
It's worse than I thought 😅  
<img width="233" alt="image" src="https://user-images.githubusercontent.com/72950514/232055541-101c9b00-f98b-407c-976c-4d39840f30c1.png">

I will work on that. The problem is that semantic tokens contain synthetic nodes added by scala-cli.
Also, using directives are currently highlighted only if they are at the beginning of file, we should probably change it so they can be in every comment

**Comment by jkciesluk** [comment] 2023-04-18 08:04
Should be solved by https://github.com/scalameta/metals/pull/5153 and https://github.com/scalameta/metals/pull/5154

**Comment by jkciesluk** [comment] 2023-07-17 08:11
fixed by https://github.com/VirtusLab/scala-cli/pull/2171

**Closed by jkciesluk** 2023-07-17 08:11 UTC
Labels: bug, semantic-highlight
