### ISSUE TITLE
Cannot "watch" expression when debugging

### ISSUE THREAD

**Issue by vadeg** [scalameta/metals#1332] opened 2020-01-16 15:52 UTC
_WATCH_ section does not display values for variables available in the scope.

**To Reproduce** Steps to reproduce the behavior:

1. Create simple `Scala` program with some values defined
2. Put a breakpoint
3. Start simple `scala` program in _DEBUG_ mode
4. When breakpoint reached try to add some variables from the scope to _WATCH_

Variables added in the _WATCH_ section should have values.

**Screenshots**

![watch-not-working](https://user-images.githubusercontent.com/5587834/72539244-510c8b00-387f-11ea-8029-6066027d93d9.png)

The same program in Intellij IDEA

<img width="599" alt="idea-works" src="https://user-images.githubusercontent.com/5587834/72539399-8a44fb00-387f-11ea-96d5-c7671891651c.png">

**Installation:**

- Operating system: macOS
- VSCode version: 1.41.1
- VSCode extension version: 1.7.2
- Metals version: (found in VSCode settings, under `metals.serverVersion`) 0.8.0

**Additional context**

Maybe it is related to [App](https://www.scala-lang.org/api/current/scala/App.html) usage in program.

**Search terms**

metals, debug, watch

**Comment by marek1840** [comment] 2020-01-21 08:32
To summarize: "watch" functionality is not yet implemented so the watch expressions won't be evaluated, hence the `an implementation is missing` log. What we probably should do is to provide more informative information like `evaluation of expression is not implemented`.

As to the other part:
> Value from the object can be seen inside the this value, but it should also be outside, which I believe is a bug.

It is not a bug, but rather a reflection of how the `App` is implemented. We can see the same behavior in `IntelliJ` on the screenshot above: only `this` variable is in scope (and two watches but they are not related) - we could probably provide some custom handling to "extract" the variables to the outer scope for `App`s but I don't think it is worth the effort. Once we have expression evaluation, user will be able to "watch" the fields of interest.

**Comment by tgodzik** [comment] 2020-01-21 09:41
Thanks @marek1840 ! I will close it since it's working as intended.

**Closed by tgodzik** 2020-01-21 09:41 UTC
Labels: debug
