### ISSUE TITLE
.bloop folder grows without boundaries (bloop-bsp-clients-classes)

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#3020] opened 2021-08-03 13:09 UTC
**Describe the bug**

Each new run of vim + coc-metals results in new `bloop-bsp-clients-classes` entries which are identical to the previous ones:

```
$ du -sh .bloop/core/bloop-bsp-clients-classes/* 
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-5TfFX5RASPeyHEOh-O7kGQ==
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-VnEP2HueTwu_JQsGeGv7pg==
712K	.bloop/core/bloop-bsp-clients-classes/classes-Metals-ZU6uaWGiQ-eReOpykI5IaQ==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-5TfFX5RASPeyHEOh-O7kGQ==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-VnEP2HueTwu_JQsGeGv7pg==
424K	.bloop/core/bloop-bsp-clients-classes/test-classes-Metals-ZU6uaWGiQ-eReOpykI5IaQ==
```

**To Reproduce**

1. Open project in `vim`
2. Close project
3. Repeat 1-2
4. Observe `.bloop/module/bloop-bsp-clients-classes`

**Expected behavior**

Classes reused and no compilation initiated on repeated project opens

**Installation**

- Operating system: Linux
- Vim version: 8.2 8020814
- coc.nvim version: 0.0.80-9fd90ad761
- [coc-metals](https://github.com/scalameta/coc-metals/issues/410) extension version: 1.0.7
- Metals version: 0.10.5

**Comment by arbitrary-dev** [comment] 2021-08-03 17:34
The same seems to be with `.metals/metal.h2.db`

**Comment by tgodzik** [comment] 2021-08-04 09:25
Thanks for reporting! Bloop directories are removed as soon as the Metals client disconnects, I can't reproduce any issues with that myself. Would it possible that client still runs after restart? It's an issue we've seen in VS Code. @ckipp01 are you able to reproduce with coc-metals ?

As for `.metals/metals.h2.db` we use it to save some information about the workspaces, but it should not grow too much beyond the initial size, does it seem to be growing too much?

**Comment by ckipp01** [comment] 2021-08-04 09:57
So playing around with this a bit I'm also unable to reproduce. @arbitrary-dev can you check that once you close that Metals is no longer running? You should be able to use `jps` via the command line to quickly check if it goes away after you close:

_When running_:
```
❯ jps -l
10834 jdk.jcmd/sun.tools.jps.Jps
10821 scala.meta.metals.Main
```
And then when close the `scala.meta.metals.Main` should no longer be there if you do another `jps -l`.

**Comment by arbitrary-dev** [comment] 2021-08-04 10:45
Here's my `:CocConfig`…
```
{
  "metals.enable": true,
  "metals.javaHome": "/usr/lib64/openjdk-11",
  "metals.showImplicitConversionsAndClasses": true,
  "metals.showImplicitArguments": true,
}
```

While vim was opened, these processes were running:
```
$ jps -l
388 scala.meta.metals.Main
1769 sun.tools.jps.Jps
474 bloop.Server
```

Here I did a couple runs of `:CocCommand metals.compile-clean`…
```
$ rm -rf .bloop .metals 
$ vim build.sbt; du -hs .bloop .metals
548M	.bloop                      
5.7M	.metals
$ jps -l
32683 jdk.jcmd/sun.tools.jps.Jps

$ vim build.sbt; du -hs .bloop .metals
1.1G	.bloop
5.7M	.metals
$ jps -l
2157 jdk.jcmd/sun.tools.jps.Jps

$ vim build.sbt; du -hs .bloop .metals
1.6G	.bloop
5.8M	.metals
$ jps -l
4092 jdk.jcmd/sun.tools.jps.Jps
```

Some more logs:
```
2021.08.04 13:36:47 INFO  logging to file /home/man/project/.metals/metals.log
2021.08.04 13:36:47 INFO  Started: Metals version 0.10.5 in workspace '/home/man/project' for client coc.nvim 0.0.80.
2021.08.04 13:36:48 INFO  time: initialize in 1.1s
2021.08.04 13:36:49 INFO  Flyway Community Edition 7.10.0 by Redgate
2021.08.04 13:36:49 INFO  Database: jdbc:h2:file:/home/man/project/.metals/metals (H2 1.4)
2021.08.04 13:36:49 INFO  Successfully validated 3 migrations (execution time 00:00.016s)
2021.08.04 13:36:49 INFO  Current version of schema "PUBLIC": 3
2021.08.04 13:36:49 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2021.08.04 13:36:49 INFO  Attempting to connect to the build server...
2021.08.04 13:36:49 WARN  no build target for: /home/man/project/build.sbt
2021.08.04 13:36:48 INFO  skipping build import with status 'Installed'
2021.08.04 13:36:51 INFO  no build target: using presentation compiler with only scala-library: 2.12.14
2021.08.04 13:36:55 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /tmp/man/.cache/metals/bsp.trace.json
2021.08.04 13:36:55 INFO  Attempting to connect to the build server...
2021.08.04 13:36:55 INFO  Attempting to connect to the build server...
2021.08.04 13:36:55 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /tmp/man/.cache/metals/bsp.trace.json
2021.08.04 13:36:55 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /tmp/man/.cache/metals/bsp.trace.json
2021.08.04 13:36:55 INFO  time: Connected to build server in 6.31s
2021.08.04 13:36:55 INFO  Connected to Build server: Bloop v1.4.8-19-4d9f966b
2021.08.04 13:36:56 INFO  time: Imported build in 1.07s
2021.08.04 13:37:12 INFO  time: indexed workspace in 15s
2021.08.04 13:37:44 INFO  compiling …
```

**Comment by ckipp01** [comment] 2021-08-04 18:02
> While vim was opened, these processes were running:

So just to confirm, when you stopped, the metals process stopped as well right? So I tried to recreate this a few different ways and still can't seem to. There was a time where I did see some left over files from earlier, but then once Metals closed it actually cleaned up all of them.

**Comment by arbitrary-dev** [comment] 2021-08-04 20:17
>So just to confirm, when you stopped, the metals process stopped as well right?
Right.

>but then once Metals closed it actually cleaned up all of them.
Who cleans up them, Metals or Bloop? Is there a way to anyhow activate verbose logging and observe what's happening during closure?

**Comment by tgodzik** [comment] 2021-08-05 09:50
Bloop is cleaning those directories up when the client disconnects, not sure if it's possible to get the logging anywhere since the logs normally go to the client and that is being shut down.

**Comment by arbitrary-dev** [comment] 2021-08-05 12:15
Could it be that Bloop shuts down before the Metals? 🤔

**Comment by tgodzik** [comment] 2021-08-05 12:28
Bloop doesn't shut down on itself, so that should not happen. Not sure what the behaviour would be in that case

**Comment by tgodzik** [comment] 2023-09-30 17:36
I think this should be fixed now. I found an issue in Bloop that might have caused that, do let me know if you still encounter this.

**Closed by tgodzik** 2023-09-30 17:36 UTC
Labels: needs more information
