### ISSUE TITLE
False parser error in match case when guard is in a new line

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#5727] opened 2023-10-06 18:35 UTC
### Describe the bug

Use the following code:
```scala
  val z: (Int, String) => Boolean =
    case (aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb)
        if true =>
      true
    case _ => false
```
Note: I'm working with scalafmt, so I put long tuple binds to cause the guard to drop to a new line.
I get the following error:
`=> expected but \n foundscalameta`
![image](https://github.com/scalameta/metals/assets/8167952/5565cb03-1d27-4a7e-a60f-1ad08873cd13)
(the code of course compiles successfully)

### Expected behavior

No error

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v1.0.1

**Comment by jkciesluk** [comment] 2023-10-09 09:04
This should already be fixed in the latest snapshot. Can you switch to the pre-release version and see if it works for you there?

**Comment by tgodzik** [comment] 2023-11-29 09:38
Looks that I can't reproduce anymore. Let us know @soronpo if you encounter it again.

**Closed by tgodzik** 2023-11-29 09:38 UTC
