### ISSUE TITLE
Error figuring out the type of expression for Doobie sources

### ISSUE THREAD

**Issue by Z1kkurat** [scalameta/metals#1699] opened 2020-05-06 07:14 UTC
**Describe the bug**
There is a function in doobie's interpreters for getting access to underlying Java primitives which is used all over the implementation, it's signature is as follows:
```scala
def primitive[J, A](f: J => A): Kleisli[M, J, A]
```
Metals seems to be unable to figure out type of `J`.  
i.e. trait `ConnectionOp.Visitor` is parameterized with `F[_]` and defines the function `commit` as follows
```scala
def commit: F[Unit]
```
and its implemetation has the following signature
```scala
trait ConnectionInterpreter extends ConnectionOp.Visitor[Kleisli[M, Connection, *]]
```
So in this case `F` is `Kleisli[M, Connection, *]` thus return type of `def commit` is `Kleisli[M, Connection, Unit]` and type of `J` when using `primitive` is `Connection`. Metals seems to fail to figure this out though I see no error message in output or anywhere else.

**To Reproduce**
1. Check out doobie source code
2. Go to `/src/main/scala/doobie/free/kleisliinterpreter.scala`
3. Scroll down to any trait, i.e. 'ConnectionInterpreter'
4. Right-click on any function inside `primitive` helper, i.e. `def commit`, use `Go to implementations` or `Go to definition`

**Expected behavior**
metals can figure out that methods are part of `java.sql.Connection` or any other used underlying type (IntelliJ can do that)

**Screenshots**
![image](https://user-images.githubusercontent.com/7479593/81146066-3f5f0880-8f80-11ea-867c-756e2d06f437.png)
![image](https://user-images.githubusercontent.com/7479593/81146119-57cf2300-8f80-11ea-8c64-4d10f598e4cd.png)
![image](https://user-images.githubusercontent.com/7479593/81146156-674e6c00-8f80-11ea-90f7-470752e2fbd5.png)

**Installation:**
- Operating system: Windows and Linux
- Editor: Visual Studio Code
- Metals version: v0.9.0

**Additional context**
-

**Search terms**
doobie

**Comment by tgodzik** [comment] 2020-05-06 09:43
Thanks for reporting! I cannot reproduce it unfortunately:

![repro](https://user-images.githubusercontent.com/3807253/81162257-29a41000-8f8d-11ea-965f-3b34889c8336.gif)

is it possible that there are no java sources inside your java home?
I do  have them under:
`/usr/lib/jvm/java-8-openjdk/src.zip`

There should have been a warning about it somewhere in the logs.

It could possibly be a good feature request to download the java sources if they don't exist. That's most likely what Intellij does.

**Comment by Z1kkurat** [comment] 2020-05-06 10:22
Indeed, you are right. `openjdk-11-jdk` from ubuntu repositories has no sources included (should be installed separately as `openjdk-11-source`) and it has different docs location rather than oracle jdk.  
Here's a link to the bug plus workarounds https://bugs.launchpad.net/ubuntu/+source/openjdk-lts/+bug/1791219
What's interesting - after I made a symbolic link to right sources location nothing has changed. I tried reimporting build, restarting build server, clean compiling workspace, restarting VSCode and all that stuff and nothing happened. Tried even to drop `.metals` and `.bloop` directories and import anew, but no success. Any ideas what can be wrong/where to look?

**Comment by tgodzik** [comment] 2020-05-06 11:45
The logic is here, it might need some improvements for sure (maybe download sources by default?):
https://github.com/scalameta/metals/blob/feb8f8c32aaaa6edb2d7ce57fc1f3e83d9ee3815/mtags/src/main/scala/scala/meta/internal/metals/JdkSources.scala

It might be that we don't take into account symbolic links? Could you maybe try copying the src.jar into java home?

The only thing in most cases you would need to do is reload window, which will retry to look for the sources. dropping `.metals` or `.bloop` might only help in a very specific case. `.bloop` only if the compilation artifacts are broken and it doesn't help to `clean compile`. In that case even I wouldn't drop the .json files, which are just the build definition for Bloop.

**Comment by tgodzik** [comment] 2020-05-20 10:39
I think this should actually be fixed by https://github.com/scalameta/metals/pull/1763 

Previously go to definition would not work for JDK 11 source for anything but java.base module. The class you were looking for was not in the base module and we would fail to find it. I would for for JDK 8 because there are no modules.

Could you check the newest [snapshot](https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot) ?

**Comment by tgodzik** [comment] 2020-06-01 09:43
This should be already fixed in master. We can reopen if there is an issue again in 0.9.1

**Closed by tgodzik** 2020-06-01 09:43 UTC
Labels: bug
