### ISSUE TITLE
"Metals: Find text in dependency JAR files" does not seem to work

### ISSUE THREAD

**Issue by spangaer** [scalameta/metals#3726] opened 2022-03-16 12:11 UTC
### Describe the bug

1.  launch command
2. type .conf
3. type buffer (well any word failed)

VSCode Metals log -> `{"code":"Unknown","name":"Error (FileSystemError)"}`

### Expected behavior

Expect results 🤷‍♂️

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.2

**Comment by spangaer** [comment] 2022-03-16 12:28
- works in ext v1.11.1 + metals 0.11.0
- works in ext v1.12.0 + metals 0.11.1
- does not work in ext v1.13.0 + metals 0.11.2

Regression due to the virtual document change?

**Comment by dos65** [comment] 2022-03-16 12:35
@spangaer Thanks for reporting and for hint. Will look what is going wrong

**Comment by tgodzik** [comment] 2022-03-16 14:26
From what I checked the issue is when the jar is broken. Managed to reproduce it on the Metals repository. We could probably just add a Try somewhere to be sure.

**Comment by dos65** [comment] 2022-03-16 14:30
@Arthurm1 I took a look. It seems that it might be solved by introducing FileSystemProvider. 

However, I think we need to do changes on server side too. There is an issue with preview text. Currently we extract it by reading a whole file on client side that wasn't optimal even with having files on disk. It would be better to extend protocol and send prepared preview-text from the server

**Comment by Arthurm1** [comment] 2022-03-16 14:42
@dos65  OK, but if you don't want to go that far - I think you can just change the VSCode side to use `workspace.openTextDocument(uri)` instead of reading the file directly...

```typescript
async function toTopLevel(locations: Location[]): Promise<TopLevel[]> {
  const locationsByFile = new Map<string, Location[]>();

  for (const loc of locations) {
    const previous = locationsByFile.get(loc.uri) || [];
    locationsByFile.set(loc.uri, [...previous, loc]);
  }

  return await Promise.all(
    Array.from(locationsByFile, async ([filePath, locations]) => {
      const uri: Uri = Uri.parse(filePath);
      const document = await workspace.openTextDocument(uri);
      if (document) {
        const newPositions = locations.reduce((arr, location) => {
          const line = document.lineAt(location.range.start.line);
          const newPosition = new PositionInFile(
            location,
            uri,
            line.text.trimStart()
          );
          return [...arr, newPosition];
        }, [] as PositionInFile[]);
        return new TopLevel(newPositions, uri);
      } else return new TopLevel([] as PositionInFile[], uri);
    })
  );
}
```

**Comment by kpodsiad** [comment] 2022-03-30 09:43
Should be fixed in the https://github.com/scalameta/metals-vscode/pull/918.
It can be checked using `pre-release` version - instruction how to switch to it is [here](https://scalameta.org/metals/docs/editors/vscode#installation).

That's said, I'll close this issue. If you will still have problems @spangaer don't hesitate with reopening this issue.

**Closed by kpodsiad** 2022-03-30 09:43 UTC
