### ISSUE TITLE
Unused imports warnings span over the entire line

### ISSUE THREAD

**Issue by yurique** [scalameta/metals#788] opened 2019-06-21 05:12 UTC
**Is your feature request related to a problem? Please describe.**

When there's a line like this:

```
import some.package.{ Class1, Class2, Class3 }
```

and `Class3` is an unused import, metals in VS Code underlines the whole line:

```
import some.package.{ Class1, Class2, Class3 }
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

![image](https://user-images.githubusercontent.com/919230/59899102-2f881580-93fc-11e9-97cb-58124f2f9227.png)

And it's impossible to tell which one is actually unused.

**Describe the solution you'd like**

It would be great to underline just he actually unused terms.

**Search terms**:

unused imports

**Comment by jvican** [comment] 2019-06-21 09:48
This is unlikely to be caused by Bloop itself, Bloop just honours the positions coming from the compiler. Could it be that Metals is not correctly setting `-Yrangepos` in that project?

**Comment by olafurpg** [comment] 2019-06-21 09:57
The position has different start/end offsets so `-Yrangepos` is probably enabled (otherwise start would be the same as end).

This looks similar to https://github.com/scalameta/metals/issues/719#issuecomment-494725515. There's nothing we can do about it on the Metals side.

**Comment by gabro** [comment] 2019-06-21 09:58
I can confirm `-Yrangepos` is on.

My reproduction is on the Metals repo itself (module `mtags`) and the bloop definition (`mtags.json`) contains `"-Yrangepos"`

**Comment by olafurpg** [comment] 2019-06-21 10:01
The error reported by `bloop compile mtags` also doesn't specify which import is unused. The information lies in the `point` field of the reported diagnostic.

```
Compiling mtags (1 Scala source)
[W]  [E1] mtags/src/main/scala/scala/meta/internal/metals/StringBloomFilter.scala:6:28
[W]       Unused import
[W]       L6: import collection.{BitSet, SetProxy}
[W]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[W] mtags/src/main/scala/scala/meta/internal/metals/StringBloomFilter.scala: L6 [E1]
```

**Comment by olafurpg** [comment] 2019-06-21 10:03
In semanticdb-scalac we special-case the position of "unused import" error to use `point` instead of `start/end`, see https://github.com/scalameta/scalameta/blob/598f3bed3abaf4a65e042f9374f1f781b705590f/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/DiagnosticOps.scala#L14-L26

Bloop could do the same as a workaround. The long term solution would be to change the start/end positions reported by scalac. Closing since there's nothing Metals can do to fix this.

**Closed by olafurpg** 2019-06-21 10:03 UTC
Labels: bug

**Comment by jvican** [comment] 2019-06-21 10:06
That workaround could be added to bloop in https://github.com/scalacenter/bloop/blob/a58d9626a1033c025fde78654049d1f9498b55a8/backend/src/main/scala/bloop/reporter/Reporter.scala#L56-L64
