### ISSUE TITLE
Find all references does not work with nested objects

### ISSUE THREAD

**Issue by AurimasAnskaitis** [scalameta/metals#1061] opened 2019-11-12 11:01 UTC
**Describe the bug**

Find all references does not work when searching for occurrences of case class nested in a few objects.

**To Reproduce**
1. Import build from the sbt project given here: https://github.com/AurimasAnskaitis/metalsBug
2. Go to object C in package a and search for all references using context menu.

**Expected behavior**

2 occurrences of this class should be found in package main

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.7.6

**Additional context**

I noticed similar problems in real projects where not all occurrences are found and different packages are present between jump locations and/or object nesting is present

**Search terms**

Metals, scala, find all references

**Comment by tgodzik** [comment] 2019-11-12 12:12
Thanks for reporting and especially the reproduction! :tada: 

I can confirm that it doesn't work, we will try to get it fixed quickly.

**Comment by sswistun-vl** [comment] 2019-11-25 16:31
As far as I can see https://github.com/scalameta/scalameta/pull/1912 should fix that.

**Comment by tgodzik** [comment] 2020-02-20 10:45
We should most likely create a test case documenting current state and checking if it works with newer Scalameta. This might need to be transferred there is it's caused by an issue in the semanticDB plugin.

**Comment by ltrojanowski** [comment] 2020-04-17 07:38
I will check if it still doesn't work

**Comment by ltrojanowski** [comment] 2020-04-17 09:24
Still an issue with metals 0.8.4 and the current snapshot

**Comment by tgodzik** [comment] 2020-04-17 14:41
This is actually a duplicate of https://github.com/scalameta/metals/issues/1553 which is being worked on.

**Closed by tgodzik** 2020-04-17 14:41 UTC
Labels: bug
