### ISSUE TITLE
Metals gets confused by 2 files in 2 projects containing identical traits

### ISSUE THREAD

**Issue by joschua-fink** [scalameta/metals#2216] opened 2020-11-14 14:19 UTC
**Describe the bug**

I have the following project:

```scala
// build.sbt

lazy val bar = crossProject(JSPlatform, JVMPlatform)
  .in(file("."))
  .settings(scalaVersion := "2.13.3")
  .jsSettings(
    scalaJSUseMainModuleInitializer := true
  )

// project/build.properties

sbt.version=1.4.2

// project/plugins.sbt

addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.0.0")
addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.3.0")

// jvm/src/main/scala/Foo.scala

trait Foo {
  println("JVM")
}

// js/src/main/scala/Foo.scala

trait Foo {
  println("JS")
}

// shared/src/main/scala/Bar.scala

object Bar extends App with Foo
```

I get the following two projects: `barJS` and `barJVM`. The project compiles and prints `JS` for `barJS/run` and `JVM` for `barJVM/run` like you would expect.

I have encountered the following issue: If I click in Visual Studio / Metals / Packages / barJVM on Foo, it will show `js/src/main/scala/Foo.scala` instead of `jvm/src/main/scala/Foo.scala`. The same behavior occurs if I am in `barJVM / Bar` and right-click on `[...] with Foo` and click then on "Go To Definition". Again I will see `js/src/main/scala/Foo.scala` instead of `jvm/src/main/scala/Foo.scala`.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.9.5 and v0.9.4

**Comment by tgodzik** [comment] 2020-11-16 10:58
Thanks for reporting! I think the issue is the same that we don't differentiate by targets in the OnDemandSymbolIndexer. The problem is actually https://github.com/scalameta/metals/issues/1196

I will close this as a duplicate.

**Closed by tgodzik** 2020-11-16 10:58 UTC
Labels: bug

**Comment by joschua-fink** [comment] 2020-11-16 11:21
And I had been confused why nobody had encountered this issue before. It turns out, I just failed to find the issue report :-)

**Comment by tgodzik** [comment] 2020-11-16 12:10
@joschua-fink Yeah, it's a pretty old one and usually hasn't been a problem for most users. But it does become a problem in case especially jvm-js classes. I will add it to the next milestone, we should try to deal with it.

**Comment by joschua-fink** [comment] 2020-11-16 12:20
Great. For me this issue is the main reason I am not considering switching from IntelliJ to Metals at the moment. And IntelliJ doesn't do a great job either in these JVM / JS scenarios.
