### ISSUE TITLE
Worksheet doesn't stop "evaluating"

### ISSUE THREAD

**Issue by donnut** [scalameta/metals#1462] opened 2020-02-23 09:27 UTC
**Describe the bug**
When a new worksheet is created in `main/scala/` it starts evaluating, and never stops doing that without returning a result

**To Reproduce**
1. Create new, empty view `What.worksheet.sc` in `main/scala/`
2. Status bar shows `Evaluating What.worksheet.sc`
3. Type e.g. `val a = 3`
4. The `Evaluation` restarts but still now results in the worksheet

The log shows this error: 
```
INFO  time: evaluated worksheet 'What.worksheet.sc' in 12s
Exception in thread "Evaluating Worksheet What.worksheet.sc" java.lang.IncompatibleClassChangeError: class mdoc.internal.markdown.FilterStoreReporter has interface scala.tools.nsc.reporters.FilteringReporter as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at mdoc.internal.markdown.MarkdownCompiler$.fromClasspath(MarkdownCompiler.scala:92)
	at mdoc.internal.worksheets.Mdoc.context(Mdoc.scala:57)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:47)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:18)
	at scala.meta.internal.worksheets.WorksheetProvider.$anonfun$evaluateWorksheet$2(WorksheetProvider.scala:225)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:223)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:142)

```
**Expected behavior**
I expect the expression in the worksheet to be evaluated and to be shows as a result

**Screenshots**
![image](https://user-images.githubusercontent.com/417406/75109718-58654800-5626-11ea-8537-2f0a7bfa0d44.png)

**Installation:**
- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
I noticed the icon in front the of name of the worksheet isn't the scala logo (as it is in the example https://scalameta.org/metals/blog/2020/01/10/cobalt.html#worksheet-support), but the logo for plain text.

**Search terms**
worksheet evaluation infinite

**Comment by tgodzik** [comment] 2020-02-24 10:38
Thanks for reporting, this is most likely connected to an issue in Mdoc or the way we create the classlaoder for it. What is the Scala version you are using?

**Comment by donnut** [comment] 2020-02-24 18:25
I might have had an inconsistency in the scala versions. I had no scala installed, only sbt. `sbt console` showed scala version 2.12.10. After reading you comment @tgodzik I installed scala 2.13.1 through sdkman, restarted `code` and now it works.

**Comment by tgodzik** [comment] 2020-02-24 18:59
You don't need to install Scala, it should have worked without it. The stack trace you posted does indicate an issue though, which might have disappeared after restarting.

Let us know if it happens again!

**Comment by rcano** [comment] 2020-03-01 14:46
Came to report the same issue, found the same solution: updating to scala 2.13.1 *and* restarting vscode.

If I switch back to 2.13.0, bug is there.

**Comment by olafurpg** [comment] 2020-03-12 11:04
Thank you for reporting! Closing this as a duplicate of https://github.com/scalameta/metals/issues/1462

Non-fatal exceptions are not being caught when evaluating worksheets.

**Comment by olafurpg** [comment] 2020-03-12 11:05
Sorry, meant closing this as a duplicate of https://github.com/scalameta/metals/issues/1456

**Closed by olafurpg** 2020-03-12 11:04 UTC
Labels: bug, needs more information
