### ISSUE TITLE
Autocompletion is broken on conflicting "encoding" scalac flag

### ISSUE THREAD

**Issue by dpfeiffer** [scalameta/metals#1303] opened 2020-01-14 13:53 UTC
**Describe the bug**
For any project where the build contains the play sbt-plugin in `plugins.sbt` and the project has the `PlayScala` plugin enabled autocompletion does not work.

The `metals.log` file contains an interesting error

```
SEVERE: requirement failed: List(utf8)
java.lang.IllegalArgumentException: requirement failed: List(utf8)
	at scala.Predef$.require(Predef.scala:281)
```

When hunting this down I figured out that the only thing which sets anything regarding the string `utf8` I found that the play sbt-plugin sets the `scalacOption` `-encoding` to `utf8`. See: https://github.com/playframework/playframework/blob/ddf3a7ee4285212ec665826ec268ef32b5a76000/dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L51

When explicitly removing the encoding set by play, everything goes back to normal. (See code snippet below where `scalacOptions` modification is commented.

**To Reproduce**
1. Create a new sbt project containing the play sbt-plugin

`plugins.sbt`
```scala
addSbtPlugin("com.typesafe.play" % "sbt-plugin"    % "2.7.4")
```

`build.sbt`
```scala
lazy val root = project
  .in(file("."))
  .settings(
    name := "test"
    // scalacOptions := scalacOptions.value.filter(o => o != "-encoding" && o != "utf8"  && o != "utf-8"),
  )
  .enablePlugins(PlayScala)
```

2. Create a new scala source file
3. Try very simple autocomplete e.g. `"".toUpp....`

**Expected behavior**
Autocomplete should be working

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Comment by gabro** [comment] 2020-01-14 14:08
Thanks for reporting!

I've tried to reproduce this but I couldn't. Here's my attempt: https://github.com/gabro/metals-issue-1303

As you can see from the screenshot, autocompletions seem to work fine

![image](https://user-images.githubusercontent.com/691940/72350906-9abe6f80-36df-11ea-8a29-39d009cee123.png)

Would you mind trying to play around with my example (or come up with a different one) and see whether you can reproduce this? I suspect there's something else other than the `encoding` option

**Comment by dpfeiffer** [comment] 2020-01-14 14:39
@gabro I think I was able to reproduce it, unfortunately I forgot that a corporate sbt plugin is enabled which adds `scalacOptions` according to this suggestion: https://tpolecat.github.io/2017/04/25/scalac-flags.html

The suggestion is to set `-encoding` to `utf-8` <- see the `-` and if you have both options in the `scalacOptions` it seems to fail with `java.lang.IllegalArgumentException: requirement failed: List(utf8)` or `java.lang.IllegalArgumentException: requirement failed: List(utf-8)` depending on which one is defined later.

I modified your example so that autocomplete stops working: https://github.com/dpfeiffer/metals-issue-1303 even without any corporate sbt plugin just by adding the `-encoding` flag manually in the build definition.

In your example you have not used the directory layout that is enforced by play (`app` instead of `src/main/scala`)  which I quickly changed and made it the root project.

If both plugins `PlayScala` and the corporate one set the encoding to `utf8` without the dash, than it seems to be working.

**Comment by tgodzik** [comment] 2020-01-14 14:59
From what I see it should be `-encoding utf8` based on https://docs.scala-lang.org/overviews/compiler-options/index.html

The error comes from the Scala Presentation Compiler I believe, so I think it should be fixed in the plugin. The only thing we can do is to translate or remove the flag inside Metals, which is rather a hack.

**Comment by dpfeiffer** [comment] 2020-01-14 17:16
I am actually wondering why this did not cause any issues prior to metals 0.8.0 because we have been using metals for a while now with exactly this misconfiguration of the compiler options.

The blog article I was referring to, seems to be a regular reference for configuring the compiler options which might cause issues for more people. I know that it is already "outdated" as it refers to Scala 2.12 but quickly googling for Scala 2.13 compiler flags yields results where the `-encoding` flag is set to `utf-8` as well.

**Closed** 2020-01-18 18:49 UTC

**Comment by j-potts** [comment] 2020-01-27 16:37
@dpfeiffer Were you able to work around this in some capacity? I wasn't able to follow within the convo if a work around is available.

**Comment by tgodzik** [comment] 2020-01-27 16:49
The most recent snapshots should have this fixed.

**Comment by j-potts** [comment] 2020-01-27 16:53
Sounds good, thanks @tgodzik !

**Comment by Baccata** [comment] 2020-02-06 11:32
@tpolecat, pinging you because I encountered the same bug : I'm always using your list of useful compiler flags : http://tpolecat.github.io/2017/04/25/scalac-flags.html. You might want to update the blog entry to change `utf-8` for `utf8`

**Comment by tgodzik** [comment] 2020-02-06 11:34
That's according to docs: https://docs.scala-lang.org/overviews/compiler-options/index.html

And the presentation compiler doesn't accept that option.

**Comment by tpolecat** [comment] 2020-02-06 15:15
@Baccata thanks!
