### ISSUE TITLE
`documentHighlight` highlighting entire chunk of code

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#3563] opened 2022-01-24 13:02 UTC
### Describe the bug

While navigating around the Dotty code base I came across a situation where Metals started highlighting the entire code block.

Starting here in `Desurgar.scala` you can see it's working normal, and then starts highlighting the entire block:

https://github.com/lampepfl/dotty/blob/26dbd774eadfa4b5e66dae098f2695da91b5e154/compiler/src/dotty/tools/dotc/ast/Desugar.scala#L393

![2022-01-24 14 01 39](https://user-images.githubusercontent.com/13974112/150787499-679a4c75-edc0-412e-b510-63df148b7f3f.gif)

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.1+22-bc2fa7a6-SNAPSHOT

**Comment by dos65** [comment] 2022-01-24 13:09
@ckipp01 I'll close it as it's a duplicate of #3053

**Comment by ckipp01** [comment] 2022-01-24 13:10
> @ckipp01 I'll close it as it's a duplicate of #3053

Ahh sorry I totally missed that. Thanks!

**Closed by dos65** 2022-01-24 13:09 UTC
Labels: Scala 3
