### ISSUE TITLE
java.lang.BootstrapMethodError thrown when writing a `.` (dot) to access an object/class member

### ISSUE THREAD

**Issue by caenrique** [scalameta/metals#4068] opened 2022-06-26 21:09 UTC
### Describe the bug

When accessing a member of an object or class, this exception gets thown and I'm not getting completions.

full stack trace:

```
Exception in thread "pool-6-thread-1" java.lang.BootstrapMethodError: java.lang.IllegalAccessEr
ror: Class 'scala.tools.nsc.interactive.Global' no access to: class 'scala.collection.immutable
.LazyList$State'
        at scala.tools.nsc.interactive.Global.typeMembers(Global.scala:1155)
        at scala.tools.nsc.interactive.Global.typeCompletions$1(Global.scala:1219)
        at scala.tools.nsc.interactive.Global.completionsAt(Global.scala:1262)
        at scala.meta.internal.pc.CompletionProvider.safeCompletionsAt(CompletionProvider.scala
:428)
        at scala.meta.internal.pc.CompletionProvider.completions(CompletionProvider.scala:58)
        at scala.meta.internal.pc.ScalaPresentationCompiler.$anonfun$complete$1(ScalaPresentati
onCompiler.scala:125)
        at scala.meta.internal.pc.ScalaPresentationCompiler$$Lambda$4458/00000000782C3420.apply
(Unknown Source)
        at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$withInterruptableCompiler$1(CompilerA
ccess.scala:87)
        at scala.meta.internal.pc.CompilerAccess$$Lambda$3408/000000007A468620.apply(Unknown So
urce)
        at scala.meta.internal.pc.CompilerAccess.$anonfun$onCompilerJobQueue$1(CompilerAccess.s
cala:197)
        at scala.meta.internal.pc.CompilerAccess$$Lambda$3206/0000000078ACCA20.apply$mcV$sp(Unk
nown Source)
        at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:139)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:823)
Caused by: java.lang.IllegalAccessError: Class 'scala.tools.nsc.interactive.Global' no access t
o: class 'scala.collection.immutable.LazyList$State'
        at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1086)
        at java.lang.invoke.MethodHandle.getCPMethodHandleAt(Native Method)
        at java.lang.invoke.MethodHandle.getAdditionalBsmArg(MethodHandle.java:869)
        at java.lang.invoke.MethodHandle.resolveInvokeDynamic(MethodHandle.java:948)
        ... 16 more
Caused by: java.lang.IllegalAccessException: Class 'scala.tools.nsc.interactive.Global' no acce
ss to: class 'scala.collection.immutable.LazyList$State'
        at java.lang.invoke.MethodHandles$Lookup.checkClassAccess(MethodHandles.java:449)
        at java.lang.invoke.MethodHandles$Lookup.accessCheckArgRetTypes(MethodHandles.java:686)
        at java.lang.invoke.MethodHandle.sendResolveMethodHandle(MethodHandle.java:1060)
        ... 19 more

```

### Expected behavior

Get completions for the object/class members, and no exception thrown

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.6

**Comment by tgodzik** [comment] 2022-06-27 07:08
Thanks for reporting! Could you also send us the code that it's failing for? Also, what Scala version are you using?

**Comment by caenrique** [comment] 2022-06-27 10:23
I just found that it works with Scala `2.13.3`. After `2.13.4` (including that one) it throws the exception

**Comment by tgodzik** [comment] 2022-06-27 10:28
I can't seem to reproduce it. What code exactly does it fail on? What Java version are you using?

**Comment by dos65** [comment] 2022-06-27 10:29
@caenrique 
Thanks for providing updates and additional info but to investigate it we need a snippet to be able to reproduce it.
Does completion works in the case below?
```scala
object sample {
  42.@@ // 
}
```

**Comment by caenrique** [comment] 2022-06-27 10:47
> I can't seem to reproduce it. What code exactly does it fail on? What Java version are you using?

I've tested with java 8 and java 11

> @caenrique Thanks for providing updates and additional info but to investigate it we need a snippet to be able to reproduce it. Does completion works in the case below?
> 
> ```scala
> object sample {
>   42.@@ // 
> }
> ```

No, it also fails on that example when writing the  `.`

**Comment by ckipp01** [comment] 2022-06-27 10:51
For what it's worth I thought this _might_ be due to something related to how the change was being sent to metals via Neovim, but I just tested with the code snippet above and also can't reproduce it.

**Comment by tgodzik** [comment] 2022-06-27 10:58
This looks like the scala-library is in a separate classloader, but that doesn't seem possible. Or maybe there is a problem with the jar itself? Did you try removing the cached scala-libary jars in the coursier dir?

**Comment by caenrique** [comment] 2022-06-27 11:19
> This looks like the scala-library is in a separate classloader, but that doesn't seem possible. Or maybe there is a problem with the jar itself? Did you try removing the cached scala-libary jars in the coursier dir?

I tried removing the coursier cache dir, but the same thing happens with the mentioned java versions.

I'm ok with this now. I can use the more recent java versions, but it's definitely weird that this happens :(

Thanks for your help!

**Comment by tgodzik** [comment] 2022-06-27 11:31
That is weird, those compiler versions should correctly work with an older Java version also :thinking:

**Comment by tgodzik** [comment] 2022-07-01 08:43
I will go ahead and close it since it seems to work correctly on newest Java versions.

**Closed by tgodzik** 2022-07-01 08:43 UTC
