### ISSUE TITLE
Wrong code folding in Scala3

### ISSUE THREAD

**Issue by Meowcolm024** [scalameta/metals#4190] opened 2022-07-26 03:42 UTC
**Describe the bug**

Code blocks do not fold well with the new syntax introduced by Scala 3

**Expected behavior**

Should fold like code block with braces

**Screenshots**

**Using indent and colon only**

<img width="386" alt="螢幕截圖 2022-07-26 上午11 36 19" src="https://user-images.githubusercontent.com/23007687/180917777-bcec9c28-b357-4bf5-abe0-00993d7ad4a8.png">
<img width="351" alt="螢幕截圖 2022-07-26 上午11 36 27" src="https://user-images.githubusercontent.com/23007687/180917780-e6dea3f0-8fb9-4ce3-9933-c99ca675da27.png">

**Using the old way**

<img width="385" alt="螢幕截圖 2022-07-26 上午11 37 01" src="https://user-images.githubusercontent.com/23007687/180917785-691ed6a1-2ce6-49a3-8db1-1c9c1388eb97.png">
<img width="384" alt="螢幕截圖 2022-07-26 上午11 37 09" src="https://user-images.githubusercontent.com/23007687/180917787-fe067010-0efb-49ce-a77d-dfacc1c59bc0.png">

**Installation:**

- Operating system: macOS
- VSCode version: 1.69.2 (Universal)
- VSCode extension version: v1.18.0
- Metals version: 0.11.7

**Comment by tanishiking** [comment] 2022-07-26 05:37
@Meowcolm024 Thank you for reporting! I transferred this issue to `scalameta/metals` as it seems a bug in the Language Server implementation, not vscode specific.

Indeed `yield()` should be folded even in Scala3 :+1:

**Comment by tanishiking** [comment] 2022-07-26 06:48
Realized the root cause is https://github.com/scalameta/metals/blob/81b014d4deb62f55fdef99f266e2aedf02efcc90/metals/src/main/scala/scala/meta/internal/parsing/FoldingRangeProvider.scala#L86-L91
we `-1` from the end line of folding range to preserve end of the block `}`.

However, in braceless syntax, we don't need this adjustment.

**Closed** 2022-07-27 02:46 UTC
Labels: bug, Scala 3
