### ISSUE TITLE
Unable to use worksheets if using scalatags + `withDottyCompat` and Dotty

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#2024] opened 2020-08-25 19:25 UTC
**Describe the bug**
This is a super niche bug that I'm not 100% sure is even Metals, but could just lie somewhere the the combination listed in the title. If you are in a Dotty project and you use [scalatags](https://github.com/lihaoyi/scalatags) via `withDottyCompat` you get the same odd error in worksheets no matter what, even with the project compiling correctly. For example, in a worksheet as simple as below:

```scala
val x = 3
```
You'll see a diagnostic that is returned (always without a position, so it just appears at line 0) that looks something like this:

```
[mdoc] [E] test.worksheet.sc:9 (mdoc generated code) Found:    (App.this.x : Int)
Required: sourcecode.Text[A]

where:    A is a type variable with constraint 

    $doc.binder(x, 0, 0, 0, 9)

256
```

**To Reproduce**
1. Use the `New Scala Project` command to create a new project via the `lampepfl/dotty.g8` template
2. Use the default build definition, but add the following
```scala
    libraryDependencies += ("com.lihaoyi" %% "scalatags" % "0.9.1")
      .withDottyCompat(dottyVersion)
```
3. Create a worksheet in `src/main/scala`
4. Add anything to it and attempt to evaluate

**Expected behavior**
Since this is compiling correctly when used in a module I'd expect this to also work with worksheets.

**Installation:**
- Operating system: macOS
- Editor: Any
- Metals version: v0.9.3 and later

**Additional context**
I thought this may be in general when using `withDottyCompat`, but trying out also having other dependencies via `withDottyCompat` on the classpath didn't cause any issues. Using the same code and also having Doodle on the classpath with 2.13 also caused no issues for worksheets. So again, it's some odd combination with worksheets, dotty, and scalatags + `withDottyCompat`.

cc @eloots @noelwelsh

**Search terms**
worksheets, dotty

**Comment by noelwelsh** [comment] 2020-08-25 19:39
Wow, that's weird. The only unusual things that I can think of in Doodle are:

* using the Java2D / Swing APIs (which are standard Java, but most Scala programs don't touch them.)
* using Haoyi's Scalatags library, which *might* use some macros.

I don't see why these would cause issues if no Doodle code is being called.

**Comment by ckipp01** [comment] 2020-08-25 19:44
> using Haoyi's Scalatags library, which might use some macros.

oooooo, that's a good call. I just checked this out and this is indeed the issue. Just using Scalatags with `withDottyCombat` gives the same exact error! I'll update the ticket. Sorry to point it at Doodle!

**Comment by olafurpg** [comment] 2020-08-26 08:05
This is an interesting issue. The problem appears to be caused by the fact that we have conflicting versions of `com.lihaoyi:sourcecode` on the classpath, one for dotty and one for 2.13
```sh
❯ cs fetch org.scalameta:mdoc-runtime_0.26:2.2.5 | grep sourcecode
/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_0.26/0.2.1/sourcecode_0.26-0.2.1.jar
❯ cs fetch com.lihaoyi:scalatags_2.13:0.9.1 | grep sourcecode
/Users/lgeirsson/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.13/0.2.1/sourcecode_2.13-0.2.1.jar
```
It looks like the `_2.13` sourcecode is picked instead of `_0.26` and the `sourcecode.Text.generate` macro is not getting expanded. I am not sure what is the best solution to this problem. Maybe it's possible to use the work by James Thompson on the tasty reader (cc/ @bishabosha) https://contributors.scala-lang.org/t/roadmap-for-the-tasty-reader-for-scala-2/4231/18

**Comment by olafurpg** [comment] 2020-08-26 08:07
To elaborate, the `$doc.binder` method has the following signature
```scala
def binder[T](x: sourcecode.Text[T], ...): Unit
```

where there is an implicit macro conversion in the `Text` companion object
```scala
object Text {
  implicit def generate[T](value: T): sourcecode.Text[T] = macro impl
}
```

I suspect the compile error comes from the fact that Dotty doesn't expand the macro and therefore doesn't discover the implicit conversion resulting in the compile error

```scala
Found:    (App.this.x : Int)
Required: sourcecode.Text[A]
```

**Comment by tgodzik** [comment] 2020-08-26 12:30
I managed to get it work with:
```
    libraryDependencies ++= List(
      "com.lihaoyi" %% "sourcecode" % "0.2.1",
      ("com.lihaoyi" %% "scalatags" % "0.9.1")
          .excludeAll(ExclusionRule(organization = "com.lihaoyi", name = "sourcecode_2.13"))
          .withDottyCompat(scalaVersion.value),
      "ch.epfl.lamp" %% "dotty-compiler" % scalaVersion.value
    )
```

Though, I think it's probably best to wait until scalatags is released for Scala 3, which is already planned. This should solve the issue and everything that we can do on Metals/Mdoc side will be much more difficult I think.

**Comment by olafurpg** [comment] 2020-08-27 08:43
It's great to know a workaround exists. Given that sourcecode is a commonly shared dependency between libraries I am concerned this approach is not scalable. It might be worth inlining the sourcecode dependency into the mdoc-runtime module to avoid the need for workarounds.

**Comment by kpbochenek** [comment] 2020-08-27 08:57
I think it would be much nicer to try shading sourcecode library instead of brurally inlining it
https://github.com/sbt/sbt-assembly/blob/db69ab53cdbf0bfb3cff07183355a74c6ce49f14/README.md#shading

**Comment by eloots** [comment] 2020-08-28 10:01
> I managed to get it work with:
> 
> ```
>     libraryDependencies ++= List(
>       "com.lihaoyi" %% "sourcecode" % "0.2.1",
>       ("com.lihaoyi" %% "scalatags" % "0.9.1")
>           .excludeAll(ExclusionRule(organization = "com.lihaoyi", name = "sourcecode_2.13"))
>           .withDottyCompat(scalaVersion.value),
>       "ch.epfl.lamp" %% "dotty-compiler" % scalaVersion.value
>     )
> ```
> 
> Though, I think it's probably best to wait until scalatags is released for Scala 3, which is already planned. This should solve the issue and everything that we can do on Metals/Mdoc side will be much more difficult I think.

Thanks @olafurpg
This at least allows us to circumvent the problem for our use case (until this is resolved in a more fundamental way)

**Comment by olafurpg** [comment] 2020-08-28 12:35
> I think it would be much nicer to try shading sourcecode library instead of brurally inlining it

@kpbochenek shading often doesn't work well with macro libraries since the implementation itself generates code for the `sourcecode.Text` namespace. The `Text.generate` macro is pretty trivial. You can copy-paste it from MUnit for Scala 2 + Dotty https://github.com/scalameta/munit/blob/1330ddaeac788a4a4f1c796342ad1e318f729a54/munit/shared/src/main/scala/munit/Clue.scala

**Comment by kpbochenek** [comment] 2020-08-28 13:05
Ahh okay so keeping dependency to sourcecode as is but only copy this small part with macro, that sounds much better :+1:

**Comment by julienrf** [comment] 2020-09-02 08:43
> The problem appears to be caused by the fact that we have conflicting versions of `com.lihaoyi:sourcecode` on the classpath, one for dotty and one for 2.13

Which project pulls the Scala 2 one? We only have one Scala 3 worksheet. Or is it that it is a dependency of worksheets? In that case, yes, I think we should shade it (and all the others dependencies of the worksheets) or find a way to use distinct classpaths for evaluating the worksheets and rendering the worksheets.

**Comment by olafurpg** [comment] 2020-09-02 08:56
The classpath of mdoc itself is already isolated from the user's classpath. We still have an mdoc-runtime classpath that only includes the necessary dependencies for the code instrumention, which includes sourcecode_0.27. The problem happens when the user brings in a dependency like scalatags_2.13 that transitively includes sourcecode_2.13, which conflicts with sourcecode_0.27. The best solution is to remove all external dependencies from the mdoc-runtime artifact (it's only pprint, which transitively brings in fansi and sourcecode).

**Comment by olafurpg** [comment] 2020-09-02 08:57
It should only require a small effort to inline the implementation of `sourcecode.Text` to avoid this problem

**Comment by tgodzik** [comment] 2020-09-02 09:06
I might need to do it anyway now to make the releases for Scala 3 faster.

**Comment by eloots** [comment] 2020-09-02 09:14
@olafurpg 

> It should only require a small effort to inline the implementation of `sourcecode.Text` to avoid this problem

That would be great as it removes the dependency on `sourceCode`...

Another question though; is my previous understanding that the problem would be solved when scalatags is released for Scala 3 correct?

There was a recent flurry of releases of Li Haoyi libraries to Scala 3 (mainly by the Dotty team). Scalatags wasn't [yet] done and I don't know if [and when] it's planned.

By the way, as soon as this problem is fixed, we can use VCS/Metals to run worksheets as part of an upcoming Scala 3 course...

**Comment by tgodzik** [comment] 2020-09-02 11:45
I started looking into that, since it might also help us to fix issues quicker.

**Comment by olafurpg** [comment] 2020-09-02 13:44
@eloots this issue will continue to persist for any Scala 2 library that transitively brings in `com.lihaoyi:sourcecode_2.13`, which I suspect is quite many libraries

**Closed** 2020-09-09 16:58 UTC

**Comment by tgodzik** [comment] 2020-09-09 18:17
@eloots it should work now with the newest snapshot version as shown here: https://scalameta.org/metals/docs/editors/overview.html
In VS Code this will only require changing the `metals.serverVersion` setting and reloading. Let me know if there are some issues still!
