### ISSUE TITLE
Metals 1.4 fails compilation with Wartremover installed

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#6889] opened 2024-10-25 20:27 UTC
### Compiler quits with Wartremover Enabled

During today's upgrade from 1.3.5 to 1.4.0, I noticed that compilation of our projects just stopped compiling after a couple of projects. After looking at the bloop errors, I decided to remove WartRemover from our environment to see if that was cousing the issue. Once removed, Metals started working again.
 
I removed the following:

```plugins.sbt
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.2.3")
```

```build.sbt
ThisBuild / wartremoverErrors ++= Seq(
  Wart.ArrayEquals,
  Wart.Recursion
)

ThisBuild / wartremoverExcluded += baseDirectory.value / "code" / "orion" / "ml-config-core" / "src" / "main" / "scala" / "db"
```

I've included the errors we were seeing. 
[reports.zip](https://github.com/user-attachments/files/17527257/reports.zip)

Here are another set of errors after removing wartremover, but Metals does seem to work.

[reports_removed_wartremover.zip](https://github.com/user-attachments/files/17527419/reports_removed_wartremover.zip)

### Expected behavior

I expect Metals to be tolerant of Wartremover, and continue to compile all of the code.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.4.0

### Extra context or search terms

wartremover

**Comment by andyczerwonka** [comment] 2024-10-25 20:35
Also looks like there's a solution coming. https://github.com/scalacenter/bloop/pull/2485

**Comment by agilesteel** [comment] 2024-10-25 21:18
We ran into the same issue. There is an even smaller reproduction (hello world essentially) that I reported on [discord](https://discord.com/channels/632642981228314653/632652693013528589/1299013354332880908). I'll paste it here. Maybe someone will find it useful:

`build.sbt`
```scala
scalaVersion := "2.13.15"
wartremoverWarnings := Warts.all
```
`project/plugins.sbt`
```scala
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "3.2.3")
```
`src/main/scala/Main.scala`
```scala
object Main extends App
```

**Comment by tgodzik** [comment] 2024-10-25 22:52
Thanks! I think I already have a fix. As soon as it's merged I will release bloop, then probably metals also

**Comment by andyczerwonka** [comment] 2024-10-28 20:59
@tgodzik can we close this as part of https://github.com/scalacenter/bloop/pull/2485, or just waiting on a release?

**Comment by tgodzik** [comment] 2024-10-29 09:46
I wanted to fix one thing before the release, should be this week. I will close this issue with the update of default Bloop version

**Comment by andyczerwonka** [comment] 2024-11-04 15:59
> I wanted to fix one thing before the release, should be this week. I will close this issue with the update of default Bloop version

Just curious if this fix is coming shortly?

**Comment by tgodzik** [comment] 2024-11-04 16:00
I will release bloop tomorrow and you can check it out first.

**Comment by agilesteel** [comment] 2024-11-07 13:40
I think `2.0.4` has issues. It doesn't even start. See how there is no output for `2.0.4` but there is for `2.0.3`?

![bloop](https://github.com/user-attachments/assets/98a012d9-b23a-4058-94ab-e57c0bdc0426)

Another thing: the screenshot above was taken in Ubuntu (WSL actually). Bloop is available on arm since 2.0 but coursier doesn't want to launch it so `cs launch bloop:1.6.0 -- about` works but `cs launch bloop:2.0.3 -- about` doesn't. The screenshot below is from an m2 mac.

![mac](https://github.com/user-attachments/assets/bad119d1-e49c-4bf2-8331-e5ebb37ce9ef)

**Comment by tgodzik** [comment] 2024-11-07 15:50
I am doing 2.0.5 release to fix things, but not sure about the second issue. Does it work if you do `cs install bloop:2.0.3` ? Or `cs launch ch.epfl.scala:bloop-cli_2.12:2.0.3` ?

**Comment by tgodzik** [comment] 2024-11-08 10:10
The update to Bloop 2.0.5 was merged. If testing the nightly, you need to reimport the build for it to effect things. I will do a release next week.

**Closed by tgodzik** 2024-11-08 10:10 UTC
Labels: fixed-upstream, bloop

**Comment by andyczerwonka** [comment] 2024-11-13 22:47
We still don't have a 1.4.1 Metals release, so not sure this should be marked done? I realize it's a bloop issue, but Metals is specific about what version of bloop. I realize we can override, but users won't know to do that when they encounter the issue.

**Comment by agilesteel** [comment] 2024-11-14 01:08
I agree. For what it's worth I confirm that it works with the pre-release `1.4.1`. The bloop version needs to be explicitly set to `2.0.5` in the settings though. Merely using the `2.0.5` is not enough. The project needs to be generated with `2.0.5`. Can't wait for the proper release...

**Comment by ritschwumm** [comment] 2024-11-15 18:08
just tried with metals 1.4.1 and the only way to actually get rid of the errors was nuking all `.metals` and `.bloop` directories in the project - none of the build commands in metals made the error go away before. is this behaviour expected?

**Comment by tgodzik** [comment] 2024-11-15 18:13
Did you reimport the build? You can always try to run with a verbose compilation and see if that shows what parameters are exactly used to compile.

**Comment by ritschwumm** [comment] 2024-11-15 18:22
i restarted bloop as requested by metals, 

i imported the build, i did a clean compile, i tried "clean and restart build server" "restart build server".

then i stopped code, killed bloop in the terminal and restarted code, then tried all of the above again.

after that i did the nuking and imported the build again for good measure, and everything was fine.

**Comment by agilesteel** [comment] 2024-11-15 18:55
Wait am I the only who nukes those folders on a daily bases? 🙈

**Comment by tgodzik** [comment] 2024-11-15 18:57
The should not be necessary, but `reset workspace` will do that for you. If that doesn't help would be cool to get some information about what is going wrong.

**Comment by agilesteel** [comment] 2024-11-15 19:12
Oh is that a new button? I'll try and report back...

**Comment by tgodzik** [comment] 2024-11-15 19:17
![image](https://github.com/user-attachments/assets/d23220c0-9a5a-480a-a27b-dc0bd86b6273)

This one

**Comment by ritschwumm** [comment] 2024-11-15 20:08
@tgodzik makes me wonder - if "clean and restart build server" nukes the .bloop and .metals folders, then why would me doing that manually make any difference? i'll check if it see the same behaviour on one of my other projects.

**Comment by tgodzik** [comment] 2024-11-16 19:37
It doesn't fully remove .bloop and .metals, only the Bloop artifacts, everything else should not cause any issues. It's just Metals indexes and some information about when was the project last imported etc. And also bloop json files, which should be correct also
