### ISSUE TITLE
Go to definition not working for extension methods

### ISSUE THREAD

**Issue by prolativ** [scalameta/metals#5522] opened 2023-08-04 10:29 UTC
### Describe the bug

```scala
//> using scala 3.3.0

trait Foo[A]:
  def aaa = "aaa"

object Foo:
  extension (foo: Foo[B])
    def bbb = "bbb"

  given {} with
    extension (foo: Foo[B])
      def ccc = "ccc"

class B

object B:
  extension (foo: Foo[B])
    def ddd = "ddd"

  given {} with
    extension (foo: Foo[B])
      def eee = "eee"

given {} with
  extension (foo: Foo[B])
    def fff = "fff"

val foo = new Foo[B] {}
val a = foo.aaa
val b = foo.bbb
val c = foo.ccc
val d = foo.ddd
val e = foo.eee
val f = foo.fff
```
`Go to definition` works for a member (`foo.aaa`) but not for extension methods

### Expected behavior

`Go to definition` should work for extension methods as well

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

1.0.0+25-36394776-SNAPSHOT

**Comment by tgodzik** [comment] 2023-08-04 10:50
Thanks for reporting! It seems that it's the compiler not giving us enough info. Maybe this is done at a later phase? Any idea?

**Comment by prolativ** [comment] 2023-08-04 11:08
It looks like `Go to definition` works if an extension method is directly available in the scope of application - because it was defined there or brought by an import. e.g.
```scala
// ...

extension (foo: Foo[B])
  def ggg = "ggg"
  
import Foo._

val foo = new Foo[B] {}
val b = foo.bbb
val g = foo.ggg

```

**Comment by jkciesluk** [comment] 2023-08-04 12:58
It looks like 
```scala
trait Foo[A]:
  def aaa = "aaa"

object Foo:
  extension (foo: Foo[B])
    def bbb = "bbb"
    
class B

val foo = new Foo[B] {}

// <<>> marks span
val a = <<foo.aaa>> // the tree is Select(qualifier = Ident(name = foo), name = aaa)
val b = <<>>foo.bbb // the tree is 
// Apply(
//  fun = Select(qualifier = Ident(name = Foo), name = bbb),  - this part has incorrect span, which is just an offset of `foo`
//  args = List(Ident(name = foo))
// )

```
Probably this issue is caused by incorrect span of `Select` tree, so it might need upstream fix in the compiler

**Comment by kasiaMarek** [comment] 2023-09-28 12:24
This is fixed by https://github.com/scalameta/metals/pull/5640 and https://github.com/lampepfl/dotty/pull/18557.

**Closed by kasiaMarek** 2023-09-28 12:24 UTC
