### ISSUE TITLE
Rename refactoring does not work in VS Code

### ISSUE THREAD

**Issue by abzif** [scalameta/metals#2537] opened 2021-02-22 10:07 UTC
**Describe the bug**

Rename refactoring does not work in VS Code

**To Reproduce**

Let's assume we have a simple scala code:
val a = 5
val b = a + 7

Put cursor on variable 'a' and press (Ctrl + Shift + R) - VS Code shows "No refactorings available"
or alternatively
Put cursor on variable 'a' and press F2 (shortcut for rename refactoring). It is possible to rename the variable but reference in the next line is not updated.

**Expected behavior**

Symbol name (variable name, function name, class name) and its references should be changed across the project - in the same file and other files referencing the symbol in the project.

**Installation:**

- Operating system: Windows 10
- Editor: Visual Studio Code version 1.53.2
- Extension Scala Metals version 1.9.13
- Extension Scala syntax version 0.5.1 (dependency of Scala Metals)
- Metals version: 0.9.10

**Comment by tgodzik** [comment] 2021-02-22 10:20
Thanks for reporting! I think `No refactorings available` is actually shown for code actions and rename is not part of those.

As for F2, could you provide a more complete example? Is this file in a project? Is it just a single file? There are some cases that rename will not work, which will be fixed by the next PR.

**Comment by tgodzik** [comment] 2021-02-22 10:37
Reported here: https://github.com/lampepfl/dotty/issues/11498

**Comment by abzif** [comment] 2021-02-22 11:32
[scala-example.zip](https://github.com/scalameta/metals/files/6021589/scala-example.zip)

Please look at the attached example. It is a very simple sbt project.
Look at comments in **Base** source file regarding variable, function and trait renaming

It seems that there are two problems here:
- Renaming seems to work properly if variable is referenced in a different file. However local references are not updated
- Subsequent try to rename fails with message that element cannot be renamed

**Comment by tgodzik** [comment] 2021-02-22 11:49
Can't seem to reproduce your issue:

![testing](https://user-images.githubusercontent.com/3807253/108704474-5c16fd80-750c-11eb-9521-04f879e26cde.gif)

do you get any errors or warning in `.metals/metals.log` ?

**Comment by abzif** [comment] 2021-02-22 12:10
Indeed, in the metals.log I got something like:

lut 22, 2021 1:08:59 PM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: null
java.nio.file.ProviderMismatchException
	at sun.nio.fs.WindowsPath.toWindowsPath(WindowsPath.java:375)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:382)
	at sun.nio.fs.WindowsPath.relativize(WindowsPath.java:44)
	at scala.meta.internal.pc.SemanticdbTextDocumentProvider.$anonfun$textDocument$2(SemanticdbTextDocumentProvider.scala:38)
	at scala.Option.map(Option.scala:230)
	at scala.meta.internal.pc.SemanticdbTextDocumentProvider.textDocument(SemanticdbTextDocumentProvider.scala:37)

**Comment by tgodzik** [comment] 2021-02-22 13:22
I think that exception is fixed in the current master, but it should not influence the results here.

Did the build import finish succesfully? Isn't there anything else in the logs?

**Comment by abzif** [comment] 2021-02-22 13:53
Import was successful and there are no other exceptions in metals.log
There are warnings like:

lut 22, 2021 2:41:21 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 31
lut 22, 2021 2:41:25 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 37

and INFO logs describing compiler call - they does not seem suspicious

**Comment by tgodzik** [comment] 2021-02-22 14:18
Those exceptions are usually thrown if the user cancelled a request that was taking too long, so it does not seem suspicious

If possible please attach the full metals.log output.

**Comment by abzif** [comment] 2021-02-22 15:15
Here is the log after fresh import and try to rename variable
[metals.log](https://github.com/scalameta/metals/files/6022887/metals.log)

**Comment by tgodzik** [comment] 2021-02-23 18:10
It doesn't look like there is any issue in the log, are you able to find all references to the problematic variables? I can imagine a behavior where we only rename local variables, but not others. Not sure how it can happen the other way around. Could you maybe remove `.metals` and `.bloop` directories and reimport the build?

**Comment by abzif** [comment] 2021-02-24 10:49
'Go to references' shows all references correctly (in local file or in other files)

I removed .metals and .bloop directories but it does not help

I also removed metals extension from VSCode, cleared some cache directories and reinstall metals again. It does not help either. I have no idea what's the problem in my environment.

I will check the functionality in the next version, for now it simply does not work for some unknown reasons.

**Comment by tgodzik** [comment] 2021-02-24 10:57
Weirdest thing is that `go to references` uses exactly the same mechanism as rename, so this should not really happen :thinking: 

Maybe it's some kind of setting in VS Code that is influencing this?

**Comment by abzif** [comment] 2021-02-24 11:07
VS code is freshly installed. I installed it to try metals scala support and did not changed any default settings :(

**Comment by abzif** [comment] 2021-02-28 21:29
Some more information:
I checked VS Code and metals on Ubuntu Linux. Renaming works without any problems!

So I guess the problem is specific only to Windows. After update to the newest version of metals 0.10 the problem still occurs

**Comment by tgodzik** [comment] 2021-03-01 16:57
@abzif I should have checked right away on windows, totally missed the ifnormation. The issue was due to URL encoding of `:`

Thanks a lot for the help!

**Closed** 2021-03-01 18:57 UTC
Labels: needs more information
