### ISSUE TITLE
Scala worksheet evaluation takes too much time and hangs

### ISSUE THREAD

**Issue by kumarn33** [scalameta/metals#1495] opened 2020-03-12 05:26 UTC
**Describe the bug**

I have created the following worksheet in vscode, on save the evaluation started but it would never end. The editor keeps showing a timer every time I save it. I have tried the same in Intellij and it ran as expected, so I think it must be some important bug.

// File: cassandra.worksheet.sc

 ```
 import com.datastax.oss.driver.api.core.CqlSession
 import com.datastax.oss.driver.api.core.cql.{ResultSet, Row, SimpleStatement}
 import com.datastax.oss.driver.api.querybuilder.QueryBuilder._
 import com.datastax.oss.driver.api.querybuilder.select.Select

// https://mvnrepository.com/artifact/com.datastax.oss/java-driver-core/4.5.0

val session: CqlSession = CqlSession.builder.build

val query: Select = selectFrom("system", "local").column("release_version")
val statement: SimpleStatement = query.build()

val rs: ResultSet = session.execute(statement)

val row: Row = rs.one()

row.getString("release_version")

```

**To Reproduce**

Create a new worksheet and copy-paste the contents as given in the code section above.

I have used the following library dependency in the build.sbt file

```
lazy val cassandraDependencies = Seq(
  "com.datastax.oss" % "java-driver-core" % "4.5.0",
  "com.datastax.oss" % "java-driver-query-builder" % "4.5.0"
)

```

**Expected behavior**

The worksheet should run and print the Cassandra release_version.

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.8.1
- VS Code plugin v 1.8.0

**Additional context**

metals.log is as follows

```

INFO  time: evaluated worksheet 'cassandra.worksheet.sc' in 12m16s
Exception in thread "Evaluating Worksheet cassandra.worksheet.sc" java.lang.NoSuchMethodError: com.typesafe.config.impl.ConfigImpl.newSimpleOrigin(Ljava/lang/String;)Lcom/typesafe/config/ConfigOrigin;
	at com.typesafe.config.ConfigOriginFactory.newSimple(ConfigOriginFactory.java:42)
	at com.datastax.oss.driver.internal.core.config.typesafe.TypesafeDriverConfig.<clinit>(TypesafeDriverConfig.java:45)
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultDriverConfigLoader.<init>(DefaultDriverConfigLoader.java:98)
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultDriverConfigLoader.<init>(DefaultDriverConfigLoader.java:85)
	at com.datastax.oss.driver.internal.core.config.typesafe.DefaultDriverConfigLoader.<init>(DefaultDriverConfigLoader.java:73)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.defaultConfigLoader(SessionBuilder.java:125)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildIfNull(SessionBuilder.java:744)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:620)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:598)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:612)
	at repl.Session$App.<init>(cassandra.worksheet.sc:20)
	at repl.Session$.app(cassandra.worksheet.sc:3)
	at mdoc.internal.document.DocumentBuilder$$doc$.$anonfun$build$2(DocumentBuilder.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withErr(Console.scala:196)
	at mdoc.internal.document.DocumentBuilder$$doc$.$anonfun$build$1(DocumentBuilder.scala:82)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at scala.Console$.withOut(Console.scala:167)
	at mdoc.internal.document.DocumentBuilder$$doc$.build(DocumentBuilder.scala:81)
	at mdoc.internal.markdown.MarkdownCompiler$.buildDocument(MarkdownCompiler.scala:53)
	at mdoc.internal.worksheets.WorksheetProvider.evaluateWorksheet(WorksheetProvider.scala:44)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:47)
	at mdoc.internal.worksheets.Mdoc.evaluateWorksheet(Mdoc.scala:18)
	at scala.meta.internal.worksheets.WorksheetProvider.scala$meta$internal$worksheets$WorksheetProvider$$evaluateWorksheet(WorksheetProvider.scala:230)
	at scala.meta.internal.worksheets.WorksheetProvider$$anon$1.run(WorksheetProvider.scala:148)

```

**Search terms**
scala worksheet hangs on vscode
<img width="744" alt="Screenshot 2020-03-12 at 10 40 55 AM" src="https://user-images.githubusercontent.com/958936/76490070-16bf0480-6450-11ea-9a55-52cd6f9b1df1.png">

**Comment by olafurpg** [comment] 2020-03-12 09:38
Thank you for reporting! This looks like a duplicate of #1462, could you check if it's related?

**Comment by kumarn33** [comment] 2020-03-12 10:11
@olafurpg  They look similar from the UI, but the errors thrown are different here we have a java.lang.NoSuchMethodError, in #1462 the error is java.lang.IncompatibleClassChangeError. So I think both are different bugs. I would like to help to resolve this but I am a totally new to scala and very little expertise in Java :-(

**Comment by olafurpg** [comment] 2020-03-12 11:04
It looks like we have three related issues, the original ticket with a suggested fix is here https://github.com/scalameta/metals/issues/1456 Closing this ticket as a duplicate.

**Closed by olafurpg** 2020-03-12 11:04 UTC
