### ISSUE TITLE
Bad `run|debug` positioning

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#1326] opened 2020-01-18 22:25 UTC
**Describe the bug**
The `run|debug` option is moving to weird positions and not just above the `App` entry point.
See screenshot.

**To Reproduce**
1. Use the following code:
```scala
trait Foo  {
  val a = 1 * 1
  val b = 1
  val c = 1     * 1
}

object Lab0 extends App 
```
The spaces are very (weirdly) important for the bug. 
2. Make sure that the file name will be `Lab0.scala`

**Expected behavior**
The `run|debug` should appear only above the entry point.

**Screenshots**
![image](https://user-images.githubusercontent.com/8167952/72671357-9385c180-3a51-11ea-9584-6553d94c3c63.png)

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.8.0

**Additional context**
None

**Comment by olafurpg** [comment] 2020-01-18 23:30
Thank you for reporting! I'm unable to reproduce on my mac

<img width="264" alt="Screenshot 2020-01-18 at 23 29 32" src="https://user-images.githubusercontent.com/1408093/72671960-684ba400-3a4a-11ea-883e-fef3579af05c.png">

Could this related to Windows? 🤔

**Comment by soronpo** [comment] 2020-01-19 00:27
Maybe. Maybe it's even a bug in VSCode itself. I'll try on my Ubuntu system tomorrow and report back.

**Comment by soronpo** [comment] 2020-01-19 00:37
Damn. I'm sorry to report that this procedure is not enough to reproduce the problem. I've reimported the build and the problem disappeared and unfortunately couldn't bring it back.
You can close this ticket if you want.

**Comment by tgodzik** [comment] 2020-01-20 10:13
Let's close it until we have a reproduction. I was trying to break the lenses different way, but was also unable to.

**Closed by tgodzik** 2020-01-20 10:13 UTC
