### ISSUE TITLE
High CPU usage on OpenJDK 11 (only)

### ISSUE THREAD

**Issue by voidcontext** [scalameta/metals#1891] opened 2020-07-03 14:23 UTC
**Describe the bug**
When using metals with OpenJDK 11, metals becomes very slow and it's CPU usage is very high after opening a large project (e.g. http4s). There's no need to do anything, it is possible to trigger this behaviour just by opening a file from the project and leave the editor open (emacs in my case), the CPU consumption will remain high and constant even after 20-30mins. With the same setup switching back to OpenJDK 8 (and reinstall coursier, metals) solves the problem.

**To Reproduce**
1. Install metals using OpenJDK 11
2. Open a file from a large project (e.g. http4s)
3. Leave the editor open

**Expected behavior**
CPU consumption should go back to normal after the initial index + build cycle.

**Screenshots**
N/A

**Installation:**
- Operating system: macOS
- Editor: Emacs
- Metals version: 0.9.0+199-1e6cda24-SNAPSHOT, v0.9.1, 0.9.1+6-38226259-SNAPSHOT
- JDK: openjdk version "11.0.1" 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

**Additional context**
Metals's been built via a custom nix derivation using coursier (can provide details if necessary)

**Search terms**
OpenJDK / Java 11, high CPU usage / consumption

**Comment by tgodzik** [comment] 2020-07-06 10:03
Thanks for reporting! This is most likely a bug in the JVM, which causes the file walking to go recursive in case of some corrupted jars. Could you try with a newer version? For example `11.0.7` ?

**Comment by tgodzik** [comment] 2020-07-13 13:41
Closing this since I am sure this is an issue caused by an older JDK version.

**Closed by tgodzik** 2020-07-13 13:41 UTC
Labels: needs more information

**Comment by jodersky** [comment] 2020-12-24 02:01
I regularly run into a similar issue when working with projects using Scala 3.0.0-M2 (but the behavior has been observed for a much longer timer, since around dotty 0.27). Seemingly at random, metals will peg all available CPUs at 100%, and the only remedy is to `kill -9` the java process.

I know that this report needs more info, but I'm putting it our here in case anyone else has similar issues

**Comment by tgodzik** [comment] 2020-12-28 10:26
@jodersky I think the issue is connected to the semanticdb flag. It seems when it's enabled Dotty will sometimes use way too much memory and just end up stuck in GC. I haven't been able to work on that yet, but most likely we need to fix it in Dotty itself. Bumping RAM for Bloop should help, but really only as a half measure.

**Comment by voidcontext** [comment] 2021-01-04 10:52
Sorry, I totally forgot about reporting back, but the original issue was solved by upgrading Java 11 to a newer patch version. 

Athough I am also experiencing this performance issue with Scala 3 (only), so it might worth to track this separately.
