### ISSUE TITLE
Bad positions (goto definition) for ammonite scripts

### ISSUE THREAD

**Issue by soronpo** [scalameta/metals#2432] opened 2021-01-24 22:19 UTC
**Describe the bug**

The goto definition goes to wrong position in ammonite scripts.

**To Reproduce**

1. Use the following script:
```scala
// scala 2.13.4
import $ivy.`io.github.dfianthdl:dfiant_2.13:0.1.0`
import DFiant._

trait Foo extends DFDesign
```
2. Try to go to definition of `DFDesign`
3. Notice that the position is strangely at the top of the file.

**Expected behavior**

Positions in Goto Defitions should be equivalent to regular Scala code.

**Installation:**

- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: v0.9.10

**Search terms**

ammonite, positions

**Comment by ckipp01** [comment] 2021-01-25 07:42
Thanks for the report @soronpo. I'm able to reproduce this, although the reproduction is flaky as in sometimes it works fine, and sometimes it doesn't. For example, the first time I tried I saw your behavior, and the definition request looked like so:

```
[Trace - 08:37:29 AM] Sending response 'textDocument/definition - (9)'. Processing request took 2380ms
Result: [
  {
    "uri": "file:///Users/ckipp/Documents/scratch-workspace/.metals/readonly/DFiant/DFDesign.scala",
    "range": {
      "start": {
        "line": 0,
        "character": 0
      },
      "end": {
        "line": 0,
        "character": 0
      }
    }
  }
]
```
The second time was the same thing, and then the third time I correctly got:

```
[Trace - 08:37:57 AM] Sending response 'textDocument/definition - (13)'. Processing request took 164ms
Result: [
  {
    "uri": "file:///Users/ckipp/Documents/scratch-workspace/.metals/readonly/DFiant/DFDesign.scala",
    "range": {
      "start": {
        "line": 33,
        "character": 15
      },
      "end": {
        "line": 33,
        "character": 23
      }
    }
  }
]
```

So I have no idea why this would respond differently the third time without really doing a deep dive about what's going on.

**Comment by megri** [comment] 2021-02-24 14:58
Possibly related to #2338?

**Comment by tgodzik** [comment] 2021-02-24 15:00
> Possibly related to #2338?

That one is more related to flaky incremental compilation and this one seems to have something to do with the source file wrongly parsed I think.

**Comment by tgodzik** [comment] 2021-08-19 18:18
I cannot reproduce this anymore, it seems that maybe this was fixed by some of the recent changes? Let's reopen if an issue pops up again.

**Closed by tgodzik** 2021-08-19 18:18 UTC
Labels: bug, ammonite
