### ISSUE TITLE
Hover signature shows fully qualified name for symbol in scope

### ISSUE THREAD

**Issue by olafurpg** [scalameta/metals#612] opened 2019-04-02 10:29 UTC
<img width="706" alt="Screenshot 2019-04-02 at 12 27 52" src="https://user-images.githubusercontent.com/1408093/55395883-d5855b80-5542-11e9-8df9-b978140feec3.png">

I expected the result type to be formatted as `Range.Inclusive` instead of `scala.collection.immutable.Range.Inclusive`. I suspect the reason is that we're not picking up the `scala.Range` type alias.

**Comment by gabro** [comment] 2019-04-07 17:44
I spent a few minutes on this and I think the issue is that `Inclusive` is owned by a val-forwarded symbol, but it's not one itself, so it doesn't get dealiased.

I tried to meddle with the `shortType` method a bit, but I didn't get anywhere yet.

**Comment by olafurpg** [comment] 2019-04-15 07:44
I believe the fix for this issue is to customize `lookupSymbol` inside `ShortenedNames` to handle val-forwarders

**Comment by tgodzik** [comment] 2019-06-14 12:29
Won't fix - from an offline discussion with Olaf this issue is not worth keeping open

**Closed** 2019-06-14 12:29 UTC
