### ISSUE TITLE
CompletionException with snapshot versions with non-escaped symbols

### ISSUE THREAD

**Issue by narma** [scalameta/metals#4498] opened 2022-10-07 11:11 UTC
### Describe the bug

1. Open project with zio snapshot version
2. Type `ZIO.succeed` or any other method
3. Go to Definition (it works)
4. Go to definition inside ZIO class doesn't work:
```
[Error - 1:59:32 PM] Request textDocument/documentSymbol failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.nio.file.NoSuchFileException: /Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2+80-80cc429a-SNAPSHOT/zio_3-2.0.2+80-80cc429a-SNAPSHOT-sources.jar
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.file.NoSuchFileException: /Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2+80-80cc429a-SNAPSHOT/zio_3-2.0.2+80-80cc429a-SNAPSHOT-sources.jar
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:166)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:106)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:339)
	at java.base/java.nio.file.FileSystems.newFileSystem(FileSystems.java:288)
	at scala.meta.internal.io.PlatformFileIO$.newFileSystem(PlatformFileIO.scala:104)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionURIMtags.toAbsolutePath(MtagsEnrichments.scala:112)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:139)
	at scala.meta.internal.mtags.MtagsEnrichments$XtensionStringMtags.toAbsolutePath(MtagsEnrichments.scala:137)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:609)
	at scala.meta.internal.metals.MetalsEnrichments$XtensionString.toAbsolutePath(MetalsEnrichments.scala:606)
	at scala.meta.internal.metals.MetalsLanguageServer.$anonfun$documentSymbol$1(MetalsLanguageServer.scala:1545)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$apply$2(CancelTokens.scala:26)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
	... 3 more
```

### Expected behavior

4. Go to definition works

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

### Extra context or search terms

File 
`/Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2+80-80cc429a-SNAPSHOT/zio_3-2.0.2+80-80cc429a-SNAPSHOT-sources.jar` doesn't exist
But `/Users/alzo/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/dev/zio/zio_3/2.0.2%2B80-80cc429a-SNAPSHOT/zio_3-2.0.2%2B80-80cc429a-SNAPSHOT-sources.jar` is present on filesystem

Difference is `+` replaced by `%2B`.

**Comment by tgodzik** [comment] 2022-10-07 16:46
Thanks for reporting! Looks like we are not correctly escaping some of the non alphanumeric characters.

**Comment by tgodzik** [comment] 2022-10-12 17:20
Duplicate of https://github.com/scalameta/metals/issues/4357

**Closed by tgodzik** 2022-10-12 17:20 UTC
