### ISSUE TITLE
lsp-ui-doc Displays Raw Markdown in Specific Cases

### ISSUE THREAD

**Issue by rbugajewski** [scalameta/metals#1489] opened 2020-03-10 13:24 UTC
In specific cases Markdown doesn’t get rendered in `lsp-ui-doc`.

**To Reproduce**
1. Set up Metals as described in the documentation
2. Create a new [Play framework](https://www.playframework.com) project
3. Go to `HomeController.scala` and hover over different code elements

**Expected behavior**
Markdown should always be rendered in `lsp-ui-doc`.

**Screenshots**

This looks great:
<img width="901" alt="Screen Shot 2020-03-10 at 02 16 10 PM" src="https://user-images.githubusercontent.com/24480/76316228-87dcab80-62da-11ea-8dd4-979448580d71.png">
In this case raw Markdown gets displayed, instead of getting rendered:
<img width="901" alt="Screen Shot 2020-03-10 at 02 16 19 PM" src="https://user-images.githubusercontent.com/24480/76316263-96c35e00-62da-11ea-86f3-f84c35e10a2b.png">

**Installation:**
- Operating system: macOS Catalina
- Editor: Emacs
- Metals version: v0.8.1

**Comment by tgodzik** [comment] 2020-03-27 19:25
Thanks for reporting! Could you check it if one of the newer snapshots?  For example: `0.8.3+65-757f7c93-SNAPSHOT` ?

We recently changed the way we display the markdown, so as a side effect it might have been fixed.

**Comment by tgodzik** [comment] 2020-03-30 11:19
I checked in Visual Studio Code and both seem to be rendered correctly. 

@rbugajewski Could you check with snapshot versions? It either has something to do with the depracted lsp elements or is explicitely related to the emacs client.

**Comment by tgodzik** [comment] 2020-03-30 12:18
Thanks to checking the play project I was able to find some bugs with hovers and fixed them here:
https://github.com/scalameta/metals/pull/1568

Thanks!

**Comment by ckipp01** [comment] 2020-04-02 09:00
I just looked a bit more into this as well since I've seen this behavior in the past with some of the vim clients. This situation is a bit bizarre since I looked at the lsp trace for the exact code you're showing both in the latest snapshot and the last stable release. Both are exactly the same. Also, both `textDocument/hover` responses are the exact same as well in this situation between doing a hover on `Action` and doing on on `Ok`. You can see this below.

```
[Trace - 10:55:05 AM] Sending response 'textDocument/hover - (10)'. Processing request took 32ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\ndef apply[C](content: C)(implicit writeable: Writeable[C]): Result\n```\nSet the result\u0027s content.\n\n\n**Parameters**\n- `content`: The content to send."
  },
  "range": {
    "start": {
      "line": 21,
      "character": 4
    },
    "end": {
      "line": 21,
      "character": 26
    }
  }
}

[Trace - 10:56:19 AM] Sending response 'textDocument/hover - (13)'. Processing request took 28ms
Result: {
  "contents": {
    "kind": "markdown",
    "value": "```scala\nfinal def apply(block: Request[AnyContent] \u003d\u003e Result): Action[AnyContent]\n```\nConstructs an `Action` with default content.\n\nFor example:\n\n```\nval echo \u003d Action { request \u003d\u003e\n  Ok(\"Got request [\" + request + \"]\")\n}\n```\n**Parameters**\n- `block`: the action code\n\n**Returns:** an action"
  },
  "range": {
    "start": {
      "line": 20,
      "character": 16
    },
    "end": {
      "line": 22,
      "character": 3
    }
  }
}
```

**Comment by ckipp01** [comment] 2020-05-14 06:55
I'm going to go ahead and close this. Between the time this was reported and now, there was some work done on the way we return markdown. Also, some of this is determined by what the client supports, and what the set for `ClientCapabilities`. Looking at this again, it does seem pretty specific to the client. We haven't had any other reports of this, and the times I referenced where I saw this in Vim was due to misconfiguration on the Vim side. If you are able to reproduce this in a way where you feel like it may be an issues on Metals end, feel free to comment back in here.

**Closed by ckipp01** 2020-05-14 06:55 UTC
Labels: missing-reproduction
