### ISSUE TITLE
Incorrect goto definition

### ISSUE THREAD

**Issue by ckipp01** [scalameta/metals#4255] opened 2022-08-12 12:09 UTC
### Describe the bug

When doing a goto definition on `Indexer` here:
https://github.com/scalameta/metals/blob/ab314f8f23de51b84c4415aa0f8f355c893f5502/metals/src/main/scala/scala/meta/internal/metals/MetalsLanguageServer.scala#L2496

This brings me to the companion object here:

https://github.com/scalameta/metals/blob/ab314f8f23de51b84c4415aa0f8f355c893f5502/metals/src/main/scala/scala/meta/internal/metals/Indexer.scala#L610

Even though in this scenario you'd expect and want it to bring you to the actual case class here:

https://github.com/scalameta/metals/blob/ab314f8f23de51b84c4415aa0f8f355c893f5502/metals/src/main/scala/scala/meta/internal/metals/Indexer.scala#L46
### Expected behavior

I'd expect to navigate to the case class.

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

0.11.8+11-bfe6c2ca-SNAPSHOT

**Comment by tgodzik** [comment] 2022-08-12 12:55
Thanks for reporting! This seems another one that I ignored :sweat_smile: and it actually popped up a couple of times. Let me check it out. Keep those issues coming! :D

**Comment by tgodzik** [comment] 2022-08-24 14:23
Duplicate of https://github.com/scalameta/metals/issues/1809

**Closed by tgodzik** 2022-08-24 14:23 UTC
Labels: improvement, semanticdb
