### ISSUE TITLE
type information missing in certain cases

### ISSUE THREAD

**Issue by andyczerwonka** [scalameta/metals#5061] opened 2023-03-17 14:05 UTC
I have a situation where most of the time, I do get type information when I hover over part of the code. In this one case, I don't see it. You will notice in the attached video, that I am getting types when hovering for everything except the values within the for comprehension.

![type-information-error](https://user-images.githubusercontent.com/138898/225936500-e961c4a9-1994-4a03-941f-daecf0a3f567.gif)

I'm not sure how to debug this case.

### Expected behavior

I would expect to see types show up when I hover over the values in the for comprehension.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.11

**Comment by tgodzik** [comment] 2023-03-17 17:40
Thanks for reporting! Any chance you could create a small reproduction? This is usually caused by the compiler not returning the correct information, might require some upstream fixes or workaround in metals.

What is the Scala version you are using? Any specific library? Maybe it also fails on an example project using that library?

**Comment by andyczerwonka** [comment] 2023-03-17 20:42
> Thanks for reporting! Any chance you could create a small reproduction? This is usually caused by the compiler not returning the correct information, might require some upstream fixes or workaround in metals.
> 
> What is the Scala version you are using? Any specific library? Maybe it also fails on an example project using that library?

Yeah, I was trying to reproduce, but I can't seem to. Is seems specific to a project using the Typelevel stack, in this case Cats Effect 3. We also have FS2 in the picture, so fairly heavy use of typeclasses and HKT's.

**Comment by armanbilge** [comment] 2023-03-17 21:07
Are you using the better-monad-for plugin with Scala 2? Maybe that is related.
- https://github.com/oleg-py/better-monadic-for

**Comment by andyczerwonka** [comment] 2023-03-17 21:10
Yes we are, and I thought that may be the case too, but I have type information in other places where it is being injected. 🤷🏻

**Comment by tgodzik** [comment] 2023-03-27 15:35
I realised that if you turn on semantic highlighting you might actually see where things start to go wrong. It will color everything in that place in one color (it uses the same mechanisms as hover). Not sure, but maybe it could help us out to pinpoint the issue?

**Comment by andyczerwonka** [comment] 2023-03-27 15:46
@tgodzik Here it is with semantic highlighting turned on. It's not obvious to me, although color did change significantly.

![image](https://user-images.githubusercontent.com/138898/227993571-502ac228-c1f8-4ac1-aea0-eb740f1d39be.png)

**Comment by tgodzik** [comment] 2023-03-28 10:22
Looks like it all starts with `scope`, which should probably be not shown as a variable. There are issues with that `scope` so the for comprehensions break as well :thinking: 

I wonder if we could create something with a similar structure.

**Comment by andyczerwonka** [comment] 2023-03-28 13:47
@tgodzik The `scope` case class is really simple.

```scala
case class RequestScope(
    user: UUID,
    principalId: UUID,
    principalType: String,
    uri: Uri,
    service: Option[String],
    bearerToken: Option[BearerToken] = None
)
```

**Comment by tgodzik** [comment] 2023-03-28 14:32
Did you maybe see any exceptions in `.metals/metals.log` ? I think I haven't asked about that and we should see something breaking there :thinking:

**Comment by andyczerwonka** [comment] 2023-03-28 15:14
I definitely tried that already, no exceptions in the logs.

**Comment by andyczerwonka** [comment] 2023-03-28 15:16
I **think** it's related to the `scope.toTypedRequestScope` extension method.

```scala
  implicit class requestScopeOps(val requestScope: RequestScope) extends AnyVal {
    def toTypedRequestScope: Validated[ServiceError, TypedRequestScope] =
      TypedRequestScope.fromRequestScope(requestScope)
  }
```

**Comment by tgodzik** [comment] 2023-03-28 16:09
I think we might need to report some more data on out side when hover info can't be found.

**Comment by samspills** [comment] 2023-04-03 01:30
I think I'm experiencing the same issue with emacs+metals when working with [`DispatcherSpec.scala` in cats-effects](https://github.com/typelevel/cats-effect/blob/0cc2d68bf607e9b6c97a93e5e9b826a05a482649/tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala). Each spec refers to a `dispatcher` resource that is passed in, and it seems that type info is available in a spec _before_ any reference to `disaptcher` and unavailable after the reference to dispatcher. 

For example: in [this test](https://github.com/typelevel/cats-effect/blob/series/3.x/tests/shared/src/test/scala/cats/effect/std/DispatcherSpec.scala#L68-L86) specifically, I get type info for `results` and `gate` and then nothing else. 

There are no exceptions in metals.log that I can see.

**Comment by kasiaMarek** [comment] 2023-04-07 08:19
A small reproduction of the issue:
```
// file: package.scala
package basepkg //in my case:  scala.meta

package object internal {
  type Intt = Int
}
```
```
// file: M.scala
package basepkg.internal //in my case:  scala.meta.internal

object M {
  val thisIsFine : Int = 3
  val hoverError : Intt = 3
}
```
The filename `package.scala` is crucial to getting the issue.

The type is not resolved in the typed tree properly.
Data from the report:
```
is error: false
symbol: value hoverError
tpe: <notype>

tree:
private[this] val <hoverError: error>: <error> = 3

full tree:
package scala.meta.internal {
  object M extends scala.AnyRef {
    def <init>(): scala.meta.internal.M.type = {
      M.super.<init>();
      ()
    };
    private[this] val thisIsFine: Int = 3;
    <stable> <accessor> def thisIsFine: Int = M.this.thisIsFine;
    private[this] val <hoverError: error>: <error> = 3;
    <stable> <accessor> def <hoverError: error>: <error> = M.this.<hoverError: error>
  }
}
```

**Comment by kasiaMarek** [comment] 2023-12-01 09:46
Closing as a duplicate: https://github.com/scalameta/metals/issues/4495. If that's not it @andyczerwonka, please reopen.

**Closed by kasiaMarek** 2023-12-01 09:46 UTC
Labels: bug, presentation-compiler, reporting
