### ISSUE TITLE
[Scala3] failures to look up definitions from Java dependency

### ISSUE THREAD

**Issue by unthingable** [scalameta/metals#4328] opened 2022-09-01 09:02 UTC
## Problem 
Definition lookup on external dependencies can suddenly stop working.

## Steps to reproduce

1. Checkout https://github.com/unthingable/monster-jam/tree/metals-definition-bug, import build
2. Navigate to https://github.com/unthingable/monster-jam/blob/e8570ac9c4268515181c15d40de2eb0579595978/src/main/scala/com/github/unthingable/MonsterJamExtension.scala#L34 (MonsterJamExtension.scala) and attempt to go to definition of `Transport` (imported via `import com.bitwig.extension.controller.api.*` on line 4)

## Symptoms and observations

* Definition lookup has been observed to work initially and then stop, with no changes to dependencies or setup
* It is still possible to find the class via symbol lookup in the workspace (`#Transport`), it successfully opens the source file

## Env
* Visual Studio Code 1.70.2
* Bloop v1.5.3.
* Metals Java: 17.0.2 from Eclipse Adoptium located at /Users/xxx/.sdkman/candidates/java/17.0.2-tem
* Metals Server version: 0.11.8

**Comment by tgodzik** [comment] 2022-09-01 10:24
Thanks for reporting and the reproduction!

**Comment by dos65** [comment] 2022-09-01 13:17
The issue is in qdox parser - `Transport.java` contains `void record();` line that breaks parser.

https://github.com/paul-hammant/qdox/issues/108

**Comment by dos65** [comment] 2022-09-14 14:11
Fixed by #4344

**Closed by dos65** 2022-09-14 14:11 UTC
Labels: bug, navigation
