### ISSUE TITLE
Error: Client is not running and can't be stopped

### ISSUE THREAD

**Issue by mbovel** [scalameta/metals#6888] opened 2024-10-25 16:41 UTC
### Describe the bug

Metals can't start when opening [dotty](https://github.com/scala/scala3).

<img src="https://github.com/user-attachments/assets/4a941e83-a6d5-4a00-b3aa-9cdc6a524626" width="500px" />

<img src="https://github.com/user-attachments/assets/24821366-af70-4d4e-b3d3-0b30b8ebc25b" width="500px" />

<details>

<summary><h4>Metals Output</h4></summary>

```
Metals version: 1.4.0
Using coursier located at /usr/local/bin/coursier
Checking Java in JAVA_HOME, which points to /Users/mbovel/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java17-darwin-amd64-22.3.3.tar.gz/graalvm-ce-java17-22.3.3/Contents/Home
	openjdk version "17.0.8" 2023-07-18
	OpenJDK Runtime Environment GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22)
	OpenJDK 64-Bit Server VM GraalVM CE 22.3.3 (build 17.0.8+7-jvmci-22.3-b22, mixed mode, sharing)
Using Java Home: /Users/mbovel/Library/Caches/Coursier/arc/https/github.com/graalvm/graalvm-ce-builds/releases/download/vm-22.3.3/graalvm-ce-java17-darwin-amd64-22.3.3.tar.gz/graalvm-ce-java17-22.3.3/Contents/Home
[Error - 6:36:12 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:12 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:12 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:12 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:12 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:12 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
	at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:14 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:36:14 PM] Connection to server got closed. Server will restart.
true
[Error - 6:36:14 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:17 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:17 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:19 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:36:19 PM] Connection to server got closed. Server will restart.
true
[Error - 6:36:19 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Could not launch Metals Language Server:
Pending response rejected since connection got disposed
Release notes was not shown: not showing release notes since they've already been seen for your current version
[Error - 6:36:20 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:20 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:20 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:20 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:20 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:20 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:23 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:36:23 PM] Connection to server got closed. Server will restart.
true
[Error - 6:36:23 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:23 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:25 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:25 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:25 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:25 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:25 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:25 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:27 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:36:27 PM] Connection to server got closed. Server will restart.
true
[Error - 6:36:27 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:27 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:28 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:28 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:28 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:28 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:28 PM] Client Metals: connection to server is erroring. Shutting down server.
[Error - 6:36:28 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: startFailed
    at LanguageClient.shutdown (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:914:19)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:885:21)
    at LanguageClient.stop (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/node/main.js:150:22)
    at LanguageClient.handleConnectionError (/Users/mbovel/.vscode/extensions/scalameta.metals-1.40.0/node_modules/vscode-languageclient/lib/common/client.js:1146:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[Error - 6:36:30 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:30 PM] The Metals server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 6:36:30 PM] Metals client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 6:36:30 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

</details>

[metals.log](https://github.com/user-attachments/files/17525162/metals.log)

### Expected behavior

No crash.

In case of crash: less notifications. It's nice to restart the server automatically, but it's scary to see 3*5 + 1 notifications popping out as it's the case now.

### Operating system

None

### Editor/Extension

None

### Version of Metals

v1.4.0

**Comment by tgodzik** [comment] 2024-10-25 17:14
Thanks for reporting. Did you change any JVM options recently? I wonder if this doesn't work with Graalvm :thinking:

**Comment by tgodzik** [comment] 2024-10-25 17:16
Does it work if you change the default JVM options for metals?

That is `metals.serverProperties` changed to maybe just `-Xmx2g`

**Comment by tgodzik** [comment] 2024-10-25 17:22
Looks like it works for me with GraalVM, so that's not the issue.

**Comment by tgodzik** [comment] 2024-10-25 17:23
Does it work in any other repositories actually? Or is it just Dotty?

**Comment by mbovel** [comment] 2024-10-25 21:06
> Did you change any JVM options recently?
I don't think so no, not since Tuesday where my setup was working.

> I wonder if this doesn't work with Graalvm 🤔

Ah, I tried switching to OpenJDK (`coursier java --jvm adoptium:17 --setup`) and it now works! 🤩

Strange, it was working with GraalVM a few days ago and I don't see what could have changed in between. Anyway, thanks a lot for the quick reply, that solved my problem!

**Comment by mbovel** [comment] 2024-10-25 21:10
> Does it work in any other repositories actually? Or is it just Dotty?

It was actually also not working on other repositories.

**Comment by tgodzik** [comment] 2024-10-25 22:54
I think I know what's going on, I need to turn off zgc for graalvm. I was hoping to use it to reduce memory consumption, but it seems it doesn't work for graal

**Comment by tgodzik** [comment] 2024-10-27 21:38
I think the issue might be that something is being printed to standard output which we use for communicating with the server. Are you able to run `java -Xmx2G -XX:+UseZGC -XX:ZUncommitDelay=30 -XX:ZCollectionInterval=5 -XX:+IgnoreUnrecognizedVMOptions  -version` or any kind of jar? We might be able to see what kind of warnings is being printed with the defaults

**Comment by tgodzik** [comment] 2024-10-27 21:44
Och, I think I managed to reproduce:
`[0.011s][warning][gc,jvmci] Setting EnableJVMCI to false as selected GC does not support JVMCI: z gc`
I need to figure out how to turn off that warning.

**Comment by mbovel** [comment] 2024-10-28 13:46
Ah, might be it then!
I am not sure, but this warning might be critical as JVMCI is what Graal uses to install itself as the C2 compiler. See https://github.com/oracle/graal/issues/2149#issuecomment-2198544644.
Maybe it would be best to not use ZGC for Graal?

**Comment by tgodzik** [comment] 2024-10-28 14:38
That's the plan! Are you able to check on the prerelease version? I just merged https://github.com/scalameta/metals-vscode/pull/1548

**Comment by tgodzik** [comment] 2024-10-29 11:15
@mbovel any chance you could check out the latest prerelease?

**Comment by mbovel** [comment] 2024-10-29 17:53
Yay, it works again! Thanks!

<img width="798" alt="image" src="https://github.com/user-attachments/assets/9ec00443-0156-4eb8-b5be-b57eb9e15689">

**Closed** 2024-10-29 22:34 UTC

**Comment by Slangsinger** [comment] 2025-05-28 06:23
I have encounted the same problems with Metals v1.5.3, the error log is as the following:
```
Metals version: 1.5.3
Using coursier located at /root/.metals/cs
Searching for Java on PATH. Found java executable under /usr/bin/java that resolves to /usr/lib/jvm/java-17-openjdk-amd64/bin/java
Using Java Home: /usr/lib/jvm/java-17-openjdk-amd64
[Error - 2:01:47 PM] Client Metals: connection to server is erroring.
Header must provide a Content-Length property.
{"[0.033s][error][gc] failed to uncommit memory (not supported)\ncontent-length":"182"}
Shutting down server.
[Error - 2:01:47 PM] Stopping server failed
Error: Client is not running and can't be stopped. It's current state is: starting
	at LanguageClient.shutdown (/root/.vscode-server/extensions/scalameta.metals-1.51.2/node_modules/vscode-languageclient/lib/common/client.js:964:19)
	at LanguageClient.stop (/root/.vscode-server/extensions/scalameta.metals-1.51.2/node_modules/vscode-languageclient/lib/common/client.js:935:21)
	at LanguageClient.stop (/root/.vscode-server/extensions/scalameta.metals-1.51.2/node_modules/vscode-languageclient/lib/node/main.js:150:22)
	at LanguageClient.handleConnectionError (/root/.vscode-server/extensions/scalameta.metals-1.51.2/node_modules/vscode-languageclient/lib/common/client.js:1196:18)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
And `java -Xmx2G -XX:+UseZGC -XX:ZUncommitDelay=30 -XX:ZCollectionInterval=5 -XX:+IgnoreUnrecognizedVMOptions  -version`
returns:
```
[0.024s][error][gc] Failed to uncommit memory (Not supported)
openjdk version "17.0.15" 2025-04-15
OpenJDK Runtime Environment (build 17.0.15+6-Ubuntu-0ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.15+6-Ubuntu-0ubuntu122.04, mixed mode, sharing)
```
Can you help check the problem? Thanks in advance
