### ISSUE TITLE
Stuck on Starting Metals server

### ISSUE THREAD

**Issue by dev-lluo** [scalameta/metals#4205] opened 2022-07-30 17:05 UTC
### Describe the bug

Clicking on either button (New Scala Project/Start Metals) just pops up the same notification again.

### Expected behavior

new empty project

### Operating system

Other (WSL2)

### Version of Metals

0.11.7

### Extra context or search terms

2022.07.31 01:00:07 INFO  tracing is disabled for protocol LSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/admin/scalang/example/.metals/lsp.trace.json or /home/admin/.cache/metals/lsp.trace.json[0m
2022.07.31 01:00:07 INFO  logging to file /home/admin/scalang/example/.metals/metals.log[0m
2022.07.31 01:00:07 INFO  Started: Metals version 0.11.7 in workspace '/home/admin/scalang/example' for client Visual Studio Code 1.69.2.[0m
2022.07.31 01:00:08 INFO  time: initialize in 0.52s[0m
2022.07.31 01:00:08 WARN  Flyway upgrade recommended: H2 2.1.214 is newer than this version of Flyway and support has not been tested. The latest supported version of H2 is 2.1.210.[0m
2022.07.31 01:00:08 WARN  Build server is not auto-connectable.[0m
2022.07.31 01:00:08 WARN  no build tool detected in workspace '/home/admin/scalang/example'. The most common cause for this problem is that the editor was opened in the wrong working directory, for example if you use sbt then the workspace directory should contain build.sbt. [0m

**Comment by tanishiking** [comment] 2022-07-31 06:21
@dev-lluo hey, thanks for reporting!
Foes your project directory contains build.sbt? 
As the warning suggests, there should be a build file in the project root :)

**Comment by tgodzik** [comment] 2022-08-01 09:25
Alternatively if you want to start quickly working on Scala you can:
- create a single Ammonite Scala script (.sc), which should not require anything else.
- run `Create new Scala project` command and choose one of the recommended templates
- you can try to use https://scala-cli.virtuslab.org/ which we are trying to use to simplify the experience of getting started

**Comment by tgodzik** [comment] 2022-11-30 17:44
Closing this for now, since there is no reproducible issue

**Closed by tgodzik** 2022-11-30 17:44 UTC
