### ISSUE TITLE
Can't debug Scala code

### ISSUE THREAD

**Issue by francotiveron** [scalameta/metals#1497] opened 2020-03-13 01:10 UTC
**Question**
I have installed metals 0.81 in my Vs code (Windows 10); everything seems to work as expected, except debugging. I have looked in https://github.com/scalameta/metals/issues/1297 but this is about OSX I am on windows 10

**Screenshots**

![image](https://user-images.githubusercontent.com/8280970/76580181-20656c80-6523-11ea-9f9c-41e3b9884f93.png)

**Installation:**

- Operating system: Windows 10
- Editor: Visual Studio Code
- Metals version: v0.8.1

I don't even see the Debug with SCALA debugger, just the usual Debug button.

**Comment by olafurpg** [comment] 2020-03-13 07:20
Thank you for reporting! Are there “run” and “debug” buttons at the top of the object definition?

**Comment by francotiveron** [comment] 2020-03-13 07:26
yes they are there and they work

**Comment by olafurpg** [comment] 2020-03-13 09:32
Closing as a duplicate of https://github.com/scalameta/metals-vscode/issues/217 

The launch/debug interface in VS Code did not exist when we started working on debugging in Metals. There is an open PR to implement support for launch.json configuration here https://github.com/scalameta/metals/pull/1466

**Closed by olafurpg** 2020-03-13 09:32 UTC
Labels: question
