### ISSUE TITLE
Incorrect errors reported by Metals

### ISSUE THREAD

**Issue by robmwalsh** [scalameta/metals#4652] opened 2022-11-18 02:13 UTC
### Describe the bug

Metals sometimes reports "errors" that sbt doesn't. Note that this doesn't only happen with a project that compiles cleanly, but it's most obvious then.

(apologies for the pic, couldn't seem to get this in text form)
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/30517573/202593416-6b2aaafe-812a-497f-86fe-c109ac6d1044.png">

```
sbt:root> clean;compile
[success] Total time: 0 s, completed Nov 18, 2022, 12:04:15 PM
[info] compiling 1 Scala source to /home/rob/code/lsp/modules/plugin/target/scala-3.2.0/classes ...
[info] compiling 17 Scala sources to /home/rob/code/lsp/libs/zio-jsonrpc/js/target/scala-3.2.0/classes ...
[info] compiling 17 Scala sources to /home/rob/code/lsp/libs/zio-jsonrpc/jvm/target/scala-3.2.0/classes ...
[info] compiling 17 Scala sources to /home/rob/code/lsp/libs/zio-lsp/jvm/target/scala-3.2.0/classes ...
[info] compiling 17 Scala sources to /home/rob/code/lsp/libs/zio-lsp/js/target/scala-3.2.0/classes ...
[info] compiling 11 Scala sources to /home/rob/code/lsp/modules/server/target/scala-3.2.0/classes ...
[info] compiling 1 Scala source to /home/rob/code/lsp/modules/vscode/target/scala-3.2.0/classes ...
[success] Total time: 10 s, completed Nov 18, 2022, 12:04:24 PM
```

from metals.log
```
Nov 18, 2022 11:54:08 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 60407
2022.11.18 11:55:33 INFO  compiling ziolspjs (1 scala source)[0m
2022.11.18 11:55:33 INFO  time: compiled zioLspJS in 0.13s[0m
2022.11.18 11:55:34 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:36 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:37 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:38 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:38 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:40 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:41 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:41 INFO  compiling ziolspjs (1 scala source)[0m
2022.11.18 11:55:41 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/LspProtocol.scala[0m
2022.11.18 11:55:41 INFO  time: compiled zioLspJS in 0.3s[0m
2022.11.18 11:56:41 INFO  compiling ziolspjs (1 scala source)[0m
2022.11.18 11:56:41 INFO  time: compiled zioLspJS in 0.34s[0m
2022.11.18 11:57:22 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 11:57:22 INFO  time: compiled zioJsonRpcJS in 0.22s[0m
2022.11.18 11:57:50 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 11:57:50 INFO  time: compiled zioJsonRpcJS in 0.24s[0m
2022.11.18 11:57:57 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 11:57:57 INFO  time: compiled zioJsonRpcJS in 0.23s[0m
Nov 18, 2022 11:58:00 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 61079
2022.11.18 11:58:01 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 11:58:01 WARN  Could not load snapshot text for /home/rob/code/lsp/libs/zio-jsonrpc/shared/src/main/scala/sls/jsonrpc/JsonRpc.scala[0m
2022.11.18 11:58:01 INFO  time: compiled zioJsonRpcJS in 0.3s[0m
2022.11.18 11:59:55 INFO  compiling ziolspjs (3 scala sources)[0m
2022.11.18 11:59:56 INFO  time: compiled zioLspJS in 1.04s[0m
2022.11.18 12:00:36 WARN  Name doesn't match for JsonRpc at Range(15,44,15,48)[0m
2022.11.18 12:00:36 WARN  Name doesn't match for JsonRpc at Range(16,11,16,15)[0m
2022.11.18 12:00:37 INFO  compiling ziojsonrpcjs (17 scala sources)[0m
2022.11.18 12:00:38 INFO  time: compiled zioJsonRpcJS in 1.67s[0m
2022.11.18 12:00:38 INFO  compiling ziolspjs (17 scala sources)[0m
2022.11.18 12:00:40 INFO  time: compiled zioLspJS in 1.15s[0m
Nov 18, 2022 12:00:56 PM scala.meta.internal.metals.Docstrings indexSymbol
SEVERE: file:///home/rob/code/lsp/libs/zio-jsonrpc/shared/src/main/scala/sls/jsonrpc/JsonRpc.scala
java.nio.file.NoSuchFileException: /home/rob/code/lsp/libs/zio-jsonrpc/shared/src/main/scala/sls/jsonrpc/JsonRpc.scala
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:380)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:432)
	at java.base/java.nio.file.Files.readAllBytes(Files.java:3288)
	at scala.meta.internal.io.PlatformFileIO$.slurp(PlatformFileIO.scala:45)
	at scala.meta.internal.io.FileIO$.slurp(FileIO.scala:24)
	at scala.meta.internal.mtags.CommonMtagsEnrichments$XtensionAbsolutePath.toInput(CommonMtagsEnrichments.scala:529)
	at scala.meta.internal.metals.Docstrings.indexSymbolDefinition(Docstrings.scala:123)
	at scala.meta.internal.metals.Docstrings.indexSymbol(Docstrings.scala:107)
	at scala.meta.internal.metals.Docstrings.documentation(Docstrings.scala:44)
	at scala.meta.internal.metals.MetalsSymbolSearch.documentation(MetalsSymbolSearch.scala:42)
	at scala.meta.internal.mtags.MtagsEnrichments$.symbolDocumentation(MtagsEnrichments.scala:193)
	at scala.meta.internal.pc.HoverProvider$.$anonfun$1(HoverProvider.scala:106)
	at scala.collection.immutable.List.flatMap(List.scala:293)
	at scala.meta.internal.pc.HoverProvider$.hover(HoverProvider.scala:106)
	at scala.meta.internal.pc.ScalaPresentationCompiler.hover$$anonfun$1(ScalaPresentationCompiler.scala:266)
	at scala.meta.internal.pc.CompilerAccess.withSharedCompiler(CompilerAccess.scala:137)
	at scala.meta.internal.pc.CompilerAccess.withNonInterruptableCompiler$$anonfun$1(CompilerAccess.scala:125)
	at scala.meta.internal.pc.CompilerAccess.onCompilerJobQueue$$anonfun$1(CompilerAccess.scala:197)
	at scala.meta.internal.pc.CompilerJobQueue$Job.run(CompilerJobQueue.scala:152)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022.11.18 12:01:28 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:01:28 INFO  time: compiled zioJsonRpcJS in 0.14s[0m
2022.11.18 12:01:51 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:01:51 INFO  time: compiled zioJsonRpcJS in 0.15s[0m
2022.11.18 12:01:58 INFO  compiling ziojsonrpcjvm (16 scala sources)[0m
2022.11.18 12:02:00 INFO  time: compiled zioJsonRpcJVM in 1.33s[0m
2022.11.18 12:02:00 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:02:00 INFO  compiling ziolspjvm (16 scala sources)[0m
2022.11.18 12:02:00 INFO  time: compiled zioJsonRpcJS in 0.14s[0m
2022.11.18 12:02:08 INFO  compiling server (1 scala source)[0m
2022.11.18 12:02:08 INFO  time: compiled zioLspJVM in 7.98s[0m
2022.11.18 12:02:08 INFO  time: compiled server in 0.4s[0m
2022.11.18 12:02:08 INFO  compiling plugin (1 scala source)[0m
2022.11.18 12:02:08 INFO  compiling ziojsonrpcjvm (1 scala source)[0m
2022.11.18 12:02:08 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:02:08 INFO  time: compiled plugin in 0.17s[0m
2022.11.18 12:02:08 INFO  time: compiled zioJsonRpcJS in 0.19s[0m
2022.11.18 12:02:08 INFO  compiling ziolspjvm (1 scala source)[0m
2022.11.18 12:02:08 INFO  time: compiled zioJsonRpcJVM in 0.2s[0m
2022.11.18 12:02:08 INFO  time: compiled zioLspJVM in 0.19s[0m
2022.11.18 12:02:29 INFO  compiling server (1 scala source)[0m
2022.11.18 12:02:29 INFO  time: compiled server in 55ms[0m
2022.11.18 12:03:12 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:12 INFO  time: compiled zioJsonRpcJS in 0.16s[0m
2022.11.18 12:03:12 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:12 INFO  time: compiled zioJsonRpcJS in 0.14s[0m
2022.11.18 12:03:12 INFO  compiling plugin (1 scala source)[0m
2022.11.18 12:03:12 INFO  compiling ziojsonrpcjvm (1 scala source)[0m
2022.11.18 12:03:12 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:12 INFO  time: compiled plugin in 0.16s[0m
2022.11.18 12:03:12 INFO  time: compiled zioJsonRpcJS in 0.2s[0m
2022.11.18 12:03:12 INFO  compiling ziolspjvm (1 scala source)[0m
2022.11.18 12:03:12 INFO  time: compiled zioJsonRpcJVM in 0.21s[0m
2022.11.18 12:03:12 INFO  compiling server (1 scala source)[0m
2022.11.18 12:03:12 INFO  time: compiled zioLspJVM in 0.19s[0m
2022.11.18 12:03:12 INFO  time: compiled server in 0.14s[0m
2022.11.18 12:03:34 INFO  compiling ziojsonrpcjvm (1 scala source)[0m
2022.11.18 12:03:34 INFO  time: compiled zioJsonRpcJVM in 0.24s[0m
2022.11.18 12:03:34 INFO  compiling server (1 scala source)[0m
2022.11.18 12:03:34 INFO  time: compiled server in 55ms[0m
2022.11.18 12:03:34 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:34 INFO  time: compiled zioJsonRpcJS in 0.2s[0m
2022.11.18 12:03:37 INFO  compiling server (1 scala source)[0m
2022.11.18 12:03:37 INFO  time: compiled server in 62ms[0m
2022.11.18 12:03:37 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:37 INFO  time: compiled zioJsonRpcJS in 0.17s[0m
2022.11.18 12:03:37 INFO  compiling plugin (1 scala source)[0m
2022.11.18 12:03:37 INFO  compiling ziojsonrpcjvm (1 scala source)[0m
2022.11.18 12:03:37 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:03:37 INFO  time: compiled plugin in 0.13s[0m
2022.11.18 12:03:37 INFO  time: compiled zioJsonRpcJS in 0.17s[0m
2022.11.18 12:03:37 INFO  compiling ziolspjvm (1 scala source)[0m
2022.11.18 12:03:37 INFO  time: compiled zioJsonRpcJVM in 0.21s[0m
2022.11.18 12:03:37 INFO  compiling server (1 scala source)[0m
2022.11.18 12:03:37 INFO  time: compiled zioLspJVM in 0.19s[0m
2022.11.18 12:03:37 INFO  time: compiled server in 60ms[0m
2022.11.18 12:04:09 INFO  compiling server (1 scala source)[0m
2022.11.18 12:04:09 INFO  time: compiled server in 0.22s[0m
2022.11.18 12:04:15 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:04:15 INFO  time: compiled zioJsonRpcJS in 0.18s[0m
2022.11.18 12:04:15 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:04:15 INFO  time: compiled zioJsonRpcJS in 0.16s[0m
2022.11.18 12:04:15 INFO  compiling plugin (1 scala source)[0m
2022.11.18 12:04:15 INFO  compiling ziojsonrpcjvm (1 scala source)[0m
2022.11.18 12:04:15 INFO  compiling ziojsonrpcjs (1 scala source)[0m
2022.11.18 12:04:15 INFO  time: compiled plugin in 0.13s[0m
2022.11.18 12:04:15 INFO  time: compiled zioJsonRpcJS in 0.15s[0m
2022.11.18 12:04:15 INFO  compiling ziolspjvm (1 scala source)[0m
2022.11.18 12:04:15 INFO  time: compiled zioJsonRpcJVM in 0.2s[0m
2022.11.18 12:04:15 INFO  compiling server (1 scala source)[0m
2022.11.18 12:04:15 INFO  time: compiled zioLspJVM in 0.17s[0m
2022.11.18 12:04:15 INFO  time: compiled server in 0.14s[0m
Nov 18, 2022 12:19:04 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 61352
```
happily I had lsp tracing enabled at the time - here's the diagnostics info being sent
[lsp trace.zip](https://github.com/scalameta/metals/files/10036952/lsp.trace.zip)

### Expected behavior

errors reported in metals should be the same as those reported by sbt. If sbt can compile the whole project, there should be no reported errors.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

0.11.9

### Extra context or search terms

I've listed linux as the OS - this is ubuntu running in WSL.

```
Metals Doctor
Build server currently being used is Bloop v1.5.4.

Metals Java: 17.0.4.1 from Eclipse Adoptium located at /home/rob/.sdkman/candidates/java/17.0.4.1-tem

Metals Server version: 0.11.9
```

Answers to @ckipp01's questions from [discord](https://discord.com/channels/632150470000902164/632628489719382036/1042751590391615548) 
*Are you using Bloop or are you using sbt as a build server?*
Bloop

*Does it happen after you change your build definition?*
No changes to build definition for a few days

*Does the build import work after that?*
Didn't change the build so didn't try it

*Just understanding your flow and what you're hitting on is helpful*
I added some helper methods to some case objects that serve as type tags to safely recover the type information they're holding on to. This took a few attempts to get right.

As part of this I used "rename symbol" (`JsonRpc` to `JsonRpcMethod`). It looks like most of the errors relate to this except for those in "HelloWorldSpec.scala" which is a nothing file from the g8 template which has never changed. I guess it's possible that the text doc sync is not handling this properly, resulting in metals having out of date file contents. I don't recall if I had recently renamed anything last time I encountered this.

**Comment by robmwalsh** [comment] 2022-11-22 02:15
Hi @tgodzik, it's not public yet but will be by the end of the year. I didn't try `Metals: recompile workspace` so I'm not sure sorry - my usual approach to "Metals" (by which I mean anything in the toolchain behind it like Bloop) not working is "restart build server" followed by `killall -9 java` if it's still not working. In this case "restart build server" did the trick.

**Comment by tgodzik** [comment] 2022-11-22 11:02
ZIO stuff is usually pretty complicated (I found a number of Metals bugs in the codebases related to the ecosystem), so this might be something to take a closer look into with a proper reproduction.

You could also try using sbt BSP with `Metals: Switch build server` command, which will use sbt directly underneath.

**Comment by robmwalsh** [comment] 2022-11-30 00:14
sorry, I missed this reply. "ZIO stuff is usually pretty complicated" might explain why we're constantly experiencing compiler crashes with scala 3 where others seem to have limited issues... though I'm not sure I entirely agree with this characterisation. Most of the apparent complexity (zio-sql aside) in the zio ecosystem falls into a few basic patterns which pretty much amount to sacrificing ourselves to the boilerplate gods to provide a better user experience. It's confusing at first glance but once you wrap your head around the patterns it all becomes much clearer. There's a video here explaining some of them https://www.youtube.com/watch?v=48fpPffgnMo - some of it's pretty basic (e.g. `<:<`) but skipping through that video may help you decipher ZIO stuff a bit easier.

I'll give the SBT build server a go and see if it happens again - I generally prefer to use bloop because it's heaps faster (particularly when I'm using sbt in the command line at the same time!).

**Comment by tgodzik** [comment] 2022-11-30 09:40
I just meant that I feel like ZIO is using the type system heavily more than some other libraries (just my opinion) and that's why we're seeing more bugs pop up there. That's a good thing though :sweat_smile: since we want those bugs to show up sooner or later.

Thanks for the video, I will take a look!

**Comment by robmwalsh** [comment] 2022-12-02 00:15
notice some more weirdness - I was getting a type error showing up with a very unexpected type in metals. There was no error for this in SBT. Unfortunately I didn't capture this immediately, but here's a screenshot from a little down the debugging path. This `Handled` type showing up in the hover hasn't existed for many compile cycles now. The correct type is shown in the summon error message (this is a handy little trick I use when metals hover doesn't work). 

![image](https://user-images.githubusercontent.com/30517573/205182105-dadfabca-3b24-4bd0-816e-061145eb2fe2.png)
*side note - I take your point about the types :D*

I tried "clean compile workspace" which didn't change anything. Restarting the build server cleared the error but now I'm not getting hover at `x`. I tried using "Insert type annotation" for `x` which causes an internal error (see details).

<details>

```
[Error - 10:37:41 AM] Request workspace/executeCommand failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: scala.concurrent.Future$$anon$2: Future.filter predicate is not satisfied
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:708)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:38)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:484)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: scala.concurrent.Future$$anon$2: Future.filter predicate is not satisfied
```

</details>

This was using bloop still - I swapped the build server over to sbt, but this got stuck importing the build. I restarted vscode and got this error:
<img width="402" alt="image" src="https://user-images.githubusercontent.com/30517573/205184599-6481c311-d383-4205-8fb5-c444bb4f856e.png">

details shows a semanticdb issue
<img width="414" alt="image" src="https://user-images.githubusercontent.com/30517573/205184681-36e834cb-dca8-477c-89da-8786d95430be.png">

used `killall java -9`, imported build using metals, same semanticdb error

swapped back to bloop; semanticdb issues disappeared. still no hover for `x`, trying to insert type annotation causes the same internal error.

perhaps this should be a new issue but it at least started off as incorrect errors reported by metals :)

commit a3ebb92c45c9cff45ebd716a4c808c4c692276e8

**Comment by tgodzik** [comment] 2022-12-02 09:39
semanticdb error might pop up if the sbt-metals plugin has issues enabling it. Might be good to see what the target has defined there (you can click on the name to see summary) and whether it's not flaky

As for the hover, that might be an issue in the compiler, since insert type annotation also uses it. There should be some more info in `.metals/metals.log`

**Comment by robmwalsh** [comment] 2023-01-30 07:21
Still getting the same issues. Now using sbt as the build server. cc @ckipp01 
<img width="619" alt="image" src="https://user-images.githubusercontent.com/30517573/215412010-e1bd3ad2-927a-488f-9ef3-bbe29c827075.png">

there are a bunch of errors like this, all the same. The type did have 4 params, but I deleted one.
sbt compiles fine (a few unrelated warnings)

**Comment by ckipp01** [comment] 2023-01-30 07:25
Ah thanks for the extra info @robmwalsh. This one I'm very interested in, because if sbt is reporting an incorrect error over BSP (or stale I guess) but just a normal sbt compile works fine, then something is definitely off. Is there any way at all you can minimize this so that I can reproduce it? I'm assuming this is still in the private repo?

**Comment by robmwalsh** [comment] 2023-01-30 07:42
It's very inconsistent.  If I restart the build server, all is well again.
I suspect the issue may be that metals does not tell vscode to clear the diagnostics in some circumstances (as is required by the language server spec https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics )

**Comment by ckipp01** [comment] 2023-01-30 07:47
> I suspect the issue may be that metals does not tell vscode to clear the diagnostics in some circumstances (as is required by the language server spec https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_publishDiagnostics )

Sure, but even before that it's the actual build server that let's Metals know if we _should_ clear them or not. Metals really doesn't do much here apart from forwarded the information that the build server provides. For example you case see the format (that you're probably familiar with in LSP) in BSP [here](https://build-server-protocol.github.io/docs/specification#publish-diagnostics). If we get a `reset` as `true`, then we should be clearing. What I'd be curious in your situation is if that is indeed happening. For example you can create a `bsp.trace.json` in your `.metals/` dir and after a restart it will pipe the trace messages into that. I'd be curious when this is happening if your build server is sending a `build/publishDiagnostics` with `reset` or not. I have an inkling that it's not.

**Comment by robmwalsh** [comment] 2023-01-30 07:50
I did suffer another compiler crash today so I guess that's a possibility, but I deleted the param after the crash, so I don't think its likely.

**Comment by robmwalsh** [comment] 2023-01-30 08:08
I've created the BSP and LSP traces, I'll have a look for the reset flag in both next time it happens - thanks for the suggestion

**Comment by robmwalsh** [comment] 2023-01-30 09:26
> I'd be curious when this is happening if your build server is sending a `build/publishDiagnostics` with `reset` or not. I have an inkling that it's not.

It seems it is, but not always when it needs to.

I had this happen again and did some digging through the bsp logs. Here's the reported diagnostic:

```
[Trace - 07:42:04 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/internal/LspReader.scala"
  },
  "buildTarget": {
    "uri": "file:/home/rob/code/lsp/#zioLspJS/Compile"
  },
  "diagnostics": [
    {
      "range": {
        "start": {
          "line": 34,
          "character": 60
        },
        "end": {
          "line": 34,
          "character": 73
        }
      },
      "severity": 1,
      "code": "6",
      "source": "sbt",
      "message": "Not found: type JsonRpcReader"
    }
  ],
  "reset": true
}
```
and then...
nothing (as in no more `build/publishDiagnostics` messages for this file after this until I ran "Clean compile workspace")

Clean Compile workspace triggered this: which reset the diagnostics as expected.

```
[Trace - 07:51:38 PM] Received notification 'build/publishDiagnostics'
Params: {
  "textDocument": {
    "uri": "file:///home/rob/code/lsp/libs/zio-lsp/shared/src/main/scala/zio/lsp/internal/LspReader.scala"
  },
  "buildTarget": {
    "uri": "file:/home/rob/code/lsp/#zioLspJS/Compile"
  },
  "diagnostics": [],
  "reset": true
}
```

The interesting thing here is that the build target is home/rob/code/lsp/#zioLspJS - this is a cross-built project. There's another build target `file:/home/rob/code/lsp/#zioLspJVM/Compile` - for which there are no `build/publishDiagnostics` .. and this is the case for any crossbuilt project - only JS, no JVM. Perhaps it doesn't matter too much if the behaviour is consistent, but this is the sort of weirdness that I could see triggering something like this. At the very least, it suggests that the build isn't modelled correctly.

**Comment by ckipp01** [comment] 2023-01-30 09:49
Ah, I think _part_ of this is probably related to https://github.com/scalameta/metals-feature-requests/issues/13 which we've honestly just never tackled yet. sbt projects suffer from this more than Mill projects for example.

From looking at the trace it's not fully clear why there wouldn't be more diagnostics being reported from the build server, but as you can imagine, there's not a lot Metals can do if the build server isn't reporting anything. It's also sort of impossible to really debug this on our side without some type of reproduction, especially seeing that the issue seems to stem from the actual build server not reporting what is expected here.

**Comment by robmwalsh** [comment] 2023-01-30 20:53
Perhaps the problem is in BSP4J since I'm getting stale diagnostics with both bloop & sbt. I'll swap back to bloop and see if the bsp trace shows similar behaviour next time.

**Comment by tgodzik** [comment] 2023-01-31 14:53
- metals doesn't handle cross building properly

This is the most likely scenario especially with different Scala versions. Native/JS should work mostly ok, though might also suffer from some undercompilation somtimes.

I am curious, how is the other project using the same sources? Would be able to reproduce some skeleton of the dependencies between projects look like?

**Comment by robmwalsh** [comment] 2023-01-31 23:09
@tgodzik  https://github.com/robmwalsh/buildsketch

Here's a rather cut down build.sbt file and the plugins etc that I'm using
This is fairly typical of zio builds (based on the zio project seed)
Apologies for the BuildHelper file (it's part of the seed :/ there's an sbt plugin that will replace it eventually)

What's not typical is it's all scala 3 at this stage (3.2.1 at the moment, though I have been using nightlies at times), using JS and JVM platforms (no native, though I may add this at some point).There's no platform-specific code in these projects, so all the sources are in shared folders.

I'm not sure how much the crossbuild is affecting this particular issue - a plausible scenario is that a build server reports errors against a JS build target, then tells it to clear errors for a JVM build target. I've got no idea how metals translates bsp diagnostics to lsp diagnostics, so I guess anything is possible, but I'd expect this would be more likely to cause issues where there's platform specific sources.

**Comment by tgodzik** [comment] 2023-02-10 12:28
Thanks for the repro! I will take a look at it!

**Comment by ghostdogpr** [comment] 2023-05-02 04:35
I'm running into similar issues on a large project. I can't share it unfortunately, but I can describe what I observe. 

Let's say I do an initial compile, no errors reported but 50 "unused import" messages. I then start removing those imports one by one. If I do it slowly, no problem. But if I do it fast (which is normal), I'm modifying code while the project is compiling. When I do that, at some point it becomes out of sync: some imports that I removed are still reported as problems. 

From that point, I can't find a nice way to "recover" except doing a clean compile which I don't want to do because it takes 10 minutes on that project. Is there a way to make it synced again? Sbt or bloop compile in a separate terminal doesn't have any impact on what I see in VS Code. What's worse is that I can't even clean compile only the current project, VS Code only offers to do it on the whole project. 

Note that my example is trivial but it gets much worse when it's errors, and I'm constantly triggering it because the project is slow to compile so I'm constantly modifying code while it compiles. 

Thanks in advance if you have any suggestions 😄

**Comment by kpodsiad** [comment] 2023-05-02 06:26
>  What's worse is that I can't even clean compile only the current module, VS Code only offers to do it on the whole project.

This should be relatively easy to implement and expose to users. I was thinking about doing it few times when bloop went crazy, but unfortunately I'm a power user who uses bloop cli so I don't need UI for invalidating one module :|
Anyway, @ghostdogpr can you create an issue for that?

**Comment by ghostdogpr** [comment] 2023-05-02 06:29
> I'm a power user who uses bloop cli so I don't need UI for invalidating one module :|

Even if you use bloop cli (which I tried too), how does that get synced with the UI? (= how does the UI stop showing your code as red, when you re-trigger a build with bloop? Whatever I did in bloop did not impact VS Code so I'm curious.)

**Comment by robmwalsh** [comment] 2023-05-02 07:04
> > I'm a power user who uses bloop cli so I don't need UI for invalidating one module :|
> 
> Even if you use bloop cli (which I tried too), how does that get synced with the UI? (= how does the UI stop showing your code as red, when you re-trigger a build with bloop? Whatever I did in bloop did not impact VS Code so I'm curious.)

The trick to using bloop is... Don't! Using sbt as the BSP server has been a far better experience for me (except for bsp compilation blocking sbt cli)

**Comment by kpodsiad** [comment] 2023-05-02 07:26
@ghostdogpr `bloop clean foo & bloop compile foo` and then some change&save in vscode should do the trick, but after reading your message I'm not so sure about it anymore, I wasn't in such situation in a while and I don't remember details :/

> The trick to using bloop is... Don't!

Unfortunately, this is true. Using sbt definitely saves you from pain which bloop is inflicting 😢 But bloop is really fast and I can't resist that speed.

**Comment by ghostdogpr** [comment] 2023-05-02 07:35
@kpodsiad I did that but the change&save didn't trigger a re-sync of the incorrect "problems", they just stayed there.

**Comment by tgodzik** [comment] 2023-05-02 09:45
This is a curious case, the issue might be connected to the fact that we don't run multiple compiles at the same time. Do you have  automatic save enabled maybe?

**Comment by ghostdogpr** [comment] 2023-05-02 09:48
> This is a curious case, the issue might be connected to the fact that we don't run multiple compiles at the same time. Do you have  automatic save enabled maybe?

I do save instantly after each modification.

**Comment by ghostdogpr** [comment] 2023-05-02 09:51
Because the project is large and takes time to compile, I'm always modifying files while compilation is going on (there are a lot of messages about deduplicating compilation in the output). It does look like this is what's causing Metals to be out of sync.

**Comment by robmwalsh** [comment] 2023-05-04 03:14
> This is a curious case, the issue might be connected to the fact that we don't run multiple compiles at the same time. Do you have automatic save enabled maybe?

@tgodzik are any diagnostics reported from the presentation compiler? these may clash with those being reported via bsp.

@ghostdogpr I've found that restarting the build server is the only way to clear out all the errors and get things to resync. sometimes you need to be more forceful with restarting (`killall java -9`)

**Comment by tgodzik** [comment] 2023-05-04 16:15
> are any diagnostics reported from the presentation compiler? these may clash with those being reported via bsp.

We don't report errors from the presentation compiler to limit the amount of errors while writing code, that might not compiler. We rely on errors from the compiler via BSP.

>  I've found that restarting the build server is the only way to clear out all the errors and get things to resync. sometimes you need to be more forceful with restarting (killall java -9)

I want to look into this, since this seems a bigger issue than I thought.

**Comment by carlosedp** [comment] 2023-06-23 18:40
This is a repro example capture I did... happens mostly using mill-bsp:

https://streamable.com/f00gmh

**Comment by tgodzik** [comment] 2023-06-29 13:04
Metals needs to get empty diagnostics for a file to clear the errors, so this might be an issue with Mill. Otherwise we would need to keep that information inside Metals, which I would prefer to avoid, since that might cause some unexpected issues.

If you do another error inside that file does it remove the old one? Does the situation with stale errors happens often when fixing all of them?

**Comment by carlosedp** [comment] 2023-06-29 16:59
I've collected the metals.log, bsp and lsp traces to this zip... my environment variables have been replaced with XXXXX due to containing tokens and etc...

[Logs.zip](https://github.com/scalameta/metals/files/11908510/Logs.zip)


Hope I can help with anything else.

**Comment by tgodzik** [comment] 2023-06-30 11:05
I don't see any empty diagnostics being sent, so I think that's the issue with stale errors. When everything is fixed Mill should send empty diagnostics with reset set to true.

**Comment by carlosedp** [comment] 2023-07-19 20:49
Worth opening an issue on Mill about this error staying stuck?

**Comment by lefou** [comment] 2023-07-20 06:36
* https://github.com/com-lihaoyi/mill/issues/2426

**Comment by tgodzik** [comment] 2023-12-07 16:58
Looks like this is now fixed in Mill! :tada:

**Closed by tgodzik** 2023-12-07 16:58 UTC
Labels: investigation needed, stability
