### ISSUE TITLE
Worksheet:  NoClassDefFoundError: java/sql/...  but identical class will compile

### ISSUE THREAD

**Issue by sfc-gh-sozer** [scalameta/metals#2244] opened 2020-11-19 00:54 UTC
**Describe the bug**

Using Worksheet mode (.sc file) in metals, any methods referencing JDBC operations result in `NoClassDefFoundError: java/sql/...`.  But the same code in a .scala file in the same project compiles and runs without complaint.

**To Reproduce**

1.  Create a simple JDBC connection using any database driver
2.  Hover over DriverManager.getConnection and see java/sql error

Simplest possible repro is shown here.   Following worksheet fails, see screenshot

> 
> import java.sql.DriverManager
> java.sql.DriverManager.drivers().forEach(println(_))

but the following class compiles and runs:

> package example
> import java.sql.DriverManager
> object Hello extends App {
>   java.sql.DriverManager.drivers().forEach(println(_))
> }

**Expected behavior**

It should just work producing a list of JDBC drivers available in the project classpath

**Screenshots**

<img width="541" alt="Screen Shot 2020-11-18 at 4 45 50 PM" src="https://user-images.githubusercontent.com/71187795/99606320-587c5380-29be-11eb-97da-0a42cbc001a0.png">

**Installation:**

- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.9.5
- JVM: OpenJDK 11

**Additional context**

This is a minimal (no DB needed) repro of a problem that surfaced in a more complex project.  Any references to classes making SQL operations in a worksheet led to java/sql/... errors. 

**Search terms**

NoClassDefFoundError Worksheet java/sql

**Comment by ckipp01** [comment] 2020-11-19 06:50
Thanks for the report @sfc-gh-sozer. Its looks like you're hitting on this https://github.com/scalameta/metals/issues/2187. Are you able to give Java 8 a try to confirm that it's the same situation for you? If so, I'll just close this as a duplicate of #2187.

**Comment by sfc-gh-sozer** [comment] 2020-11-19 17:05
Ahh -- must be @ckipp01. Apologies for not seeing that before reporting :)  Go ahead and close as dup...

**Comment by ckipp01** [comment] 2020-11-19 17:29
No worries! Thanks for reporting!

**Closed by ckipp01** 2020-11-19 17:29 UTC
