### ISSUE TITLE
.bloop/*.json "classesDir" configuration isn't respected

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#1428] opened 2020-02-13 14:37 UTC
**Describe the bug**
Metals ignores `.bloop/*.json` "classesDir" configuration.

**To Reproduce**
1. Go to project
2. Await for `bloopInstall`
3. Observe:
```
$ grep classesDir .bloop/*.json
.bloop/scala-playground-test.json:        "classesDir": "/home/man/projects/scala-playground/.bloop/scala-playground/scala-2.12/test-classes",
.bloop/scala-playground.json:        "classesDir": "/home/man/projects/scala-playground/.bloop/scala-playground/scala-2.12/classes",
$ find .bloop -type f -a -not -iname *.json -exec du -h {} +
4.0K	.bloop/scala-playground/bloop-bsp-clients-classes/classes-Metals-GTMzrJDdQweEvgks3Fi6Kw==/Fs2StreamDebounce.class
4.0K	.bloop/scala-playground/bloop-bsp-clients-classes/classes-Metals-GTMzrJDdQweEvgks3Fi6Kw==/Fs2StreamShutdown.class
12K	.bloop/scala-playground/bloop-bsp-clients-classes/classes-Metals-GTMzrJDdQweEvgks3Fi6Kw==/Fs2StreamShutdown$.class
32K	.bloop/scala-playground/bloop-bsp-clients-classes/classes-Metals-GTMzrJDdQweEvgks3Fi6Kw==/Fs2StreamFeedback$.class
…
```

**Expected behavior**
```
$ grep classesDir .bloop/*.json
.bloop/scala-playground-test.json:        "classesDir": "/home/man/projects/scala-playground/.bloop/scala-playground/scala-2.12/test-classes",
.bloop/scala-playground.json:        "classesDir": "/home/man/projects/scala-playground/.bloop/scala-playground/scala-2.12/classes",
$ find .bloop -type f -a -not -iname *.json -exec du -h {} +
4.0K	.bloop/scala-playground/scala-2.12/classesFs2StreamDebounce.class
4.0K	.bloop/scala-playground/scala-2.12/classes/Fs2StreamShutdown.class
12K	.bloop/scala-playground/scala-2.12/classes/Fs2StreamShutdown$.class
32K	.bloop/scala-playground/scala-2.12/classes/Fs2StreamFeedback$.class
…
```

**Installation:**
- Operating system: Linux
- Editor: Vim (coc-nvim)
- Metals version: v0.8.0+230-1cd23494-SNAPSHOT
- Bloop version: v1.4.0-RC1+33-dfd03f53

**Additional context**
Discovered while working on Bloop Tmpfs plugin for Sbt:  
https://github.com/scalacenter/bloop/issues/1031#issuecomment-585775689

**Comment by tgodzik** [comment] 2020-02-13 15:09
Hi, thanks for reporting! 

I am not sure what the issue here is, Metals isn't involved with the compilation at all. What Metals feature is impacted by this? We are using classes directories provided to us by Bloop and they seem correct to me - those are the client classes directory as intended.

**Comment by arbitrary-dev** [comment] 2020-02-13 17:53
>I am not sure what the issue here is
Metals starts Bloop server and asks `bloopInstall` which generates `.bloop/*.json` configuration files where there are `classesDir` parameters which specifies where Bloop should store compiled `*.class` files. This configuration was working fine as of previous Metals version I used (0.7, I guess).

>What Metals feature is impacted by this?
Nowadays, when Metals asks Bloop for compilation (through BSP, I suppose), these `classesDir` parameters in `.bloop/*.json` configuration files are ignored and the files get compiled in `.bloop/*/bloop-bsp-clients-classes/classes-Metals-GTMzrJDdQweEvgks3Fi6Kw==/` directory instead.

So it seems like Bloop server started by Metals picks up configuration from somewhere else rather than `.bloop/*.json`

**Comment by olafurpg** [comment] 2020-02-13 18:25
@arbitrary-dev can you elaborate on your use-case for `classesDir`?

**Comment by arbitrary-dev** [comment] 2020-02-13 21:20
@olafurpg I'd like to develop [an Sbt plugin](https://github.com/arbitrary-dev/sbt-bloop-tmpfs) which will offload to Tmpfs all the `*.class`'es (specified by `classesDir`) & other files that Bloop create in a process of compilation instantiated by Metals through BSP.

Tmpfs is useful in this case to spare SSD cycles from continuous compilations/recompilations.

Also everything was working just fine on Metals 0.7 (Bloop 1.3.4), but on Metals 0.8 (Bloop 1.4.0-RC1) things got broken, perhaps some infrastructure have changed.

**Comment by tgodzik** [comment] 2020-02-14 18:19
Metals is not responsible for the compilation, so we only use what Bloop gives us.

I don't believe it is a issue in Metals.

And from what I understand, it is normal for Bloop to create separate dirs for each of the clients.

**Comment by tgodzik** [comment] 2020-02-20 10:37
Closing this, because `classesDir` are actually supported correctly and the plugin you are implementing will most likely need to wait for offloading to be finished.

**Closed by tgodzik** 2020-02-20 10:37 UTC
Labels: needs more information

**Comment by davidmlw** [comment] 2020-03-23 01:27
classesDir is not respected. 
Currently the classes is put in .bloop/project/bloop-internal-classes/bloop-cli-tu<randomletters>/project/

and this is not related metals at all.
