### ISSUE TITLE
Remote extension disables Metals despite fulfilled dependency

### ISSUE THREAD

**Issue by alec-bernardi** [scalameta/metals#2952] opened 2021-07-12 15:15 UTC
**Describe the bug**

As of the latest release of VSCode the `Scala (Metals)` extension is disabled when using the `Remote - SSH` extension to develop remotely.
It claims a dependency is disabled, when in reality the `Scala Syntax` extension runs locally, but `Scala (Metals)` runs remotely.

**To Reproduce**

1. Install the following extensions: `Remote - SSH`, `Scala (Metals)`, and `Scala Syntax (official)`
2. Connect to a remote host  (via Command Palette:  Remote-SSH: Connect to Host`)
3. In the Explorer tab, use `Open Folder` to open a Scala project
4. In the Extensions tab, see that `Scala (Metals)` is disabled: `This extension has been disabled because it depends on an extension that is disabled`

**Expected behavior**
The plugin should not be disabled.

**Screenshots**

![image](https://user-images.githubusercontent.com/51329603/125309510-d4396080-e2ff-11eb-9112-442c7b178151.png)

**Installation:**

- Operating system: Windows (Local)/Linux (Remote)
- Editor: Visual Studio Code (1.58.0)
- Metals version: v1.10.6

**Additional context**

**Search terms**

**Comment by tgodzik** [comment] 2021-07-12 15:23
Thanks for reporting, the issue is caused by a recent change in VS Code, closing in favour of https://github.com/scalameta/metals-vscode/issues/613

**Closed by tgodzik** 2021-07-12 15:23 UTC
