### ISSUE TITLE
Go to definition doesn't work.

### ISSUE THREAD

**Issue by goral09** [scalameta/metals#1577] opened 2020-04-02 09:52 UTC
**Describe the bug**
When trying to **Go-to definition** of the method (that is in the same file) the functionality does not work. It jumps to the top of the current file.

**To Reproduce**
I'm sorry I can't provide a minimal working example. You can try checking-out [my project](https://github.com/CasperLabs/CasperLabs/blob/NO-TICKET_improve_finalizer/casper/src/test/scala/io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest.scala#L29) and **go-to** on `createBlockAndUpdateFinalityDetector`.

**Expected behavior**
Cursor jumps to the definition.

**Screenshots**
In the [gif I recoreded](https://gfycat.com/jaggedoptimisticcoyote) you can see that VSCode knows the type definition of the method but fails on **go-to definition** action. On the second try, I am using the same action on another method and this time it jumps correctly.

**Installation:**
- Operating system: Linux Ubuntu LTS
- Editor: Visual Studio Code
- Metals version: v0.8.3

**Additional context**

**Search terms**
go to, go-to, jump to definition, definition

**Comment by kpbochenek** [comment] 2020-04-02 12:09
Thanks for reporting this issue!

This is reproducible and looks like a bug.

From technical checking:
This is a problematic piece of code(line 70 1-based, which means 69 0-based)
![2020-04-02-140514_782x239_scrot](https://user-images.githubusercontent.com/10478402/78247326-ffbd8080-74ea-11ea-88eb-6a3eaa9eb382.png)

Metap output from generated semanticdb:
```
[67:70..67:79) => io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest#mkVotingMatrix().(isHighway)
[69:11..69:13) <= local23
[69:15..69:17) <= local24
[69:22..69:58) => io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest#
[69:59..69:63) => monix/eval/Task#
[70:23..70:26) => scala/collection/Seq.
```

It resolves `createBlockAndUpdateFinalityDetector` into `io/casperlabs/casper/finality/votingmatrix/FinalityDetectorByVotingMatrixTest#` which is wrong.

**Comment by kcwill2** [comment] 2021-03-10 17:27
My team is seeing this problem as well. go to definition is pretty unreliable. some symbols work, some symbols don't even those defined in the same source file.

**Comment by tgodzik** [comment] 2021-04-26 09:29
It seems that we no longer have reproduction for this. If anyone manages to get some reliable reproduction, do let me know. Closing this for now.

**Closed by tgodzik** 2021-04-26 09:29 UTC
Labels: bug, semanticdb, upstream-fix-needed
