### ISSUE TITLE
BuildInfo.metalsVersion is set incorrectly in releases

### ISSUE THREAD

**Issue by isomarcte** [scalameta/metals#662] opened 2019-04-13 16:35 UTC
**Describe the bug**
When building the code from the release tar.gz, the value of `BuildInfo.metalsVersion` is incorrectly set to the `SNAPSHOT` version. This leads to the incorrect version of `sbt-metals` being set in the generated `metals.sbt` file, causing a resolution failure.

All that to say, it is currently not possible to build the code correctly for the released tar.gz.

**To Reproduce**

```shell
$ /tmp/tmp.kWwDd0lwFh λ > wget -q 'https://github.com/scalameta/metals/archive/v0.5.0.tar.gz'
$ /tmp/tmp.kWwDd0lwFh λ > ls
v0.5.0.tar.gz
$ /tmp/tmp.kWwDd0lwFh λ > tar xvzf v0.5.0.tar.gz
$ /tmp/tmp.kWwDd0lwFh λ > ls
metals-0.5.0  v0.5.0.tar.gz
$ /tmp/tmp.kWwDd0lwFh λ > cd metals-0.5.0
$ /tmp/tmp.kWwDd0lwFh/metals-0.5.0 λ > sbt 'show version'
[info] Loading settings for project global-plugins from plugins.sbt,metals.sbt ...
[info] Loading global plugins from /home/dstrawn/.sbt/1.0/plugins
[info] Loading settings for project metals-0-5-0-build-build from plugins.sbt ...
[info] Loading project definition from /tmp/tmp.kWwDd0lwFh/metals-0.5.0/project/project
[info] Updating ProjectRef(uri("file:/tmp/tmp.kWwDd0lwFh/metals-0.5.0/project/project/"), "metals-0-5-0-build-build")...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project metals-0-5-0-build from plugins.sbt ...
[info] Loading project definition from /tmp/tmp.kWwDd0lwFh/metals-0.5.0/project
[info] Compiling 1 Scala source to /tmp/tmp.kWwDd0lwFh/metals-0.5.0/project/target/scala-2.12/sbt-1.0/classes ...
[info] Done compiling.
[info] Loading settings for project metals-0-5-0 from build.sbt ...
[info] Set current project to metals-0-5-0 (in build file:/tmp/tmp.kWwDd0lwFh/metals-0.5.0/)
[info] unit / version
[info] 	0.5.1-SNAPSHOT
[info] interfaces / version
[info] 	0.5.1-SNAPSHOT
[info] metals / version
[info] 	0.5.1-SNAPSHOT
[info] bench / version
[info] 	0.5.1-SNAPSHOT
[info] docs / version
[info] 	0.5.1-SNAPSHOT
[info] mtest / version
[info] 	0.5.1-SNAPSHOT
[info] sbt-metals / version
[info] 	0.5.1-SNAPSHOT
[info] input / version
[info] 	0.5.1-SNAPSHOT
[info] cross / version
[info] 	0.5.1-SNAPSHOT
[info] mtags / version
[info] 	0.5.1-SNAPSHOT
[info] slow / version
[info] 	0.5.1-SNAPSHOT
[info] version
[info] 	0.5.1-SNAPSHOT
```

```scala
// DO NOT EDIT! This file is auto-generated.
// By default, this file does not do anything.
// If the environment variable METALS_ENABLED has the value 'true',
// then this file enables sbt-metals and sbt-bloop.
resolvers ++= {
  if (System.getenv("METALS_ENABLED") == "true") {
    List(Resolver.sonatypeRepo("snapshots"))
  } else {
    List()
  }
}

libraryDependencies := {
  import Defaults.sbtPluginExtra
  val oldDependencies = libraryDependencies.value
  if (System.getenv("METALS_ENABLED") == "true") {
    val bloopModule = "ch.epfl.scala" % "sbt-bloop" % "1.2.5"
    val metalsModule = "org.scalameta" % "sbt-metals" % "0.5.1-SNAPSHOT"
    val sbtVersion = Keys.sbtBinaryVersion.in(TaskKey[Unit]("pluginCrossBuild")).value
    val scalaVersion = Keys.scalaBinaryVersion.in(update).value
    val bloopPlugin = sbtPluginExtra(bloopModule, sbtVersion, scalaVersion)
    val metalsPlugin = sbtPluginExtra(metalsModule, sbtVersion, scalaVersion)
    List(bloopPlugin, metalsPlugin) ++ oldDependencies.filterNot { dep =>
      (dep.organization == "ch.epfl.scala" && dep.name == "sbt-bloop") ||
      (dep.organization == "org.scalameta" && dep.name == "sbt-metals")
    }
  } else {
    oldDependencies
  }
}
```

**Comment by isomarcte** [comment] 2019-04-13 16:38
I'd be happy to open a PR to fix this, but I'd like to discuss how you'd like to fix this. There are a number of ways, from an environment variable, a new `build.sbt` value, to using one of the various sbt release related plugins.

**Comment by gabro** [comment] 2019-04-14 08:13
Hi @isomarcte, the relevant code here here:

https://github.com/scalameta/metals/blob/6693914e4662220df4a04ce3ab841a11a851c0b0/build.sbt#L2-L8

The current use cases (which justify the code above) are:

- publishing from the CI: dynamically computed version (for publishing on Sonatype/Maven)
- publishing locally: use a fixed SNAPSHOT version, to allow fast iteration when developing (so that you can keep a stable `"metals.version"` in VSCode setting and just reload the editor to test the latest version)

As of today, a quick workaround for your use case would be to set the `CI` variable (to anything, e.g. `CI=true`) and Metals will use the dynamically computed version.

I can imagine adding another env variable for clarity, along the lines of:

```diff
 def isCI = System.getenv("CI") != null
+def useDynVer = System.getEnv("USE_DYN_VER") != null
 inThisBuild(
   List(
     version ~= { dynVer =>
-      if (isCI) dynVer
+      if (useDynVer || isCI) dynVer
       else localSnapshotVersion // only for local publishng
     }, 
```

**Comment by gabro** [comment] 2019-04-14 08:22
Ah now that I look at it, the `dynVer` would probably not work since you miss the Git metadata when building from the tar file.

Since we base `dynVer`, I don't think downloading the tar it can ever give you a correct Metals version, unless we hardcode it somewhere.

So I see two options here:

1. hardcode the stable version somewhere and use it as a fallback for when `dynVer` can't be computed
2. allow setting a `METALS_VERSION` variable to force a version

Honestly I think option 1 is a bit incovenient from the maintainers point of view, since it's easy to forget and dynVer works very well for the common use cases.
I would rather go with option 2, and have something like:

```
 def isCI = System.getenv("CI") != null
+def forcedVersion = System.getEnv("METALS_VERSION")
 inThisBuild(
   List(
     version ~= { dynVer =>
       if (forcedVersion != null) forcedVersion
-      if (isCI) dynVer
+      else (isCI) dynVer
       else localSnapshotVersion // only for local publishng
     }, 
```

**Comment by gabro** [comment] 2019-04-14 08:35
Sorry for the stream of consciousness, but now that I think about it, you could also sidestep the problem and use `coursier bootstrap --standalone` to build a fatjar from the correct published version.

**Comment by isomarcte** [comment] 2019-04-14 14:05
Hey @gabro thanks for the response. 

Of the two options you proposed, a hard coded version value and a environment variable, I agree the environment variable is the better option. 

With respect to the fatjar option through `coursier`, I agree that would allow for the creation of a valid release binary, but that sort of sides steps the issue. It is generally expected that running the default build command on a released commit (in any VCS) will result in a valid release build. Using the pre-compiled artifacts rather than the source doesn't directly address that issue.

Just to give you some context on where I am coming from, I am attempting to package `metals` for various package managers. This is because `metals` is amazing, and because in *nix systems loading an unmanaged binary into the file system hierarchy is consider bad practice (you can't uninstall it easily, you don't get updates automatically, etc.). All of the packaging systems that I am aware of, rpm, deb, brew, macports, pacman, bsd-ports, are designed to do a source build of the target package. They may distribute a binary file, but they still are supposed to do a source build to create the binary they distribute. 

To that end I have already created an [Arch Linux package for `metals`][archlinux-metals], though in order to make it work correctly I had to add a [patch][AUR-patch]. It would be nice if package maintainers weren't forced to do that. 

Thanks again.

[archlinux-metals]: https://aur.archlinux.org/packages/metals/ "AUR Metals"

[AUR-patch]: https://aur.archlinux.org/cgit/aur.git/tree/version-fix.patch?h=metals "Version Patch"

**Comment by olafurpg** [comment] 2019-04-14 16:34
> I have already created an Arch Linux package for metals,

Thank you for your work and reporting this issue, having a Arch Linux package is awesome!

To build the project in the same environment as the published releases, you can run `CI=true sbt $COMMAND`. The `SNAPSHOT` version is used during local development.

Can you elaborate on the motivation to build Metals from source? Running `sbt compile` downloads a lot of binaries from Maven Central  so you only compile <1% of sources that contribute to the final artifact, either way. In comparison, `coursier bootstrap --standalone` builds a fatjar from Maven Central, which provides an immutable data storage for the full dependency classpath.

> It is generally expected that running the default build command on a the tree of a released commit (in any VCS) will result in a valid release build, without having to have the VCS metadata present, e.g .git.

We use git-based versioning in this project for better or worse. It helps us keep the version number synchronized with the git commit, which makes it for example easy to publish a unique version for every merged PR that people can install via https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

**Comment by olafurpg** [comment] 2019-04-14 16:50
BTW, the command `CI=true sbt 'set every version := "0.5.0"' compile` can be used to define the version number even if `.git` does not exist.

**Comment by isomarcte** [comment] 2019-04-14 18:59
Hey @olafurpg, 

> Can you elaborate on the motivation to build Metals from source? 

Sure, or at least I can attempt to. Though I should state the these are not necessarily my personal opinions, but the general motivation for package managers to build from source as I understand them. 

* Reduce duplication in the file system by having binaries dynamically link to common shared libraries. (as opposed to creating static binaries for all everything)
* Apply patches or minor modifications to the source for a variety of reasons.
* Allow package maintainers or users to customize compilation parameters (this is of particular interest to Gentoo and Arch users, though custom rebuilds are not uncommon in other *nix environments too.)

That all being said, I agree these arguments of _much less weight_ in the JVM ecosystem. Here are some reasons why building from source _doesn't_ make a lot of sense. 

* Compilation parameters for `scalac` and `javac` have much less effect than those of other compilers such as `clang` or `gcc`. 
* Managing dynamic linking between many different libraries and binaries is very difficult. This has lead to many people just making static binaries or using tools like [Flatpak][flatpak] or [Snaps][snap] to create containerized environments with the explicit goal of _not_ sharing library dependencies.

> Running sbt compile downloads a lot of binaries from Maven Central so you only compile <1% of sources that contribute to the final artifact, either way. 

I realize that building just metals from source and while downloading the dependencies from Maven Central means that most of the code is actually not compiled from source. The _idea_ is that eventually the dependencies would be moved into their own packages and then linked dynamically (See item 3 [of the Arch Linux Java Packaging Guidelines][java-packaging-guidelines]). For example, this is how things work for the [Haskell ecosystem on Arch Linux][haskell-arch-packages]. Though I think it is unlikely that all of `metals` dependencies would get packaged.

All that to say though, I do agree that in this case it is not very important to build from source. My motivation to do so is primarily just to keep in line with packaging best practices, my personal opinions on it aside. Since it is also not very difficult to build from source either, I opted to follow the standard guidelines.

> We use git-based versioning in this project for better or worse. It helps us keep the version number synchronized with the git commit, which makes it for example easy to publish a unique version for every merged PR that people can install via https://scalameta.org/metals/docs/editors/vscode.html#using-latest-metals-snapshot

I totally understand, and to be clear, I don't think there is anything wrong with using VCS based versioning. It is especially useful for `SNAPSHOT` builds, as you pointed out. I was merely hoping we could find a solution that would allow the release builds generated from the `tar.gz` of the commit to build correctly without modification.

> BTW, the command CI=true sbt 'set every version := "0.5.0"' compile can be used to define the version number even if .git does not exist.

I did not realize that. That will make packaging more simple.

I'd be interested in hearing any other thoughts you might have on this. If you guys would prefer to leave things as is, that is fine with me too, feel free to close the issue in that case. I'll just modify the version in the packages as I'm doing now.

Thanks again for your thoughts on this.

[flatpak]: https://flatpak.org/ "Flatpak"
[snap]: https://snapcraft.io/ "Snap"
[haskell-arch-packages]: https://www.archlinux.org/packages/?sort=&q=haskell&maintainer=&flagged= "Haskell Arch Packages"

[java-packaging-guidelines]: https://wiki.archlinux.org/index.php/Java_package_guidelines#Java_packaging_on_Arch_Linux "Arch Linux Java Packaging Guidelines"

**Comment by olafurpg** [comment] 2019-04-15 07:42
@isomarcte thank you for the explanation! If the workaround `CI=true sbt 'set every version := "0.5.0"' compile` works then I think it's best to close this issue with "working as intended". Note that the Metals server dynamically resolves and classloads the `mtags` module for the exact Scala version matching the users build. When making source changes to mtags you need to re-publish mtags for Scala 2.11.12/2.12.8/2.12.7/... via the command `+mtags/publishLocal`.

**Closed by olafurpg** 2019-04-15 07:42 UTC

**Comment by isomarcte** [comment] 2019-04-15 12:46
@olafurpg sounds good. 

> When making source changes to mtags you need to re-publish mtags for Scala 2.11.12/2.12.8/2.12.7/... via the command +mtags/publishLocal.

Thanks for letting me know. I'll keep that in mind when packaging it.
