### ISSUE TITLE
(scala3) type hints missing some type parameters

### ISSUE THREAD

**Issue by kubukoz** [scalameta/metals#3935] opened 2022-05-20 20:23 UTC
### Describe the bug

As seen on the screenshot: type hints have empty strings instead of inferred parameters.

Reproduction: 

1. use scala-cli 0.1.3
2. Create file:

```scala
//>using scala "3.1.1"
//>using lib "org.typelevel::cats-core:2.7.0"
//>using lib "org.typelevel::cats-effect:3.3.9"
sealed trait Error extends Product with Serializable

object Error {
  case object C extends Error
}

object demo {
  import util.chaining._
  import cats.implicits._
  import cats.effect._
  import cats.data._

  val r = IO(42).pipe(EitherT.liftF(_))

}
```

3. Enable type hints

Actual result, line 16:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/894884/169605053-e75969a4-1c9c-48a1-9a7e-b459dec56e86.png">

In Scala 2:

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/894884/169605101-28aa77a1-4e6a-4557-bd13-93ad10107183.png">

Note the additionally missing type hints on the method calls in the body of `r`, although that's likely a separate issue.

### Expected behavior

Similar to Scala 2 as shown above.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

0.11.5

**Comment by tanishiking** [comment] 2022-09-06 07:08
I'm not sure how it was fixed, but it looks like it's fixed in scala 3.2.0 :tada:

<img width="1149" alt="Screen Shot 2022-09-06 at 16 04 35" src="https://user-images.githubusercontent.com/9353584/188568856-d9b7083c-5e6a-4d3b-960a-a2cbbba9ffb5.png">


```
test/demo.r. => val method rEitherT[IO, Nothing, Int]
  EitherT => cats/data/EitherT#
  IO => cats/effect/IO#
  Nothing => scala/Nothing#
  Int => scala/Int#
```

**Comment by tgodzik** [comment] 2022-09-06 07:24
That's awesome! I can confirm that it works with the example. We should probably add a test case to close this.

**Comment by kasiaMarek** [comment] 2024-02-16 12:13
Since this works now, and Metals doesn't even use SemanticDB for decorations anymore, so a test wouldn't make much sense, I'm just closing this.

**Closed by kasiaMarek** 2024-02-16 12:13 UTC
Labels: bug, Scala 3, semanticdb
