### ISSUE TITLE
NullPointerException during textDocument/completion

### ISSUE THREAD

**Issue by arosien** [scalameta/metals#829] opened 2019-07-15 23:37 UTC
```
[Error - 1:42:13 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:36)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at scala.tools.nsc.Global.isPast(Global.scala:1007)
	at scala.tools.nsc.Global.isPastTyper(Global.scala:1003)
	at scala.reflect.internal.Symbols$MethodSymbol.typeAsMemberOf(Symbols.scala:3015)
	at scala.reflect.internal.Types$Type.memberType(Types.scala:728)
	at scala.meta.internal.pc.Completions.detailString(Completions.scala:252)
	at scala.meta.internal.pc.Completions.detailString$(Completions.scala:246)
	at scala.meta.internal.pc.MetalsGlobal.detailString(MetalsGlobal.scala:23)
	at scala.meta.internal.pc.CompletionProvider.$anonfun$completions$1(CompletionProvider.scala:68)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at scala.collection.Iterator.toStream(Iterator.scala:1415)
	at scala.collection.Iterator.toStream$(Iterator.scala:1414)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1429)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1415)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1171)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1161)
	at scala.collection.immutable.StreamIterator.$anonfun$next$1(Stream.scala:1061)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1050)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1050)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1055)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:134)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:40)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:412)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:145)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:59)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$1(RemoteEndpoint.java:281)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
	... 9 more
```

VS Code Extension info:
```
Name: Scala (Metals)
Id: scalameta.metals
Description: Scala language server with rich IDE features
Version: 1.5.1
Publisher: Scalameta
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=scalameta.metals
```

Incidentally, I have a `bloop test -w` running in a terminal, but I'm not sure it is affecting this:
```
> bloop about
bloop v1.3.2

Using Scala v2.12.8 and Zinc v1.3.0-M4+22-4704d479
Running on Java v1.8.0_144 (/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre)
Maintained by the Scala Center (Martin Duhem, Jorge Vicente Cantero)
```

**Comment by tgodzik** [comment] 2019-07-16 09:22
Thanks for reporting! Do you have any reproduction of the issue?

Is this still happening on a particular piece of code? Or was it just one off?

**Comment by arosien** [comment] 2019-07-16 16:46
I haven't been able to reproduce it. I believe it happened immediately after my laptop woke up, so perhaps there was some kind of race condition as metals tried to connect to something, etc.

**Comment by tgodzik** [comment] 2019-07-17 07:16
We are pretty aggressive about restarting the presentation compiler, so the issues like this should not be a problem. As you said this might be some race condition or it could be some internal state.

That null comes from a place that has a var, so pretty sure the internal state of presentation compiler must have been corrupted.

Since, it's not possible to reproduce I am closing this, but let use know if this happens again and becomes a problem.

**Closed by tgodzik** 2019-07-17 07:16 UTC
Labels: needs more information

**Comment by arosien** [comment] 2019-07-17 17:30
Perhaps file another issue for another project? Scala code that doesn't handle a `null` sounds so... primitive 😢.

**Comment by tgodzik** [comment] 2019-07-18 09:41
The Scala presentation compiler contains quite a bit of mutable state for efficiency's sake. Because of that it's pretty hard to debug and stuff like that might happen. Without a reproduction is near impossible to fix.
