### ISSUE TITLE
goto definition for val is not working

### ISSUE THREAD

**Issue by suchendra** [scalameta/metals#532] opened 2019-02-18 14:32 UTC
**Describe the bug**

I have declared the value using val in the code, but when I tried to get the goto definition of that it is not working.

**To Reproduce**
1. declare the values using val
2. Cmd + click on it.
3. not able to Click.

**Expected behavior**

Should work like, how 'var' works.

**Screenshots**

**Installation:**
- Operating system: macOS
- Editor: Both Visual Studio Code/Atom
- Metals version: v0.4.0

**Additional context**

**Search terms**

**Comment by olafurpg** [comment] 2019-02-18 14:36
Thanks for reporting! Can you please include some example code/screenshot? I am unable to reproduce.

**Comment by suchendra** [comment] 2019-02-18 14:39
`val httpBindingFuture = Http().bindAndHandle(route, host, port)`

and 

`val host = localhost`
`val port = 3004`

When I tried to hover on the host and port, not able to get the definition

**Comment by olafurpg** [comment] 2019-02-18 15:29
It's expected that hovering on `host` doesn't show the definition since hover is not implemented https://github.com/scalameta/metals/issues/431 

Did you save the source code and make sure that it compiles before running goto definition?

**Comment by olafurpg** [comment] 2019-02-18 15:29
Also, have you imported the build?

**Comment by suchendra** [comment] 2019-02-19 03:02
Yes, I have imported the build and even saved the files, but it is working for the other methods and variables. I meant not exactly hovering, cmd+ hover which will make the hovering values like a link that's not working.

**Comment by olafurpg** [comment] 2019-02-20 08:47
Thanks for the information, I am still unable to reproduce. Is there helpful information in `.metals/metals.log`?

**Comment by suchendra** [comment] 2019-02-20 13:06
Sure, I will get it.

**Comment by suchendra** [comment] 2019-02-21 06:55
I checked on metals log I did not get any information. How would I conclude on this bug?

**Comment by olafurpg** [comment] 2019-02-21 08:57
It's difficult to fix without a reproduction. We still have a few known navigation issues but they are primarily around extension methods in for comprehensions.

**Comment by olafurpg** [comment] 2019-02-22 12:19
Closing as "needs more information". Please reopen if you are able to provide a reproduction.

**Closed by olafurpg** 2019-02-22 12:19 UTC
