### ISSUE TITLE
Unable to find references for symbols from external library

### ISSUE THREAD

**Issue by arbitrary-dev** [scalameta/metals#847] opened 2019-07-30 10:51 UTC
**Describe the bug**
Unable to find workspace references for symbols from external library.

**To Reproduce**
1. Go to external library class
2. Find a symbol
3. `gr` (go to references in nvim.coc)
4. See error:
   ```
   [coc.nvim] References not found
   ```
   `:CocInfo`
   ```
   no build target: /Users/**/.metals/readonly/**/LibraryClass.scala
   ```

**Expected behavior**
References found.

**Installation:**
- Operating system: macOS
- Editor: Vim (nvim.coc)
- Metals version: v0.7.0

**Comment by tgodzik** [comment] 2019-07-30 11:30
Hi, thanks for reporting!

`no build target: /Users/**/.metals/readonly/**/LibraryClass.scala` is expected, but it should still find all references. Is there anything in `.metals/metals.log` that seems to be out of ordinary? I suspect semanticDB plugin might be misconfigured, which would show up as warnings about missing semanticDB files.

**Comment by arbitrary-dev** [comment] 2019-07-30 12:41
Nope, in `.metals/metals.log` I see only these warnings:
```
WARN  no build target: /Users/**/.metals/readonly/**/LibraryClass.scala
```

**Comment by arbitrary-dev** [comment] 2019-07-30 12:45
There were also lots of these warnings during project compilation, but I think they are unrelated to the issue:
```
WARN  unexpected dependency directory: /Users/*/.coursier/cache/v1/https/**/<unrelated_library>-sources.jar.md5.asc
```

**Comment by tgodzik** [comment] 2019-07-31 12:25
Those warnings should not have anything to with references.

Do you maybe have a some small reproduction? It would be useful to know what library class it is, what symbol this was tried on (object, class, field?) and what it should have found. There are some cases in which scalameta doesn't work properly. 

For example:
LibraryClass.scala:
```
object LibraryCla@@ss{
  def apply() = 123
}
```
WorkspaceFile.scala:
```
object Main extends App{
  println(LibraryClass())
}
```
Where @@ represents where the cursor is.

**Comment by tgodzik** [comment] 2019-08-08 17:31
@arbitrary-dev  any possible reproduction?

**Comment by arbitrary-dev** [comment] 2019-08-11 09:37
Will try…

**Comment by tgodzik** [comment] 2019-09-02 12:56
The feature works overall, so until we have any valid repro I will close this.

**Closed by tgodzik** 2019-09-02 12:56 UTC
Labels: needs more information
