### ISSUE TITLE
Unverified breakpoints as a result of naming convention

### ISSUE THREAD

**Issue by mdelomba** [scalameta/metals#3747] opened 2022-03-22 16:28 UTC
### Describe the bug

As a result of us not strictly enforcing naming conventions we have projects with different naming conventions as shown below:
LibraryProject
    subprojecta
    subProjectB
    SubProjectC

When debugging I've noticed that the only code that has verified breakpoints are the projects with all lowercase naming. The other projects will show as "Unverified Breakpoint". After renaming projects to being all lowercase, the issue seems to be resolved and I can now break into that code. 

Steps to reproduce would be:

1. Create project with anything but all lowercase naming
2. Run application
3. Attach to debug
4. Place a breakpoint
5. Breakpoint should appear with "Unverified Breakpoint"
6. Rename project to be all lowerase (I also Refresh, Compile, Import build)
7. Run Steps 2- 4
8. Breakpoint show now be verified and users can break into code.

### Expected behavior

Although projects should have some form of naming convention that all engineers abide by, all lowercase naming should not be a requirement in order to debug into code.

### Operating system

Windows

### Editor/Extension

VS Code

### Version of Metals

v0.11.1

**Comment by YeOldePorkchop** [comment] 2022-04-07 21:10
Thanks for the reply , we are currently using Windows 10.
I'll be getting a JSON file to you here shortly. The files need to be vetted before we can give them to you but the person to do that is out today.

The issue I'm seeing is when we initialize our subproject: `lazy val subProjectA = (project in file("subprojecta")). settings( name := "SubProjectA")`

The area `file("subprojecta")` appears to need to match our folder name (case sensitive) which in this case would be `subProjectA`.
We would also see this issue with `file("subProjectA")` and the folder was `subprojecta`.

This has me curious if this is actually an issue with Metals or SBT. We didn't seem to have this issue with IntelliJ but see it with VSCode.

**Comment by tgodzik** [comment] 2022-04-08 08:58
Oh, that might be related. I haven't checked it with the project names. I will take a look next week when I will have access to a Windows machine.

**Comment by YeOldePorkchop** [comment] 2022-04-08 22:18
I've created a reproduction of our project structure in: https://github.com/YeOldePorkchop/NamingConventionIssue

Attached are the dap-server.trace.json text as well as the dap-client.trace.json text.

[dap-client.txt](https://github.com/scalameta/metals/files/8455547/dap-client.txt)
[dap-server.txt](https://github.com/scalameta/metals/files/8455548/dap-server.txt)

**Comment by tgodzik** [comment] 2022-04-25 16:25
I think I know what might be going on.

> The area file("subprojecta") appears to need to match our folder name (case sensitive) which in this case would be subProjectA.
> We would also see this issue with file("subProjectA") and the folder was subprojecta.

Normally, directory names need to match exactly, but on Windows `subProjectA` is the same as `subprojecta`, while Metals will try to match exactly. This seems to be an issue in https://github.com/scalacenter/scala-debug-adapter/blob/b3d0140ef132d6de0674880e4f818347ffde1a19/core/src/main/scala/ch/epfl/scala/debugadapter/internal/SourceEntryLookUp.scala

@adpi2 any ideas on how to solve this one? Should we just change all the paths we get to lower case?

**Comment by adpi2** [comment] 2023-11-16 12:52
Fixed in [scalacenter/scaladebugadapter#615](https://github.com/scalacenter/scala-debug-adapter/pull/615)

**Closed by adpi2** 2023-11-16 12:52 UTC
Labels: bug, debug
