### ISSUE TITLE
Error starting Sbt because of error in metals.sbt (Sbt 0.13)

### ISSUE THREAD

**Issue by dragos** [scalameta/metals#504] opened 2019-01-27 12:29 UTC
**Describe the bug**

Sbt won't start in the Scala checkout

**To Reproduce**
Not sure. I changed some branches in the Scala checkout, but when I tried to start Sbt I got:

```
 $ sbt
/Users/dragos/.sbt/0.13/plugins/metals.sbt:12: error: not found: value pluginCrossBuild
    val sbtVersion = Keys.sbtBinaryVersion.in(pluginCrossBuild).value
                                              ^
[error] Type error in expression
```

I had to delete `metals.sbt` in the global Sbt 0.13 directory to make progress.

**Comment by gabro** [comment] 2019-01-27 13:09
This is likely due to an older version of sbt than metals supports. Metals works from 0.13.16 on, can you confirm which version are you using?

**Comment by gabro** [comment] 2019-01-27 13:36
0.13.7, actually. However this was addressed in https://github.com/scalameta/metals/pull/43, so it might actually be something else... 🤔

**Comment by dragos** [comment] 2019-01-27 13:51
It's `0.13.13`. It's part of the Scala build, and since we're supporting 10 Scala versions, we have to live with old versions of everything. Not a big deal, I can delete metals.sbt from time to time, but I thought you should be aware.

**Comment by gabro** [comment] 2019-01-27 14:30
> I thought you should be aware.

Definitely! Thanks for reporting, indeed we shouldn't try to load an incompatible sbt plugin if we know the version. Which branch it is? I would like to take a look and reproduce to see why the fix I've added in #434 isn't working.

**Comment by gabro** [comment] 2019-01-27 14:43
Ah, I think I know why.

We skip writing the `metals.sbt` file if the Sbt version is not compatible, but if you change Sbt version after the fact, the plugin file will be loaded by an incompatible version of Sbt and at that point it's already too late.

One possible solution would be to actively delete the file if the sbt version is not compatible, instead of just skipping to write it.

**Comment by olafurpg** [comment] 2019-01-27 15:46
Thanks for reporting! A workaround is to upgrade to sbt 0.13.17 where the `pluginCrossBuild` task was introduced. I opened #505, which makes the generated `metals.sbt` file compile on older sbt 0.13 versions but crash at runtime when the environment variable `METALS_ENABLED=true`.

**Closed** 2019-01-27 16:04 UTC
Labels: bug

**Comment by dragos** [comment] 2019-01-28 08:21
I can't upgrade, at least not easily, since this happens on the scala/scala repo when building an older version (we're unique in that, since we support 3-year old Scala versions :D).

**Comment by olafurpg** [comment] 2019-01-28 08:23
Fair enough, the generated metals.sbt should at least compile with 0.13.13 now.
