### ISSUE TITLE
Range `encloses`: endLine and endCharacter logic

### ISSUE THREAD

**Issue by myFree** [scalameta/metals#718] opened 2019-05-11 10:29 UTC
**Describe the bug**
Not sure if I'm misunderstanding what encloses is checking for - but if the range.endLine > other.endLine; isn't the endCharacter moot?

**To Reproduce**
range = Range(7,2,14,3)
other = Range(7,6,7,23)

**Expected behavior**
I would think that `range` encloses `other` here; as range ends 7 lines after `other` does

**Screenshots**
![Selection_999(927)](https://user-images.githubusercontent.com/476578/57568486-5bb97b00-73e8-11e9-9100-cf589889cb4f.png)

**Installation:**
n/a

**Comment by olafurpg** [comment] 2019-05-11 10:43
Thanks for reporting! Can you please include an example where the current behavior for end users does not work as expected? For example, goto definition

**Comment by myFree** [comment] 2019-05-11 11:05
I'm playing around in the code - so I came across it with it via a probably slightly weird scenario; which was trying to find the `scala.meta.Tree` which is the body of a function from a known `scala.meta.tokens.Token`

So; the `other` range comes from the token; and if it is encompassed by a `scala.meta.Tree` range; then I know I'm getting close.

(I'll probably ask in Gitter if I can't clean up my lookup approach; but for now I'm ok stubbing my toes in the interest of a voyage of possible discover)

**Comment by olafurpg** [comment] 2019-05-11 11:18
Can you provide a reproduction where the current behavior causes a user experience issue when editing code with Metals?

**Comment by myFree** [comment] 2019-05-11 11:22
Seems like its only used in a test; so I would guess it doesn't have a Metals end user impact

![Selection_999(928)](https://user-images.githubusercontent.com/476578/57569018-c5895300-73ef-11e9-9479-d5369addbc51.png)

(The other 2 usages is in I wrote)

**Comment by olafurpg** [comment] 2019-05-22 08:55
Closing with "working as intended", this method is only used in tests for a specific purpose. @myFree feel free to open a new issue if you can reproduce a user-facing issue such as "goto definition doesn't work in situation XXX".

I've added a note in #672 to move the `encloses` method out of `MtagsEnrichments` into our test modules.

**Closed by olafurpg** 2019-05-22 08:55 UTC
