### ISSUE TITLE
Go to definition / hover revert to enclosing tree if cursor is not on a symbol

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1707] opened 2020-05-06 17:18 UTC
**Describe the bug**

I Scala 3 in code like:
```scala
class A {
  
  def foo() = {
    // this is a comment
  }
}
```

**To Reproduce**
1. use go to definition on the comment
2. Metals will go to foo.

**Expected behavior**
Nothing happens.

**Installation:**
- Operating system: macOS/Windows/Linux
- Editor: Visual Studio Code/Atom/Vim/Sublime/Emacs
- Metals version: v0.9.0

**Additional context**
This is most likely due to compiler behavior when faced with a non-existing symbol position.

**Search terms**
scala3 go to definition

**Comment by olafurpg** [comment] 2020-05-06 18:22
Thank you for reporting! I think this is caused by using "find closest tree enclosing position" without validating that the position points to an identifier.

**Comment by gabro** [comment] 2020-09-25 19:43
Took a quick look at this, and I think it's a bug in the dotty pc.

Specifically `enclosingSourceSymbol` (used by `findDefinitions`) defaults to `List(enclosingTree(path).symbol` for anything that is not explicitly handled.

https://github.com/lampepfl/dotty/blob/89f42f41b3be797ff18f2d12b806a6b8925b383b/compiler/src/dotty/tools/dotc/interactive/Interactive.scala#L101-L136

It would probably make sense to prevent the default behavior on trees that do not represent identifiers

**Comment by tanishiking** [comment] 2022-04-22 08:34
This issue is fixed by the following PRs
https://github.com/scalameta/metals/pull/3792
https://github.com/scalameta/metals/pull/3807

**Closed by tanishiking** 2022-04-22 08:34 UTC
Labels: bug, Scala 3, presentation-compiler
