### ISSUE TITLE
Can't start debugee on Windows

### ISSUE THREAD

**Issue by tgodzik** [scalameta/metals#1021] opened 2019-10-27 18:36 UTC
**Describe the bug**
When running/testing on linux everything hangs and after a while message pops up "Can't start debugee"

**To Reproduce**
1. Install VS Code on Windows.
2. Create a test or main class.
3. Try to run it using code lenses.
4. See error:

```
INFO  Starting debug proxy for [tests.DocumentHighlightLspSuite]
ERROR Unexpected error during remote test execution: 'socket closed'.
INFO  Canceling debug proxy for [tests.DocumentHighlightLspSuite]
INFO  Listening for transport dt_socket at address: 52284
```

**Expected behavior**
The main/test method should be run.

**Screenshots**

![image](https://user-images.githubusercontent.com/3807253/67639518-ce63d780-f8f0-11e9-8d13-d21287b04c44.png)

**Installation:**
- Operating system: Windows
- Editor: Visual Studio Code
- Metals version: 0.7.6+164-4d32f232-SNAPSHOT

**Search terms**
windows run test

**Comment by tgodzik** [comment] 2019-10-27 19:21
@marek1840 We can try to fix this tomorrow - I should have Windows on my machine at work.

**Comment by marek1840** [comment] 2019-11-06 16:35
The root cause was that bloop was unable to detect the JDI notification on Windows. With https://github.com/scalacenter/bloop/pull/1073 being merged, the problem should disappear once new version of bloop (1.3.6?) is released.

**Comment by olafurpg** [comment] 2019-11-11 04:10
Closing since the PR has been merged in Bloop. Thank you for fixing the issue @marek1840 !

**Closed by olafurpg** 2019-11-11 04:10 UTC
Labels: bug, debug-adapter-protocol
