### ISSUE TITLE
“Insert type annotation” wrongly infers `Any` type

### ISSUE THREAD

**Issue by mberndt123** [scalameta/metals#6412] opened 2024-05-16 22:04 UTC
### Describe the bug

1. Clone this repo: https://github.com/zio/zio-http/
2. check out commit ade9245c (current `main` as of this writing)
3. open the project using VS Code, import project (bloop or sbt, doesn't matter)
4. Remove the type annotation from `val live` in `object NettyClientDriver`, save file
5. use the _insert type annotation_ feature to add the type annotation again

Metals will infer `Any` instead of the correct type

### Expected behavior

The inferred type should be  `ZLayer[NettyConfig, Nothing, NettyClientDriver]`

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v1.3.1

**Comment by mberndt123** [comment] 2024-05-16 22:47
Another issue is:

In the same file, go to line 89. Position the cursor on line 89 between the leading dot and the word `customHeaders`. Trigger code completion -> works fine, you get all the right methods.

Move the cursor to line 90 between the leading dot and the word `webSocketUri`. Trigger code completion -> You only get junk.

**Comment by tgodzik** [comment] 2024-05-17 07:56
Looking into the project it seems that for both Bloop and sbt BSP it's failing. The weirdest thing is that the presentation compiler seems to be sending us errors all around :thinking:

**Comment by mberndt123** [comment] 2024-05-17 10:40
It looks mostly fine in the Metals doctor though 🤷🏻‍♂️
![doctor](https://github.com/scalameta/metals/assets/11650737/8779ecca-10dd-465b-935f-e6fcb869e9af)
Perhaps it is somehow related to the sbt-projectmatrix plugin?

**Comment by tgodzik** [comment] 2024-12-31 14:46
Finally, going back to the issue I see a lot of:
```
[error] zio.http.netty.client.NettyClientDriver.requestWebsocket(file:///home/tgodzik/Documents/metals/tests/unit/target/e2e/community/zio/zio-http/jvm/src/main/scala/zio/http/netty/client/NettyClientDriver.scala:129)
[error]  
[error]  No automatically generated traces are permitted here. Add an implicit parameter
[error]  to pass through a user generated trace or explicitly call `newTrace`
[error]  to force generation of a new trace.
[error]  
[error]  copy/paste:
[error]    (implicit trace: Trace)  <- no existing implicit parameter list
[error]    , trace: Trace           <- existing implicit parameter list
[error]    (newTrace)                       <- I know what I'm doing, generate a new trace anyway
[error]    
```
and anything that takes in trace as a parameter fails.

**Comment by tgodzik** [comment] 2024-12-31 14:50
Yep, looks like if I remove `import zio.stacktracer.TracingImplicits.disableAutoTrace` everything works :O

**Comment by tgodzik** [comment] 2024-12-31 15:00
Looks like it also works with ` implicit val trace: Tracer.instance.Type with Tracer.Traced = Trace.empty` it doesn't like the alias

**Comment by tgodzik** [comment] 2024-12-31 15:09
Turns out this is a duplicate of https://github.com/scalameta/metals/issues/4495 which is caused itself by https://github.com/scala/bug/issues/12663

If you are in any other package than zio this will be fine.

**Closed by tgodzik** 2024-12-31 15:09 UTC
Labels: bug, presentation-compiler, Scala 2
