### ISSUE TITLE
ubuntu ecryptfs home + bloop 1.5.4 keeps recompiling all files,  regression since 1.5.3-6-13310fda

### ISSUE THREAD

**Issue by silles79** [scalameta/metals#4623] opened 2022-11-08 16:36 UTC
### Describe the bug

This is not going to be easy to reproduce, since i cannot share the project, it's not mine.

and it's is a massive project, which takes ages to compile.

since upgrading metals to version 0.11.9 I noticed it keeps recompiling almost every files all the time.

if u use bloop 1.5.3 - i forced the version in vcode.
and touch a test file, top level file, nothing depends on it:
2022.11.08 17:17:15 INFO  compiling test (1 scala source)
2022.11.08 17:17:22 INFO  time: compiled test in 6.5s

if i use the recommended bloop version 1.5.4:
same file touched
2022.11.08 17:17:27 INFO  compiling test (215 scala sources and 2 java sources)
2022.11.08 17:24:27 INFO  time: compiled test in 7m0s
all the test files forced to recompile.

I tried to do a clean compile, wipe all .bloop folder etc.

Something is not ok with bloop 1.5.4 integration.

### Expected behavior

only recompile files need

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment] 2022-11-08 16:51
Thanks for reporting! Are you able to run Bloop cli with `bloop compile --verbose <project_name>` ? It should say a bit more about what is going on. Anything specific that the project uses?  Could you also check out the latest Bloop version `1.5.4-14-7cb43276`?

Does it happen also when using sbt BSP or normally via your build tool CLI?

**Comment by tgodzik** [comment] 2022-11-08 16:52
A minimal reproduction or even just any reproduction would help a lot here.

**Comment by silles79** [comment] 2022-11-08 17:17
just tried 1.5.4-14-7cb43276
when opened the project with that version:
2022.11.08 17:58:42 INFO  Connected to Build server: Bloop v1.5.4-14-7cb43276
2022.11.08 17:58:42 INFO  time: Imported build in 0.35s
2022.11.08 17:58:47 INFO  time: indexed workspace in 4.54s
2022.11.08 17:58:50 INFO  compiling test (215 scala sources and 2 java sources)
2022.11.08 18:05:14 INFO  time: compiled test in 6m23s

put a println into the test:
2022.11.08 18:13:28 INFO  compiling test (1 scala source)
2022.11.08 18:13:36 INFO  time: compiled test in 7.78s

clicked on run tests:
2022.11.08 18:13:41 INFO  compiling test (215 scala sources and 2 java sources)

think the recompile madness happens when trying to run the test.

I ran the tests with 1.5.3 no recompile.

**Comment by silles79** [comment] 2022-11-09 08:21
I installed bloop cli
first compile:
[bloop-compile.txt](https://github.com/scalameta/metals/files/9968856/bloop-compile.txt)

used vim to edit a test:
second compile:
[bloop-compile-2.txt](https://github.com/scalameta/metals/files/9968888/bloop-compile-2.txt)

only recompiled 1 file.
so no problems when using cli 

think the constant full recompile happens when using metals+vcode.

**Comment by silles79** [comment] 2022-11-09 08:44
This is what happens when using vcode:
Load project:

Java home: /home/user/opt/graalvm
Metals version: 0.11.9
2022.11.09 09:28:01 INFO  logging to file /home/user/projects-ja/abc-scale-up/.metals/metals.log
2022.11.09 09:28:01 INFO  Started: Metals version 0.11.9 in workspace '/home/user/projects-ja/abc-scale-up' for client Visual Studio Code 1.73.0.
2022.11.09 09:28:01 INFO  Flyway Community Edition 9.4.0 by Redgate
2022.11.09 09:28:01 INFO  See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.4.0
2022.11.09 09:28:01 INFO  
2022.11.09 09:28:01 INFO  Database: jdbc:h2:file:/home/user/projects-ja/abc-scale-up/.metals/metals (H2 2.1)
2022.11.09 09:28:01 INFO  Successfully validated 4 migrations (execution time 00:00.014s)
2022.11.09 09:28:01 INFO  Current version of schema "PUBLIC": 4
2022.11.09 09:28:01 INFO  Schema "PUBLIC" is up to date. No migration necessary.
2022.11.09 09:28:02 INFO  time: initialize in 1.2s
Initializing Scala Debugger
Release notes was not shown: not showing release notes since they've already been seen for your current version
2022.11.09 09:28:03 INFO  Attempting to connect to the build server...
2022.11.09 09:28:03 INFO  Bloop uses /home/user/opt/graalvm defined at /home/user/.bloop/bloop.json
2022.11.09 09:28:03 INFO  Bloop currently uses settings: -Xmx4G,-XX:MetaspaceSize=4G
2022.11.09 09:28:03 INFO  skipping build import with status 'Installed'
2022.11.09 09:28:07 INFO  no build target found for /home/user/projects-ja/abc-scale-up/rax/src/test/scala/uk/co/ja/rax/test/PublicBranchesAddProductsTest.scala. Using presentation compiler with project's scala-library version: 3.2.0
2022.11.09 09:28:09 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/user/projects-ja/abc-scale-up/.metals/bsp.trace.json or /home/user/.cache/metals/bsp.trace.json
2022.11.09 09:28:09 INFO  Attempting to connect to the build server...
2022.11.09 09:28:09 INFO  Bloop uses /home/user/opt/graalvm defined at /home/user/.bloop/bloop.json
2022.11.09 09:28:09 INFO  Bloop currently uses settings: -Xmx4G,-XX:MetaspaceSize=4G
2022.11.09 09:28:09 INFO  Attempting to connect to the build server...
2022.11.09 09:28:09 INFO  Bloop uses /home/user/opt/graalvm defined at /home/user/.bloop/bloop.json
2022.11.09 09:28:09 INFO  Bloop currently uses settings: -Xmx4G,-XX:MetaspaceSize=4G
2022.11.09 09:28:09 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/user/projects-ja/abc-scale-up/project/project/.metals/bsp.trace.json or /home/user/.cache/metals/bsp.trace.json
2022.11.09 09:28:09 INFO  tracing is disabled for protocol BSP, to enable tracing of incoming and outgoing JSON messages create an empty file at /home/user/projects-ja/abc-scale-up/project/.metals/bsp.trace.json or /home/user/.cache/metals/bsp.trace.json
2022.11.09 09:28:09 INFO  time: Connected to build server in 6.02s
2022.11.09 09:28:09 INFO  Connected to Build server: Bloop v1.5.4
2022.11.09 09:28:10 INFO  time: code lens generation in 5.25s
2022.11.09 09:28:10 INFO  time: Imported build in 0.65s
2022.11.09 09:28:18 INFO  time: indexed workspace in 8.4s
2022.11.09 09:28:23 INFO  compiling rax-test (215 scala sources and 2 java sources)
2022.11.09 09:35:30 INFO  time: compiled rax-test in 7m7s

All compiled, add println to test and save:
2022.11.09 09:35:51 INFO  compiling rax-test (1 scala source)
2022.11.09 09:35:59 INFO  time: compiled rax-test in 7.87s

All compiled, add 1 more println to test and save:
2022.11.09 09:36:04 WARN  Could not load snapshot text for /home/user/projects-ja/abc-scale-up/rax/src/test/scala/uk/co/ja/rax/test/PublicBranchesAddProductsTest.scala
2022.11.09 09:36:05 INFO  compiling rax-test (215 scala sources and 2 java sources)
2022.11.09 09:43:03 INFO  time: compiled rax-test in 6m57s
and recompiles everything !

add more println:
2022.11.09 09:43:45 INFO  compiling rax-test (1 scala source)
2022.11.09 09:43:52 INFO  time: compiled rax-test in 7.34s

**Comment by silles79** [comment] 2022-11-09 09:10
just tried multiple edits from vim/cli and got the same issue with 1.5.4
I guess it's an bloop issue than 
Shall I close this one and open one in bloop ?

**Comment by tgodzik** [comment] 2022-11-09 09:18
It's fine to leave it here, it's something we need to deal with anyway.

Are you able to create /home/user/projects-ja/abc-scale-up/project/project/.metals/bsp.trace.json file and send it later?

So the full recompile happens randomly, not only after running test? And it never happens on CLI?

**Comment by silles79** [comment] 2022-11-09 09:31
yes it does happen randomly for no reason. I'm making the same change to the same file.
I does happen as well when using CLI only, editing with VIM . so not using metal at all !!!

that's why I thought this should be an issue in bloop and report it there?

**Comment by tgodzik** [comment] 2022-11-09 09:34
We can move it for sure then. If you manage to run `bloop compile --verbose <name_project>` it should actually say why it's recompiling and what was invalidated.

**Comment by silles79** [comment] 2022-11-09 09:38
i have posted the verbose output above: see here
https://github.com/scalameta/metals/issues/4623#issuecomment-1308379433

**Comment by silles79** [comment] 2022-11-09 09:42
Here is an other one:
----------------------------------------------------------------------------------------
Inital compile:
user@xps8930:~/projects-ja/abc-scale-up$ bloop compile --verbose  rax-test

[D] Elapsed: 416257.810264 ms
user@xps8930:~/projects-ja/abc-scale-up$ 
----------------------------------------------------------------------------------------
2nd recompile:
user@xps8930:~/projects-ja/abc-scale-up$ bloop compile --verbose  rax-test

[D] Elapsed: 1064.883415 ms
----------------------------------------------------------------------------------------
touch file and recompile:
user@xps8930:~/projects-ja/abc-scale-up$ touch rax/src/test/scala/uk/co/ja/rax/test/PublicBranchesAddProductsTest.scala
user@xps8930:~/projects-ja/abc-scale-up$ bloop compile --verbose  rax-test
[D] Elapsed: 1060.052142 ms

----------------------------------------------------------------------------------------

Add println to test
user@xps8930:~/projects-ja/abc-scale-up$ vim rax/src/test/scala/uk/co/ja/rax/test/PublicBranchesAddProductsTest.scala
user@xps8930:~/projects-ja/abc-scale-up$ bloop compile --verbose  rax-test

[D] Elapsed: 6581.751463 ms

----------------------------------------------------------------------------------------
add 1 more println to same test, triggers full recompile:
user@xps8930:~/projects-ja/abc-scale-up$ vim rax/src/test/scala/uk/co/ja/rax/test/PublicBranchesAddProductsTest.scala
user@xps8930:~/projects-ja/abc-scale-up$ bloop compile --verbose  rax-test
[D] Elapsed: 401073.854179 ms

**Comment by tgodzik** [comment] 2022-11-09 09:51
Ach sorry! I missed that! Still waking up :sweat_smile:

**Comment by tgodzik** [comment] 2022-11-09 09:53
The weirdest thing is:
```
Initial directly invalidated classes: Set(uk.co.ja.rax.test.PublicBranchesAddProductsTest)
Sources indirectly invalidated by:
	product: Set(/home/user/projects-ja/abc-scale-up/rax/src/test/scala/uk/co/ja/rax/test/BankHolidaysRouterTest.scala,
```
looks like Zinc is detecting that all those files depend on the changed one, which makes no sense :thinking:

**Comment by silles79** [comment] 2022-11-09 09:57
yeah makes no sense. just downgraded and repeated the same exercise with 1.5.3:
[bloop-1.5.3.txt](https://github.com/scalameta/metals/files/9969699/bloop-1.5.3.txt)

no issue at all.  only compiles the 1 test file. this is the expected behavior

**Comment by tgodzik** [comment] 2022-11-09 10:04
We could potentially go through the snapshot versions of Bloop to see which change could have caused it if you have time.

Could be done in a binary search manner from the list here:
```
1.5.3-2-117b7e05
1.5.3-4-b5cf7cc4
1.5.3-6-13310fda 
1.5.3-8-c47dcb02
1.5.3-10-7ff53684
1.5.3-12-a0ca82de    
1.5.3-16-8f18368b      
1.5.3-26-ee0b253d
1.5.3-28-373a64c9    
1.5.3-30-31ba8b4b
1.5.3-35-c51f8d96      
1.5.3-38-586cfbff
1.5.3-40-0bd25506  
1.5.3-42-75a0d6ee
1.5.3-44-03658369  
1.5.3-54-ed1f9c82    
1.5.3-56-8630f73c    
1.5.3-58-678864a0
1.5.3-60-3de5fb9f   
1.5.3-62-2093ddd1  
1.5.3-65-72f9449a 
1.5.3-67-6c91b225
```

**Comment by dos65** [comment] 2022-11-09 11:38
@tgodzik I would look at that this line - https://github.com/scalacenter/bloop/pull/1772/files#diff-ca589194cc6d81468ca76060c24cdad979a401e21525c86edf7229a8115ab4e5R187 .

In case which @silles79 describes, there shouldn't be any removed product from analysis, so then we calculate them in `getOrElse`. Maybe we need to use `equivS` with some different parameters ([a bit above](https://github.com/scalacenter/bloop/pull/1772/files#diff-ca589194cc6d81468ca76060c24cdad979a401e21525c86edf7229a8115ab4e5R174-R178) it's used with some `BloopStamps`)

**Comment by tgodzik** [comment] 2022-11-09 12:08
Why do we actually need to do `.getOrElse` ? Shouldn't the removedProducts from Zinc be enough?

**Comment by silles79** [comment] 2022-11-09 12:21
Simple project as this:

bloop-issue/
bloop-issue/src/
bloop-issue/src/test/
bloop-issue/src/test/resources/
bloop-issue/src/test/scala/
bloop-issue/src/test/scala/TestA.scala
bloop-issue/src/test/scala/TestB.scala
bloop-issue/src/main/
bloop-issue/src/main/resources/
bloop-issue/src/main/scala/
bloop-issue/.gitignore
bloop-issue/build.sbt

Keep editing TestB:

2022.11.09 13:19:48 INFO  Connected to Build server: Bloop v1.5.4
2022.11.09 13:19:52 INFO  time: indexed workspace in 4s
2022.11.09 13:19:52 INFO  compiling bloop-issue-test (2 scala sources)
2022.11.09 13:19:53 INFO  time: compiled bloop-issue-test in 1.04s
2022.11.09 13:19:56 INFO  compiling bloop-issue-test (1 scala source)
2022.11.09 13:19:56 INFO  time: compiled bloop-issue-test in 0.41s
2022.11.09 13:20:03 INFO  compiling bloop-issue-test (2 scala sources)
2022.11.09 13:20:03 INFO  time: compiled bloop-issue-test in 0.47s

attached the src:

[src.tar.gz](https://github.com/scalameta/metals/files/9970909/src.tar.gz)

**Comment by dos65** [comment] 2022-11-09 12:35
@tgodzik 
> Why do we actually need to do .getOrElse ? Shouldn't the removedProducts from Zinc be enough? 

It's one to one prot from Zinc.
There was an issue that by some reason a classfile was deleted but not reflected in analysis. I haven't the source of that but this solution helps to avoid it. Also, if classfile directory was touched externally bloop should detect that

**Comment by dos65** [comment] 2022-11-23 19:40
> attached the src:

[src.tar.gz](https://github.com/scalameta/metals/files/9970909/src.tar.gz)

Hmm. I couldn't reproduce this issue (Linux / Metals 0.11.9 / Bloop 1.5.4)

@silles79 btw which VSCode version do you use? Maybe the editor somehow leads to this issue. Also, could you try to disable all other plugins except of Metals to be sure that the issue is in Metals itself.

**Comment by silles79** [comment] 2022-11-23 20:56
@dos65 1.73.1 but the issue is with bloop, nothing to do with metals (most likely)

same thing happens with vim + bloop 1.5.4 + compile with CLI.

I'm using Ubuntu 22.04.1and my home is encrypted with ecryptfs.

just remembered I used to have issue with sbt and long filenames while using ecryptfs...
had to add something like scalacOptions ++= Seq("-Xmax-classfile-name","200") to make things work.

could it be a similar issue?

**Comment by silles79** [comment] 2022-11-23 21:17
ok this is weird. I tried my old laptop, same ubuntu, same java, same bloop, same vcode and the same project, same encrypted fs 
all good. no issues:
DELL XPS 9360:
2022.11.23 21:59:46 INFO  Connected to Build server: Bloop v1.5.4
2022.11.23 21:59:46 INFO  time: Imported build in 0.18s
2022.11.23 21:59:53 INFO  time: indexed workspace in 7.14s
2022.11.23 22:00:01 INFO  compiling bloop-issue-test (2 scala sources) <- first compile 
2022.11.23 22:00:08 INFO  time: compiled bloop-issue-test in 6.76s
2022.11.23 22:00:18 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:00:19 INFO  time: compiled bloop-issue-test in 1.12s
2022.11.23 22:00:22 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:00:24 INFO  time: compiled bloop-issue-test in 1.56s
2022.11.23 22:00:27 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:00:28 INFO  time: compiled bloop-issue-test in 1.43s
2022.11.23 22:00:32 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:00:34 INFO  time: compiled bloop-issue-test in 1.36s
2022.11.23 22:00:35 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:00:37 INFO  time: compiled bloop-issue-test in 1.35s
2022.11.23 22:01:38 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:01:40 INFO  time: compiled bloop-issue-test in 1.43s
2022.11.23 22:01:43 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:01:44 INFO  time: compiled bloop-issue-test in 1.07s
2022.11.23 22:02:08 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:02:09 INFO  time: compiled bloop-issue-test in 1.29s
2022.11.23 22:02:50 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:02:51 INFO  time: compiled bloop-issue-test in 1.33s

I tried again on my main desktop and it keeps:
DELL XPS 8930 
2022.11.23 22:05:45 INFO  Connected to Build server: Bloop v1.5.4
2022.11.23 22:05:46 INFO  time: indexed workspace in 1.22s
2022.11.23 22:05:47 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:05:49 INFO  time: compiled bloop-issue-test in 2.5s
2022.11.23 22:05:56 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:05:56 INFO  time: compiled bloop-issue-test in 0.7s
2022.11.23 22:05:58 INFO  compiling bloop-issue-test (2 scala sources)
2022.11.23 22:05:58 INFO  time: compiled bloop-issue-test in 0.77s

downgrade 1.5.3
2022.11.23 22:15:09 INFO  Connected to Build server: Bloop v1.5.3
2022.11.23 22:15:10 INFO  time: indexed workspace in 1s
2022.11.23 22:15:17 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:15:19 INFO  time: compiled bloop-issue-test in 2.57s
2022.11.23 22:15:20 WARN  Could not load snapshot text for /home/silles/projects/bloop-issue/src/test/scala/TestB.scala
2022.11.23 22:15:27 WARN  Could not load snapshot text for /home/silles/projects/bloop-issue/src/test/scala/TestB.scala
2022.11.23 22:15:27 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:15:27 INFO  time: compiled bloop-issue-test in 0.72s
2022.11.23 22:15:32 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:15:32 INFO  time: compiled bloop-issue-test in 0.64s
2022.11.23 22:15:35 INFO  compiling bloop-issue-test (1 scala source)
2022.11.23 22:15:35 INFO  time: compiled bloop-issue-test in 0.56s

all good on the XPS 8930

something is screwed on my xps 8930 + 1.5.4. not sure what ...

**Comment by silles79** [comment] 2022-11-24 08:53
today managed to break it on my laptop as well (xps13)
it went something like:
1. after fresh boot:
2. rm -rf .bloop/ .metals/ .vscode/ project/ target/
3. start vcode etc, import mini project.
4. added like 10 println() into TestB
5. keep deleting them 1 by 1 and press save.
6. was all good. than clicked on clean compile workspace.
7. after full recompile repeat from 4... than it break

not 100% sure how to reproduce it. sometimes it just works for a while, until some combination of 
restart server || clean compile || random edit and save just breaks the workspace.

is there any other logs to look for other than .metal.logs?

**Comment by silles79** [comment] 2022-11-24 09:25
100% sure it's ecryptfs  (only my home is encrypted )+ bloop 1.5.4 @tgodzik @dos65 

moved the project to /tmp and no issue at all.

**Comment by tgodzik** [comment] 2022-11-24 09:33
Thanks for the investigation! My guess now is that previously, we would not remove the products, which meant no compilation needed, but also leftover classfiles etc. But since we use last modified for the product stamps this might cause issues with encryption since it will modify the last modified time.

I wonder if we can do better than last modified and at the same time not cause serious performance bottlenecks.

**Comment by dos65** [comment] 2022-11-24 10:04
@silles79 Maybe I missed something in this thread. Have you already compared this behaviour with sbt? In theory, it either should happen in sbt too or I incorrectly ported code from zinc

**Comment by silles79** [comment] 2022-11-24 10:17
just tried with sbt.version=1.8.0 .... no issues noticed. just compiles 1 file all the time

**Comment by silles79** [comment] 2022-11-24 10:22
1. just started sbt from cmd line
2. edited TestB with vim, save.
3. test:compile.
4. repeated 20 times. no issues

**Comment by tgodzik** [comment] 2022-11-24 10:33
You could try switching to BSP sbt server `Metals: Switch BSP server` command and see if this can get reproduced with pure sbt.

It's a bit different from CLI I think. I will take a look to see what is the difference and if any with the hashes used by sbt.

**Comment by silles79** [comment] 2022-11-24 10:37
yep. i was just doing that. no issues to report. vcode+metal+sbt+bsp:

2022.11.24 11:35:06 INFO  compiling 1 Scala source to /home/silles/Downloads/bloop-issue/target/scala-2.13/test-classes ...
2022.11.24 11:35:08 INFO  done compiling
2022.11.24 11:35:08 INFO  time: compiled bloop-issue-test in 1.26s
2022.11.24 11:35:08 INFO  Processing buildTarget/scalaTestClasses
2022.11.24 11:35:08 INFO  compiling bloop-issue
2022.11.24 11:35:08 INFO  time: compiled bloop-issue in 3ms
2022.11.24 11:35:08 INFO  compiling bloop-issue-test
2022.11.24 11:35:08 INFO  time: compiled bloop-issue-test in 5ms
2022.11.24 11:35:08 INFO  Processing buildTarget/scalaMainClasses
2022.11.24 11:35:08 INFO  compiling bloop-issue
2022.11.24 11:35:08 INFO  time: compiled bloop-issue in 5ms
2022.11.24 11:35:08 INFO  compiling bloop-issue-test
2022.11.24 11:35:08 INFO  time: compiled bloop-issue-test in 7ms

repeated 20-30 times. no problems.

**Comment by tgodzik** [comment] 2022-11-24 10:38
Ok, I see there is a workaround we could also use for Bloop https://github.com/sbt/sbt/commit/7ba5fd79f8857b87bd86736cdeefbc04d97e3350

**Comment by silles79** [comment] 2022-11-28 09:43
1.5.4-67-c910a45b so far so good, haven't noticed any unnecessary recompiles :+1:

**Comment by tgodzik** [comment] 2022-11-28 10:03
Thanks! I will close this if we don't find any issues within a week.

**Closed** 2022-12-02 15:53 UTC
Labels: bug
