### ISSUE TITLE
missing completion item for case class defined in a different scope

### ISSUE THREAD

**Issue by ivanopagano** [scalameta/metals#649] opened 2019-04-11 13:11 UTC
**Describe the bug**
Auto-completion won't suggest an existing case class type to auto-import, even with a complete name match.

In addition the auto-completer suggests similar names defined in the same scope as the missing one.

**To Reproduce**
[Edited]
The simple case had other issues, and once those are correctly managed, the case is not representative anymore.

In the end the issue seems to be related to a more complex interaction scenario

~define two files with:~

~An object and two case classes~

~A trait trying to define a variable with the same case class in the object previously defined, in another package~

**Expected behavior**
I would expect the completion to suggest importing the `AClass` defined, just as it does if doing it from the same scope

**Screenshots**
![image](https://user-images.githubusercontent.com/1067461/55959401-f77d8d00-5c6a-11e9-9e1d-396e396eb3ed.png)

![image](https://user-images.githubusercontent.com/1067461/55959485-2d227600-5c6b-11e9-815c-1cc8cba55fee.png)

**Installation:**
- Operating system: macOS
- Editor: Visual Studio Code
- Metals version: v0.5.0-M1

**Additional context**
On a bigger project, where the object in the first source contained many different case classes of similar prefix as the one needed, the completer would suggest other correct auto-imported alternatives, but not the exact match, as shown here

![image](https://user-images.githubusercontent.com/1067461/55959805-cbaed700-5c6b-11e9-9f46-244c1121b620.png)

The `Block` case class is defined in the same `TezosTypes` scope object as the proposed alternatives, like `BlockData` and `BlockHash`, yet it doesn't show up

**Search terms**
auto-completion
missing

**Comment by olafurpg** [comment] 2019-04-11 13:27
Thanks for reporting! Has the separate file been compiled? It’s a known limitation that we don’t complete recently edited symbols from separate files without a successful compilation in the build. I’m afraid this will remain the expected behavior until somebody solves cheap outlining.

**Comment by ivanopagano** [comment] 2019-04-11 13:29
I will check for that.

In any case, _my reproducible error won't work_, I figured out I didn't put the sources inside the `src/main/scala` source path, so nothing was working correctly.

Probably I can't reproduce

**Comment by ivanopagano** [comment] 2019-04-11 13:31
While the simplified cases now work correctly, I checked with the last example, from real project, and it won't correctly pick up the `Block` item, even if previously compiled correctly.

**Comment by olafurpg** [comment] 2019-04-11 13:35
Completions for recently changed symbols in separate files without successful build compilation may occasionally work by accident but that functionality is not officially supported. It’s best to save frequently and try to keep the sources compiling successfully as much as possible. I admit this workflow is unusual if you’re used to IntelliJ but my personal experience for the past two weeks is that it’s not so terrible.

**Comment by olafurpg** [comment] 2019-04-11 13:37
Does it appear as a completion if you manually import it first?

**Comment by ivanopagano** [comment] 2019-04-11 14:25
> Does it appear as a completion if you manually import it first?

Yep

**Comment by ivanopagano** [comment] 2019-04-11 14:26
Well, to be honest, I save quite constantly, so I wouldn't expect that to be an issue... yet I have no way to reproduce faithfully.

I'm so ingrained in auto-save, that I do it second nature even on the wrong context... 
(save on a browser page, save on sublime-merge... which actually stashes the changes!! 😂 ...)

**Comment by olafurpg** [comment] 2019-04-12 08:01
Hmm, if the symbol appears with an explicit import then it sounds like a bug. The auto-import is powered by our own in-memory indexes that we update on file save but also requires the corresponding classfiles to be available in the target directory so the compiler can pick them up.

**Comment by olafurpg** [comment] 2019-04-15 07:37
Please reopen if you are able to reproduce a case where

- project is successfully compiled
- missing auto-import completion
- manual import + scope completion works

The situation below is a known limitation and is unlikely to get fixed in the near future:

1. project successfully compiles
2. open file `B.scala` and add new method/class without saving + compiling successfully in the build
3. open `A.scala` in the same project and try to complete the new method/class from `B.scala`

The completion in step 3 may occasionally work by accident but it's not expected behavior. This limitation is due to the fact that Metals
- restarts the presentation compiler frequently in order to provide a reliable experience for long-running coding sessions
- doesn't typecheck full source files with the presentation compiler in order to speed up response times for completions/hover/...

**Closed by olafurpg** 2019-04-15 07:37 UTC
