### ISSUE TITLE
Cannot open sources jar of artifact containing `+` in its version number

### ISSUE THREAD

**Issue by adpi2** [scalameta/metals#4570] opened 2022-10-25 09:22 UTC
### Describe the bug

1. Create an sbt build containing:
```scala
libraryDependencies += "ch.epfl.scala" % "com-microsoft-java-debug-core" % "0.34.0+9"
```
2. Import the build in Metals
3. Go to Symbol `IEvaluationProvider` (it's a class in `com-microsoft-java-debug-core`)

Metals fails to open the source file in the sources jar. Instead it prints:
```
/home/piquerez/.cache/coursier/v1/https/repo1.maven.org/maven2/ch/epfl/scala/com-microsoft-java-debug-core/0.34.0%252B9/com-microsoft-java-debug-core-0.34.0%252B9-sources.jar
```

![image](https://user-images.githubusercontent.com/13123162/197735999-a6f49fd4-896b-418b-91f0-86115996d104.png)

### Expected behavior

Metals should open the `IEvaluationProvider.java` file in the sources jar.

### Operating system

Linux

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment] 2022-10-25 09:35
Thanks for reporting! This looks like a duplicate of https://github.com/scalameta/metals/issues/4357

There is a potential fix in https://github.com/scalameta/metals/pull/4560 which I haven't yet tested, though the issues with opening jars within java is causing a lot of headache :/

**Comment by tgodzik** [comment] 2022-11-02 17:49
Looks like it's still failing, seems that we are double escaping %, which might be the cause.

**Comment by tgodzik** [comment] 2022-11-03 09:30
Let's come back to this later on, #4595 is a workaround for now.

**Comment by tgodzik** [comment] 2023-02-16 16:14
Looks like this is working, just checked in scala-debug-adapter repo

**Closed by tgodzik** 2023-02-16 16:14 UTC
Labels: bug, navigation
