### ISSUE TITLE
Fatal recursive dependency on local project

### ISSUE THREAD

**Issue by rjraya** [scalameta/metals#2198] opened 2020-11-10 15:14 UTC
**General context**

I'm working on a project called _Stainless_ which builds on another project called _Inox_. I want to be able to navigate to definitions by doing control + click on a keyword. I would like to edit _Inox_ code after navigating to it through the _Stainless_ code. Originally, my [build.sbt](https://github.com/epfl-lara/stainless/blob/master/build.sbt) file used an online version of _Inox_ and not the local copy. So I could navigate to _Inox_ definitions, but any changes on their code were erased after closing the files. Now I'm using another [build.sbt](https://github.com/jad-hamza/stainless/blob/master-with-local-inox/build.sbt) file that will use the local copy of _Inox_ placed in the ../ directory relative to the _Stainless_ directory of my machine. However, the following bug is encountered:

**Bug description**

After loading _Stainless_ on VSCode, I get the following error on the right lower part of the screen:

> Fatal recursive dependency detected in 'root-test': List(root-test, stainless-core-test,root-test)
> 
> Source: Scala (Metals) (Extension)

**To Reproduce**

1. Clone [Inox](https://github.com/epfl-lara/inox) and [Stainless](https://github.com/jad-hamza/stainless/). Place them on the same folder. On Stainless, checkout the tracked branch master-with-local-inox.
2. Optionally, in the Stainless folder, run `sbt clean` and `sbt universal:stage` to compile the program. Open VSCode. If needed delete the .bloop file. 
3. Import the sbt file when required by VSCode. 
4. See error at the right lower part of the screen. 

**Expected behavior**

The error itself does not prevent me from writing code in VSCode but it seems to interfere with Metals functionality. I can no longer navigate to definitions. In particular, to Inox definitions. 

**Screenshots**

**Installation:**

- Operating system: Linux
- Editor: Visual Studio Code
- Metals version: v1.9.5

**Additional context**

This is related to  #768 and #1049. However, there the problem occurred while working with a dependency to be found online.

**Search terms**

**Comment by rjraya** [comment] 2020-11-10 15:50
After renaming `root` to `stainlessroot` and `inoxroot` in the corresponding files. The error disappears. However, I cannot navigate to many definitions both in Inox and Stainless. Including definitions I could navigate previously in Stainless.

**Comment by tgodzik** [comment] 2020-11-11 12:41
Thanks for reporting! The issue is probably connected to the identically named modules, Bloop doesn't allow for that unfortunately and I doubt we will change it anytime soon.

With the changed names this should work though. I will need to try to reproduce your issue.

**Comment by tgodzik** [comment] 2020-11-11 13:15
I checked out the repositories and it seems inox is not being found and compiled by Bloop. This is most likely connected to https://github.com/scalacenter/bloop/issues/1002.

The alternative would be to checkout inox as a submodule or use sbt BSP, which has been recently introduced. More info here: https://github.com/scalacenter/bloop/issues/1002

**Comment by tgodzik** [comment] 2020-11-12 16:41
I am closing this as it's not possible to fix in the current Bloop plugin, the alternative is sbt BSP, which should work without problems.

**Closed by tgodzik** 2020-11-12 16:41 UTC
Labels: won't fix

**Comment by mbovel** [comment] 2023-01-11 13:57
I am faced with the same issue today.

As @rjraya mentioned, renaming the respective parent and child projects so that they are not both called `root` solve the “Fatal recursive dependency” error.

Then, using the Bloop server, code navigation doesn't work at all.

Using the SBT sever, code navigation works only in the parent project, but not in child projects. That is, importing `scala-smtlib` from `inox` with `lazy val smtlib = RootProject(file("../scala-smtlib")), Metals Doctor shows:

<img width="1249" alt="image" src="https://user-images.githubusercontent.com/777748/211824381-5eaac98a-5f52-4720-9c2c-e4558a528843.png">

**Comment by tgodzik** [comment] 2023-01-11 14:18
Looks like the issue is that we are unable to add the `metals.sbt` plugin file to the other project.  Maybe you can copy it over to ../scala-smtlib project dir?

**Comment by mbovel** [comment] 2023-01-11 15:32
> Looks like the issue is that we are unable to add the `metals.sbt` plugin file to the other project. Maybe you can copy it over to ../scala-smtlib project dir?

Youhou, indeed, that works! Thanks! 😄

**Comment by mbovel** [comment] 2023-01-11 15:40
For the record, this is what I did:
1. Clone `inox` and `stainless` in the same dir,
2. Rename root SBT projects so that they are not all named `root`,
3. Setup inox dependency in stainless to use the local repo: uncomment `RootProject(file("../inox"))` in `stainless/build.sbt`.
4. Open both project with VSCode, set build server to SBT and ”Import Build“ , first inox and then stainless.

Now I can code  :sunglasses:
