### ISSUE TITLE
Need a command to delete and regenerate snapshot text

### ISSUE THREAD

**Issue by tribbloid** [scalameta/metals#7070] opened 2024-12-25 23:11 UTC
### Is your feature request related to a problem? Please describe.

yes, a metals bug: https://github.com/scalameta/metals/issues/7064

### Describe the solution you'd like

The metals server frequently give the following error message:

```
2024.12.25 17:47:45 INFO  compiling core (94 scala sources)
2024.12.25 17:47:49 INFO  time: compiled core in 3.81s
2024.12.25 17:48:00 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
2024.12.25 18:00:23 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
2024.12.25 18:00:23 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
2024.12.25 18:00:23 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
2024.12.25 18:00:23 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
2024.12.25 18:00:53 WARN  Could not load snapshot text for /home/peng/git/spookystuff/prover-commons/module/core/src/main/scala/ai/acyclic/prover/commons/graph/Engine.scala
```

this is problematic, snapshot text should be generated from source code, either manually or automatically

### Describe alternatives you've considered

N/A

### Search terms

snapshot text, metals

**Comment by tgodzik** [comment] 2024-12-27 15:15
Ach, looks like with the new scope this is a duplicate of https://github.com/scalameta/metals/issues/7064

**Closed by tgodzik** 2024-12-27 15:15 UTC
