### ISSUE TITLE
adding scalaOption utf-8 encoding in build sbt result in no code suggestions

### ISSUE THREAD

**Issue by awouda** [scalameta/metals#1424] opened 2020-02-13 06:12 UTC
**Describe the bug**

Having  "-encoding", "utf-8" as ScalaOptions in my build.sbt file,
I get 
`Feb 13, 2020 6:57:17 AM scala.meta.internal.pc.CompilerAccess handleError
SEVERE: requirement failed: List(UTF-8)
java.lang.IllegalArgumentException: requirement failed: List(utf-8)
	at scala.Predef$.require(Predef.scala:281)`

In the metals.log and code suggestions do not work.

**To Reproduce**
Add in build.sbt
`
scalacOptions ++= Seq(
  "-deprecation",                      // Emit warning and location for usages of deprecated APIs.
  // disabled this encoding flag, if enabled, Scala Metals doesn't build correctly
  "-encoding", "utf-8",                // Specify character encoding used by source files.
)`

scala version is 2.12.10
Using Visual Studio Code
`Version: 1.42.0
Commit: ae08d5460b5a45169385ff3fd44208f431992451
Date: 2020-02-06T10:51:23.649Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-29-generic`

See metals log for the List(utf-8) error. Also in a source file code suggestions do not work.

**Expected behavior**

No java.lang.IllegalArgumentException in metals.log, and working code suggestions

**Installation:**
- Linux m5510 5.3.0-29-generic #31-Ubuntu SMP Fri Jan 17 17:27:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- VS Code 1.42.0
- Metals version: v0.8.0
- openjdk version "1.8.0_232"

**Comment by gabro** [comment] 2020-02-13 06:21
Hi, thanks for reporting!
This is a duplicate of https://github.com/scalameta/metals/issues/1303 which is already fixed in master.
You can work around this by either removing the offending option or by using the latest snapshot (more info on this on the website)

**Closed by gabro** 2020-02-13 06:21 UTC

**Comment by awouda** [comment] 2020-02-13 06:39
ok, sorry missed 1303, my google skills are degrading.. 
Thanks.
