### ISSUE TITLE
Extract xyz as value

### ISSUE THREAD

**Issue by kpodsiad** [scalameta/metals#4574] opened 2022-10-27 20:04 UTC
### Describe the bug

Not sure if this is a bug or rather an improvement.

Execute `extract .. as value`
```scala
//> using scala "2.13.10"

object Extract {
  def test(name: String)(fun: => Any)

  test("foo") {
    Vector(1,2,3,4).fi@@lter(_ % 2 == 0)
  }
}
```

result:
```scala
//> using scala "2.13.10"

object Extract {
  def test(name: String)(fun: => Any)

  val newValue = {
    Vector(1,2,3,4).filter(_ % 2 == 0)
  }
  test("foo") (newValue)
}
```

### Expected behavior

Braces are kept and not switched to parens.
```scala
//> using scala "2.13.10"

object Extract {
  def test(name: String)(fun: => Any)

  test("foo") {
    val newValue = Vector(1,2,3,4).filter(_ % 2 == 0)
  }
}
```

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

v0.11.9

**Comment by tgodzik** [comment] 2022-10-28 14:58
Thanks for reporting! This is an expected behaviour since we are in an apply and we want to extract the whole block. There are some scenarios that a user would rather extract it outside. 

There might be some improvements to do here, but I don't think it should work like this:
```
  test("foo") {
    val newValue = Vector(1,2,3,4).filter(_ % 2 == 0)
  }
```
since this is not really extracting but just assigning to value, so it's outside the scope of this code action.

**Comment by tgodzik** [comment] 2022-11-02 16:16
Will close it since I think it's working as intended. We can create a feature request if needed.

**Closed by tgodzik** 2022-11-02 16:16 UTC
