### ISSUE TITLE
IndexOutOfBoundsException when doing completion on certain symbol

### ISSUE THREAD

**Issue by Poytr1** [scalameta/metals#1662] opened 2020-04-23 12:23 UTC
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

1. Open a new Scala file
2. Type "package o"
3. No suggestions and `IndexOutOfBoundsException` occurs

**Expected behavior**

Should have completion suggestions like `org`

**Screenshots**

![image](https://user-images.githubusercontent.com/20534718/80098834-16ae3a80-85a0-11ea-9d4e-c7458ee01abf.png)

**Installation:**

- Operating system: Windows
- VSCode version: 1.44.2
- VSCode extension version: 1.8.6
- Metals version: 0.8.4

**Stacktrace**

```
[Error - 8:09:36 PM] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.IndexOutOfBoundsException: 1
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:673)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:646)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1(CancelTokens.scala:40)
	at scala.meta.internal.metals.CancelTokens$.$anonfun$future$1$adapted(CancelTokens.scala:36)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: 1
	at scala.reflect.internal.util.BatchSourceFile.lineToOffset(SourceFile.scala:188)
	at scala.meta.internal.pc.AutoImports.autoImportPosition(AutoImports.scala:66)
	at scala.meta.internal.pc.AutoImports.autoImportPosition$(AutoImports.scala:43)
	at scala.meta.internal.pc.MetalsGlobal.autoImportPosition(MetalsGlobal.scala:25)
	at scala.meta.internal.pc.CompletionProvider.importPosition$lzycompute$1(CompletionProvider.scala:68)
	at scala.meta.internal.pc.CompletionProvider.importPosition$1(CompletionProvider.scala:68)
	at scala.meta.internal.pc.CompletionProvider.$anonfun$completions$1(CompletionProvider.scala:141)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:461)
	at scala.collection.Iterator.toStream(Iterator.scala:1417)
	at scala.collection.Iterator.toStream$(Iterator.scala:1416)
	at scala.collection.AbstractIterator.toStream(Iterator.scala:1431)
	at scala.collection.Iterator.$anonfun$toStream$1(Iterator.scala:1417)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.StreamIterator.$anonfun$next$1(Stream.scala:1061)
	at scala.collection.immutable.StreamIterator$LazyCell.v$lzycompute(Stream.scala:1050)
	at scala.collection.immutable.StreamIterator$LazyCell.v(Stream.scala:1050)
	at scala.collection.immutable.StreamIterator.hasNext(Stream.scala:1055)
	at scala.collection.convert.Wrappers$IteratorWrapper.hasNext(Wrappers.scala:31)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:134)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.CollectionTypeAdapter.write(CollectionTypeAdapter.java:40)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:125)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:243)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:423)
	at org.eclipse.lsp4j.jsonrpc.json.adapters.MessageTypeAdapter.write(MessageTypeAdapter.java:55)
	at com.google.gson.Gson.toJson(Gson.java:669)
	at com.google.gson.Gson.toJson(Gson.java:648)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:145)
	at org.eclipse.lsp4j.jsonrpc.json.MessageJsonHandler.serialize(MessageJsonHandler.java:140)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageConsumer.consume(StreamMessageConsumer.java:59)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.lambda$handleRequest$1(RemoteEndpoint.java:281)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:670)
	... 9 more
```

**Search terms**

**Comment by Poytr1** [comment] 2020-04-25 03:11
@tgodzik Thanks for your input.

`New Scala File` option would be very useful during my development :)

Here I actually just created a new file under the project root, not under a folder like `main/src/scala/foo/bar`, so I'm not sure if it affected the code intelligence's behavior. I think the metals was trying to give a `org` suggestion here right?

**Comment by tgodzik** [comment] 2020-04-27 11:30
If you create a file under root Metals will work only with the basic Presentation Compiler that just provides the scala library. A number of features will not work in this case, since we don't actually know anything about the classpath or dependencies.

> I think the metals was trying to give a org suggestion here right?

Not 100% sure where that might have come from, but it's possible it was suggested by Metals.

**Comment by ckipp01** [comment] 2020-09-03 17:57
So I started looking at this tonight. I believe that this is now fixed. Testing with the current snapshot, the `package o` example originally given by @Poytr1 no longer happens, and I'm unable to reproduce with the reproduction that you have listed @tgodzik. I did go back to `0.8.4` and I was able to reproduce it the, but not on the current version. I believe we can close this.

**Comment by tgodzik** [comment] 2020-09-04 08:58
Cool! I can't reproduce it either anymore. Thanks for checking @ckipp01 !

**Closed by tgodzik** 2020-09-04 08:58 UTC
Labels: bug, presentation-compiler
