### ISSUE TITLE
Funky behavior when creating new file

### ISSUE THREAD

**Issue by odersky** [scalameta/metals#4063] opened 2022-06-24 12:20 UTC
### Describe the bug

In VSCode + Metals

Create new file %n

 - Gives a new tab Untitled-2

In that tab, click save %s

 - Opens a form to enter the file name
 
Choose `foo.scala` somewhere in your project directory (say, `dotty`). 

 - Creates a _new_ tab named `foo.scala` and adds the line `package dotty` at the top.

 - The original tab Untitled-2 stays open.
  
 

### Expected behavior

I would expect it to use & rename the Untitled tab.

I also would expect it to add a package clause only to an empty file, but not if the file is already written.

### Operating system

macOS

### Editor/Extension

VS Code

### Version of Metals

latest

**Comment by tgodzik** [comment] 2022-06-27 08:50
Thanks for reporting! I suspect it's the same issue as https://github.com/scalameta/metals/issues/2869 since in those cases it invokes `save as`. 

> The original tab Untitled-2 stays open.

I wasn't able to reproduce that one, it changed the tab to the new name for me. Does it happen every time in your case?

**Comment by tgodzik** [comment] 2022-07-01 08:45
I will close this one since it's already covered in the other issue.

**Closed by tgodzik** 2022-07-01 08:45 UTC
