### ISSUE TITLE
Go to definition for exports

### ISSUE THREAD

**Issue by susliko** [scalameta/metals#5140] opened 2023-04-13 14:56 UTC
### Describe the bug

An attempt to go to definition at `Bar.foo` in the following code
```scala
object Foo:
  def foo = "foo"

object Bar:
  export Foo.*

object Buz:
  Bar.fo@@o
```

leads to `object Bar`

Scala version: 3.3.0-RC3

### Expected behavior

Not sure, which of the following behaviours is preferable:
1. jump to the line `export Foo.*`
2. jump to the line `def foo`
3. add both locations to the jump list

I'm leaning to the last one

### Operating system

macOS

### Editor/Extension

Nvim (nvim-metals)

### Version of Metals

v0.11.11

**Comment by tgodzik** [comment] 2023-04-13 16:33
Thanks for reporting! This is a duplicate of https://github.com/scalameta/metals/issues/4325 something we need to work on at some point.

**Closed by tgodzik** 2023-04-13 16:33 UTC
